### ISSUE TITLE
santactl/fileinfo Rule daemon connectivity issues

### ISSUE THREAD

**Issue by arubdesu** [google/santa#102]
This probably isn't Sierra-specific because I think I've seen `fileinfo` issues in the past, but if I'm going to be able to wrap this in a puppet/chef wrapper, I want to be able to reliably target a path to tell if an item is whitelisted. With 0.9.13 on 10.12.0, I'm seeing a certain machine failing to access the Rule key with the `fileinfo` verb on the same uptime session as lockdown was applied (not saying correlation is causation, just mentioning). I've HUP'd the daemon without being able to resuscitate it, I see
`Calculating 1/1`
and then `Cannot communicate with daemon`.

**Comment by tburgin** [comment]
I have seen this a few time before as well. I will take a closer look. Typically only while santad is under a heavy load.

**Comment by arubdesu** [comment]
Tried as much as a reboot and as little as a kext unload coupled with the daemon HUP, have two machines (and growing, as I get more folks into lockdown mode in our canaries group) that consistency display this system with any output from `fileinfo`

**Comment by arubdesu** [comment]
Found my issue, the daemon really is down, and respawning every second when I've gone into lockdown by setting ClientMode to 2. 
```
[2016-09-23T20:45:40.280Z] E Santa: Could not read configuration file: The file “config.plist” couldn’t be opened because you don’t have permission to view it., replacing.
[2016-09-23T20:45:43.762Z] I santad: Started, version 0.9.13
[2016-09-23T20:45:44.918Z] I santad: Started, version 0.9.13
[2016-09-23T20:45:46.073Z] I santad: Started, version 0.9.13
```
I'm setting that key with defaults write as sudo and it's root:wheel 600, so I'm not sure why this is what I'm observing.

**Comment by russellhancox** [comment]
I think this is related to the file watcher code not working properly on
10.12. After using defaults chmod the file back to 644.

**Comment by arubdesu** [comment]
`chmod`ing to 644 doesn't seem to be alleviating the situation, still getting the configuration file read error. Tried removing the BlacklistRegex key which was also in place, no change.

**Comment by russellhancox** [comment]
Does `plutil -lint` say the file is valid? That and permissions are the two possible causes of that error.

**Comment by arubdesu** [comment]
Yup,
```
$ sudo plutil -lint /var/db/santa/config.plist 
/var/db/santa/config.plist: OK
$ ls -l /var/db/santa/config.plist
-rw-r--r--  1 root  wheel  59 Sep 26 09:23 /var/db/santa/config.plist
```
And still seeing the `E` error on load and every-second `I santad: Started, version 0.9.13` in the log

**Comment by russellhancox** [comment]
Hang on, if santad is restarting every second it must be crashing. Are there crash reports in /Library/Logs/DiagnosticReports?

**Comment by arubdesu** [comment]
yup, pardon. 
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString longValue]: unrecognized selector sent to instance 0x3215'
abort() called
terminating with uncaught exception of type NSException
```

[santad_2016-09-26-103825_odapl17.crash.txt](https://github.com/google/santa/files/493335/santad_2016-09-26-103825_odapl17.crash.txt)

**Comment by russellhancox** [comment]
Looks like the ClientMode key is not able to be converted to a number or the file is being read as a string. What does this return?

`defaults read /var/db/santa/config.plist ClientMode`

**Comment by arubdesu** [comment]
```
$ sudo defaults read /var/db/santa/config.plist
{
    ClientMode = 2;
}
```

**Comment by russellhancox** [comment]
I forgot defaults doesn't give you any indication of a value's type but I've managed to reproduce this by forcing it to be a string. Try this:

`defaults write /var/db/santa/config.plist ClientMode -int 2`

**Comment by arubdesu** [comment]
ಠ_ಠ. That was it... Pardon the bother

**Comment by russellhancox** [comment]
We should handle this case properly, it's not unreasonable to use defaults without a type. Fix incoming
