### ISSUE TITLE
Mechanism to detect a rule is present without artifacts on-disk

### ISSUE THREAD

**Issue by arubdesu** [google/santa#103]
Currently the only way (I can think of) you could tell if a rule is present, without having a file present that there is a rule for, is 1. stopping the daemon and 2. dumping the rules db to check for the sha256. Something along the lines of a 'check' subcommand to santactl's `rule` verb would allow the previously hinted-at configuration management-based control, so we can verify whether or not a sha256 is present before adding it.

**Comment by tburgin** [comment]
Included in v0.9.18
