### ISSUE TITLE
Metrics Server Endpoint Not Getting Called

### ISSUE THREAD

**Issue by eopeter** [google/santa#1032]
I am looking to get Santa metrics to my backend but the endpoint configured in the mobile config never gets call. Do I need to do something special to enable it? The following is what my `santactl status` response looks like:

```bash
user$ santactl status
>>> Daemon Info
  Mode                      | Monitor
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 12  (Peak: 34.81%)
  Watchdog RAM Events       | 288  (Peak: 361.76MB)
>>> Cache Info
  Root cache count          | 938
  Non-root cache count      | 18
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 0
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 0
>>> Sync Info
  Sync Server               | https://XXXX/v1/santa/
  Clean Sync Required       | Yes
  Last Successful Full Sync | Never
  Last Successful Rule Sync | Never
  Push Notifications        | Disconnected
  Bundle Scanning           | Yes
  Transitive Rules          | Yes
>>> Metrics Info
  Metrics Server            | https://XXXX/metrics/santa
  Export Interval (seconds) | 30
```

I expected Santa to POST a payload to `https://XXXX/metrics/santa` every 30 seconds

These are the settings in my mobile config related to metrics:

```xml
<key>MetricURL</key>
<string>https://XXXX/metrics/santa</string>
<key>MetricFormat</key>
<string>rawjson</string>
```

**Comment by pmarkowsky** [comment]
Those are the right keys.  Are you seeing an error messages from the `santametricservice` in the logs in `Console.app` or `log stream --predicate 'processImagePath CONTAINS[c] "santametricservice"'`?

**Comment by eopeter** [comment]
I left the above command running for the last hour and there are no logs; I do not see any error messages

**Comment by pmarkowsky** [comment]
@eopeter is the `santametricservice` started? 

You should see logs when the daemon starts up. Alternatively you can run the `santametricservice` in the foreground and then tailing the logs with the same command.

**Comment by eopeter** [comment]
@pmarkowsky Yes the service is started. As shown below. I stopped it and started it manually and ran it for a while and still nothing.

Started Manually
```bash
$ /Applications/Santa.app/Contents/MacOS/santametricservice
Started, version 2022.11.490266363
```

No Logs 
```bash
$ log stream --predicate 'processImagePath CONTAINS[c] "santametricservice"'
Filtering the log data using "processImagePath CONTAINS[c] "santametricservice""
```

Before I started manually, this is what the setup was. The metric service is running as 'nobody'

```bash
launchctl list | grep santa

579	0	com.google.santa.syncservice
417	0	EQHXZ8M8AV.com.google.santa.daemon
328	0	com.google.santa.metricservice
-	0	com.google.santa.bundleservice
-	78	com.linkedin.security.guardin.santa.listener
```

<img width="902" alt="image" src="https://user-images.githubusercontent.com/2012979/217095745-250ec88d-9023-413c-a731-839a2b34c4fb.png">

**Comment by pmarkowsky** [comment]
That seems really odd. You should always see a log message when the daemon starts up.  Can you reproduce this behavior with the latest version of Santa?

**Comment by eopeter** [comment]
Latest seems to resolve the issue. Thank you!
