### ISSUE TITLE
Support regex binary paths in File Authorization rules

### ISSUE THREAD

**Issue by slashnick** [google/santa#1057]
**My use case**
I want to use File Authorization to restrict file access for `~/Library/Application Support/Google/Chrome/*/Cookies` to just Google Chrome. 

On my machine, the binary that opens this file is `/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/111.0.5563.110/Helpers/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper`. The `111.0.5563.110` version number changes often when Chrome auto-updates.

I could add a Process rule using TeamID, but that would allow any Google-signed application (eg. Google Drive) to open this file.

**Proposal**
Add a new optional BinaryPathRegex option to WatchItems -> Processes. I suppose this option should be mutually exclusive with BinaryPath.

With the example above, one could write a Process rule like:

```
<dict>
  <key>TeamID</key>
  <string>EQHXZ8M8AV</string>
  <key>BinaryPathRegex</key>
  <string>^/Applications/Google Chrome\.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/([\d\.]+)/Helpers/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper$</string>
</dict>
```

**Alternative - support symlinks in BinaryPath**

In `Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/` contains `Current`, which is a symlink for `111.0.5563.110`.

Maybe I could set BinaryPath to `.../Versions/Current/...` instead of `.../Versions/111.0.5563.110/...`. Santa could resolve symlinks in BinaryPath rules to figure out the actual underlying file.

For the Chrome use case in particular, it's tricky to figure out when Santa should resolve BinaryPath to its absolute path, since users might update Chrome while santad is running. I think the options are:
- Resolve BinaryPath every time the file access watch item is matched
  - Involves file IO in a hot path
- Periodically resolve BinaryPath when the File Access Policy is applied
  - Fast
  - Chrome will be broken for `FileAccessPolicyUpdateIntervalSec` seconds after updating until Santa sees that the symlink has changed

**Comment by mlw** [comment]
The public docs have not yet been updated, but a feature was recently added to support exceptions based on Signing ID as well. So an example configuration could look like:

```
<dict>
  <key>TeamID</key>
  <string>EQHXZ8M8AV</string>
  <key>SigningID</key>
  <string>com.google.Chrome.helper</string>
</dict>
```
See [WatchItems.mm](https://github.com/google/santa/blob/main/Source/santad/DataLayer/WatchItems.mm#L303)

Because the per-dict options are `AND`ed together, this would ensure that only the Chrome helper app signed by Google (and not other Google-signed things) would be allowed.

This seems like it should work for the stated use case and gracefully handle update scenarios without overhead of regex matching on a hot-ish path.

**Comment by slashnick** [comment]
Amazing! That seems a lot better than regex matching
