### ISSUE TITLE
Display proper notifications when file system monitoring denies an operation

### ISSUE THREAD

**Issue by mlw** [google/santa#1084]
When access is denied, an appropriate event is added to the santa log. However there is no user-facing messaging.

A new UI is needed with appropriate path and process information displayed that should look similar to the current blocked binary dialog. Additionally, a message should be written to the TTY when appropriate.

**Comment by pmarkowsky** [comment]
@mlw is there anything more to do with this?

**Comment by pmarkowsky** [comment]
Talked with @mlw. This is definitely closed as per the release notes in 2023.8.
