### ISSUE TITLE
Add per-rule customized URLs

### ISSUE THREAD

**Issue by russellhancox** [google/santa#1087]
## Overview

The UI that displays block notifications currently has a single "Open.." button that can open a single site with templated values from the blocked execution. For some block rules, it would be nice to be able to customize the URL to be completely different or disable the button altogether.

## Proposal

Add a `custom_url` field to the Rule type that can be populated from a sync server and will be stored in the rules database (similarly to the `custom_msg` field). When a notification is displayed:

* If the field contains a valid URL, the "Open" button will open this URL instead of the normal templated URL from the config. If the GUI config normally customizes the button's text, that customization will be ignored and the label will say `Open...`.
* If the field contains the string `null`, the button will not be shown on the dialog.
* Any other value, or a missing value for that rule will show the normal button.

**Comment by mlw** [comment]
fixed by #1140
