### ISSUE TITLE
launchctl returns -6 (abort) status for EQHXZ8M8AV.com.google.santa.daemon

### ISSUE THREAD

**Issue by junomonster** [google/santa#1092]
## Problem

```
% santactl status
An error occurred communicating with the daemon, is it running?

% sudo launchctl list | grep santa
-	0	com.google.santa.syncservice
-	-6	EQHXZ8M8AV.com.google.santa.daemon
1294	0	com.google.santa.metricservice
-	0	com.google.santa.bundleservice
```

## Environment

```
% systemextensionsctl list
3 extension(s)
--- com.apple.system_extension.network_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	VBG97UB4TA	com.objective-see.lulu.extension (2.4.2/2.4.2)	Extension	[activated enabled]
--- com.apple.system_extension.endpoint_security
enabled	active	teamID	bundleID (version)	name	[state]
		EQHXZ8M8AV	com.google.santa.daemon (2023.4/2023.4.527579445)	santad	[terminated waiting to uninstall on reboot]
*	*	EQHXZ8M8AV	com.google.santa.daemon (2023.4/2023.4.527579445)	santad	[activated enabled]

% ps aux | grep santa
juno              1447   0.0  0.0 407962720     48 s000  S+    3:14PM   0:00.00 grep santa
nobody            1294   0.0  0.0 408667232   5488   ??  Ss    3:07PM   0:00.02 /Applications/Santa.app/Contents/MacOS/santametricservice --syslog

% santactl version
santad          | 2023.4 (build 527579445)
santactl        | 2023.4 (build 527579445)
SantaGUI        | 2023.4 (build 527579445)
```

MacOS Version: 13.3.1 (a) (22E772610a)
Lockdown Mode: On
Other system softwares that may affect santa?:
- blockblock
- lulu
- wireguard
- openvpn

## What I did
- Reinstall santa through dmg file on the release page
- `/Applications/Santa.app/Contents/MacOS/Santa --unload-system-extension` and `/Applications/Santa.app/Contents/MacOS/Santa --load-system-extension`
- Give full disk access permission to Santa.app
- Reboot

**Comment by junomonster** [comment]
I resolved it myself.

When I checked dmesg, I accidentally found the error message from sandboxd that com.google.santa.daemon did not have full disk permission.

```
% sudo dmesg | grep santa
... sandboxd deny santa blahblah TCCFullDisk ...
```

So I checked "Full Disk Access" security tab on MacOS system configuration, yeah there was "com.google.santa.daemon" which was not seen before I reboot some times.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/91265970/236662103-18a5f0ae-a2ca-474f-af72-7661fd37e260.png">

Anyway, after allowing "com.google.santa.daemon", it works.

```
% santactl status
>>> Daemon Info
  Mode                      | Monitor
  Log Type                  | file
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 0  (Peak: 0.14%)
  Watchdog RAM Events       | 0  (Peak: 6.22MB)
>>> Cache Info
  Root cache count          | 4
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 0
```

**Comment by junomonster** [comment]
And, another useful thing to know is:
As https://santa.dev/deployment/configuration.html#mdm-specific-client-configuration mentioned that end-user who did not specify MDM cannot install the example configurations (TCC full disk allow, allow extension automatically).

![image](https://user-images.githubusercontent.com/91265970/236662269-2329b8ae-9faf-422c-9397-4f464dc53431.png)

**Comment by arubdesu** [comment]
Lockdown mode is certainly another curveball your setup posed versus the more commonly expected use case, as at least a user-approved if not Device Enrollment Program-enrolled MDM is expected to be in place. Without that 'supervised' mode being enabled, even a signed MDM profile cannot affect the changes needed to allow the system extension.
