### ISSUE TITLE
After turning on the clean_sync switch, the event logs are no longer being uploaded

### ISSUE THREAD

**Issue by izzh** [google/santa#1101]
Hey:
In the profile, I set _EnableAllEventUpload_ and _SyncEnableCleanSyncEventUpload_ to **true**. 
Additionally, I sent the _clean_sync_ field to the santa client through the sync server and set it as **true**. 
However, I noticed that aside from block event logs that occasionally upload, the event logs of Allow_XXX type are not being uploaded. 
My understanding was that all logs should be uploaded like they were when _clean_sync_ was set to **false**. Unfortunately, since I am not familiar with OC language, I was unable to comprehend the logic by reading the source code. Did I misunderstand something?

my santa client version: 
```
santad          | 2023.1 (build 503475832)
santactl        | 2023.1 (build 503475832)
SantaGUI        | 2023.1 (build 503475832)
```

**Comment by mlw** [comment]
My local efforts to repro were not successful - I am able to log all events in the events database.

One potential issue might be that the `EnableAllEventUpload` key is getting overridden by the sync server? You can confirm this by checking the value of: `grep -A1 EnableAllEventUpload /var/db/santa/sync-state.plist`

**Comment by izzh** [comment]
I checked and confirmed that _EnableAllEventUpload_ exists, but _SyncEnableCleanSyncEventUpload_ does not.

```
(base) root@localhost ushare # grep -A1 EnableAllEventUpload /var/db/santa/sync-state.plist           
	<key>EnableAllEventUpload</key>
	<true/>
(base) root@localhost ushare # grep -A1 SyncEnableCleanSyncEventUpload  /var/db/santa/*.plist
(base) root@localhost ushare #
```

**Comment by izzh** [comment]
> My local efforts to repro were not successful - I am able to log all events in the events database.
> 
> One potential issue might be that the `EnableAllEventUpload` key is getting overridden by the sync server? You can confirm this by checking the value of: `grep -A1 EnableAllEventUpload /var/db/santa/sync-state.plist`

The events should be recorded in the events database, but when calling the _/eventupload/<machine_id>_ API to transmit the events to the sync server, they are being cleared, resulting in the sync server not receiving any event data.

**Comment by mlw** [comment]
I see, I maybe misinterpreted what you're saying. So you believe that you are indeed storing all events into the events.db as I saw, but during a sync, when the `clean_sync` flag is set, nothing is uploaded.

The logic for when things are uploaded is in [SNTSyncEventUpload.m](https://github.com/google/santa/blob/2023.4/Source/santasyncservice/SNTSyncEventUpload.m#L58):
```objc
if (!self.syncState.cleanSync || [[SNTConfigurator configurator] enableCleanSyncEventUpload]) {
```

If `clean_sync` is set, items should still be uploaded presuming that the `SyncEnableCleanSyncEventUpload` key is also set. In the original comment, it is mentioned that this is set, but it is worth confirming. Do you get an appropriate value after running the folowing?

```
sudo grep -A1 SyncEnableCleanSyncEventUpload /Library/GoogleCorpSupport/Profiles/com.google.corp.gmac.santa.mobileconfig
```

**Comment by mlw** [comment]
Helpful suggestion from @russellhancox to query the profile directly:
```
sudo profiles list -verbose -o stdout-xml | grep -A1 SyncEnableCleanSyncEventUpload
```

**Comment by izzh** [comment]
> Helpful suggestion from @russellhancox to query the profile directly:
> 
> ```
> sudo profiles list -verbose -o stdout-xml | grep -A1 SyncEnableCleanSyncEventUpload
> ```

Using this command to query, the value of the _SyncEnableCleanSyncEventUpload_ field is indeed configured.
```
(base) root@localhost ~ # sudo profiles list -verbose -o stdout-xml | grep -A1 SyncEnableCleanSyncEventUpload
											<key>SyncEnableCleanSyncEventUpload</key>
											<true/>
(base) root@localhost ~ #
```
Is there an issue with the implementation of this part of the code? Could you please help to check it carefully? Thank you~

**Comment by izzh** [comment]
> /eventupload/<machine_id>

The sync server was implemented by me in Java based on the sync protocol. Below is the process I reproduced, including the status information of the Santa client and the sync server logs. 

1.When the sync server sets the **clean_sync** field to **false**, the event data can be received at /eventupload/<machine_id> API.

**santa client（Upload one event is needed.）：**

```
root@santadeMac ~ # santactl status
>>> Daemon Info
  Mode                      | Lockdown
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 0  (Peak: 8.34%)
  Watchdog RAM Events       | 0  (Peak: 94.21MB)
>>> Cache Info
  Root cache count          | 7
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 1
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 1
>>> Watch Items
  Enabled                   | No
>>> Sync Info
  Sync Server               | https://testX.com/api/santa/
  Clean Sync Required       | No
  Last Successful Full Sync | 2023/05/24 17:01:08 +0800
  Last Successful Rule Sync | 2023/05/24 17:01:08 +0800
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Rules          | Yes
root@santadeMac ~ # santactl sync  
Missing Machine Owner.
Preflight starting
Performing request, attempt 1
Server Trust: /O=(null)/OU=(null)/CN=*.testX.com/SHA-1=X
Preflight complete
Event upload starting
Performing request, attempt 1
Uploaded 1 events
Event upload complete
Rule download starting
Performing request, attempt 1
Received 1 rules
Processed 1 rules
Rule download complete
Postflight starting
Performing request, attempt 1
Postflight complete
Sync completed successfully
```

**sync server（The sync server received one event data.）：**

```
2023-05-24 17:02:09.291 INFO 1 --- [io-7003-exec-14] c.h.c.a.c.HidsSantaServerController : santa preflight request data:{"binary_rule_count":0,"os_version":"13.3.1","santa_version":"2023.1.503475832","certificate_rule_count":0,"serial_num":"C02GF27TMD6R","hostname":"macos-13.1.shared","os_build":"22E261","transitive_rule_count":0,"model_identifier":"Parallels18,1","client_mode":"LOCKDOWN","teamid_rule_count":1,"compiler_rule_count":0,"primary_user":""}
2023-05-24 17:02:09.323 INFO 1 --- [io-7003-exec-14] h.c.s.s.i.HidsSantaClientInfoServiceImpl : response data and machine_id：jsonObject:{"batch_size":100,"enable_transitive_rules":true,"client_mode":"LOCKDOWN","blocked_path_regex":"","full_sync_interval":120,"allowed_path_regex":"","enable_bundles":false,"enable_all_event_upload":true,"clean_sync":false}, 958C4E85-0782-5FE6-9207-746BD15148EC
**2023-05-24 17:02:09.323 INFO 1 --- [io-7003-exec-14] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.getConfigInfo(..) end】, 【result：{"batch_size":100,"enable_transitive_rules":true,"client_mode":"LOCKDOWN","blocked_path_regex":"","full_sync_interval":120,"allowed_path_regex":"","enable_bundles":false,"enable_all_event_upload":true,"clean_sync":false}】【time：33ms】**
2023-05-24 17:02:09.396 INFO 1 --- [io-7003-exec-16] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.eventUpload(..) start】, 【request：[958C4E85-0782-5FE6-9207-746BD15148EC, org.apache.catalina.connector.RequestFacade@392213b3]】
**2023-05-24 17:02:09.397 INFO 1 --- [io-7003-exec-16] c.h.c.a.c.HidsSantaServerController : santa eventUpload data:{"events":[{"parent_name":"launchd","file_path":"/System/Applications/Home.app/Contents/MacOS","logged_in_users":["santa"],"file_bundle_version_string":"7.0","decision":"ALLOW_CERTIFICATE","file_name":"Home","signing_chain":[{"valid_until":1792863581,"sha256":"d84db96af8c2e60ac4c851a21ec460f6f84e0235beb17d24a78712b9b021ed57","org":"Apple Inc.","ou":"Apple Software","valid_from":1603996358,"cn":"Software Signing"},{"valid_until":1792863581,"sha256":"5bdab1288fc16892fef50c658db54f1e2e19cf8f71cc55f77de2b95e051e2562","org":"Apple Inc.","ou":"Apple Certification Authority","valid_from":1319477981,"cn":"Apple Code Signing Certification Authority"},{"valid_until":2054670036,"sha256":"b0b1730ecbc7ff4505142c49f1295e6eda6bcaed7e2c68c5be91b5a11001f024","org":"Apple Inc.","ou":"Apple Certification Authority","valid_from":1146001236,"cn":"Apple Root CA"}],"pid":15151,"file_bundle_name":"Home","file_sha256":"5f9504a936e8a9341e91bcfaba65912cd4fd8fc63786d081ca0cd28d562d33d6","file_bundle_id":"com.apple.Home","ppid":1,"execution_time":1684918905.7145071,"file_bundle_path":"/System/Applications/Home.app","file_bundle_version":"9999.9","current_sessions":["santa@console","santa@ttys000","santa@ttys001","santa@ttys002"],"quarantine_timestamp":0,"executing_user":"santa"}]}**
2023-05-24 17:02:09.482 INFO 1 --- [io-7003-exec-16] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.eventUpload(..) end】, 【result：null】【time：86ms】
2023-05-24 17:02:09.565 INFO 1 --- [io-7003-exec-17] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.getRulesInfo(..) start】, 【request：[958C4E85-0782-5FE6-9207-746BD15148EC, org.apache.catalina.connector.RequestFacade@392213b3]】
2023-05-24 17:02:09.584 INFO 1 --- [io-7003-exec-17] c.h.c.s.s.impl.HidsSantaRuleServiceImpl : machineId:958C4E85-0782-5FE6-9207-746BD15148EC, key:hids:santa:rule:958C4E85-0782-5FE6-9207-746BD15148EC cached rules idList:[287]
2023-05-24 17:02:09.587 INFO 1 --- [io-7003-exec-17] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.getRulesInfo(..) end】, 【result：{"rules":[{"rule_type":"TEAMID","sha256":"EQHXZ8M8AV","custom_msg":"Google Chrome","policy":"ALLOWLIST"}]}】【time：22ms】
2023-05-24 17:02:09.665 INFO 1 --- [io-7003-exec-18] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.postflight(..) start】, 【request：[958C4E85-0782-5FE6-9207-746BD15148EC]】
2023-05-24 17:02:09.671 INFO 1 --- [io-7003-exec-18] h.c.s.s.i.HidsSantaClientInfoServiceImpl : serialNum:C02GF27TMD6R，update heartheat
2023-05-24 17:02:09.684 INFO 1 --- [io-7003-exec-18] c.h.c.a.c.HidsSantaServerController : santa postflight machine_id:958C4E85-0782-5FE6-9207-746BD15148EC
2023-05-24 17:02:09.684 INFO 1 --- [io-7003-exec-18] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.postflight(..) end】, 【result：null】【time：19ms】
```

2.When the sync server sets the **clean_sync** field to **true**, ALLOW_X types of event data cannot be received at /eventupload/<machine_id> API.

**santa client（Upload four events is needed）：**

```
root@santadeMac ~ # santactl status
>>> Daemon Info
  Mode                      | Lockdown
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 0  (Peak: 8.34%)
  Watchdog RAM Events       | 0  (Peak: 94.21MB)
>>> Cache Info
  Root cache count          | 4
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 1
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 4
>>> Watch Items
  Enabled                   | No
>>> Sync Info
  Sync Server               | https://testX.com/api/santa/
  Clean Sync Required       | No
  Last Successful Full Sync | 2023/05/24 16:36:50 +0800
  Last Successful Rule Sync | 2023/05/24 16:36:50 +0800
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Rules          | Yes
root@santadeMac ~ # santactl sync  
Missing Machine Owner.
Preflight starting
Performing request, attempt 1
Server Trust: /O=(null)/OU=(null)/CN=*.testX.com/SHA-1=X
Clean sync requested by server
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Received 1 rules
Processed 1 rules
Rule download complete
Postflight starting
Performing request, attempt 1
Postflight complete
Sync completed successfully
root@santadeMac ~ # 
```

**sync server（The sync server did not receive any event data.）**

```
2023-05-24 16:37:56.839 INFO 1 --- [io-7003-exec-43] c.h.c.a.c.HidsSantaServerController : santa preflight request data:{"binary_rule_count":0,"os_version":"13.3.1","santa_version":"2023.1.503475832","certificate_rule_count":0,"serial_num":"C02GF27TMD6R","hostname":"macos-13.1.shared","os_build":"22E261","transitive_rule_count":0,"model_identifier":"Parallels18,1","client_mode":"LOCKDOWN","teamid_rule_count":1,"compiler_rule_count":0,"primary_user":""}
2023-05-24 16:37:56.871 INFO 1 --- [io-7003-exec-43] h.c.s.s.i.HidsSantaClientInfoServiceImpl : response data and machine_id：jsonObject:{"batch_size":100,"enable_transitive_rules":true,"client_mode":"LOCKDOWN","blocked_path_regex":"","full_sync_interval":120,"allowed_path_regex":"","enable_bundles":false,"enable_all_event_upload":true,"clean_sync":true}, 958C4E85-0782-5FE6-9207-746BD15148EC
**2023-05-24 16:37:56.871 INFO 1 --- [io-7003-exec-43] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.getConfigInfo(..) end】, 【result：{"batch_size":100,"enable_transitive_rules":true,"client_mode":"LOCKDOWN","blocked_path_regex":"","full_sync_interval":120,"allowed_path_regex":"","enable_bundles":false,"enable_all_event_upload":true,"clean_sync":true}】【time：32ms】**
2023-05-24 16:37:56.940 INFO 1 --- [io-7003-exec-44] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.getRulesInfo(..) start】, 【request：[958C4E85-0782-5FE6-9207-746BD15148EC, org.apache.catalina.connector.RequestFacade@2a882726]】
2023-05-24 16:37:56.959 INFO 1 --- [io-7003-exec-44] c.h.c.s.s.impl.HidsSantaRuleServiceImpl : machineId:958C4E85-0782-5FE6-9207-746BD15148EC, key:hids:santa:rule:958C4E85-0782-5FE6-9207-746BD15148EC cached rules idList:[287]
2023-05-24 16:37:56.962 INFO 1 --- [io-7003-exec-44] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.getRulesInfo(..) end】, 【result：{"rules":[{"rule_type":"TEAMID","sha256":"EQHXZ8M8AV","custom_msg":"Google Chrome","policy":"ALLOWLIST"}]}】【time：22ms】
2023-05-24 16:37:57.034 INFO 1 --- [io-7003-exec-45] com.hids.center.api.aop.WebLogAspect : 【HidsSantaServerController.postflight(..) start】, 【request：[958C4E85-0782-5FE6-9207-746BD15148EC]】
2023-05-24 16:37:57.039 INFO 1 --- [io-7003-exec-45] h.c.s.s.i.HidsSantaClientInfoServiceImpl : serialNum:C02GF27TMD6R，update heartbeat
```

The sync server is working properly, but when I set the clean_sync field to true to clear the rule cache, the ALLOW_XXX type event data is also being deleted, and is no longer reported to the sync server. Please help me analyze which step I may have done wrong while using it.

**Comment by izzh** [comment]
> Event upload starting
> Event upload complete

When executing the santactl sync command to call the sync server interface, the behavior is different compared to before.

**Comment by russellhancox** [comment]
It does look like SyncEnableCleanSyncEventUpload is being ignored. Was the profile enabling it installed after Santa was installed and started? Try `sudo killall santasyncservice` to restart the sync service, which will cause it to re-read the values in the profile.

I'd also suggest updating to the latest Santa version. While I don't _think_ there are any changes that would affect this, it's much easier for us to help with the latest version so any other code changes can be ignored.

**Comment by izzh** [comment]
> It does look like SyncEnableCleanSyncEventUpload is being ignored. Was the profile enabling it installed after Santa was installed and started? Try `sudo killall santasyncservice` to restart the sync service, which will cause it to re-read the values in the profile.
> 
> I'd also suggest updating to the latest Santa version. While I don't _think_ there are any changes that would affect this, it's much easier for us to help with the latest version so any other code changes can be ignored.

I updated the profile, added the SyncEnableCleanSyncEventUpload field, and reinstalled the profile while Santa was already installed and running.

I executed the command `sudo killall santasyncservice` but found that it didn't work.

```
root@macos-13 Desktop # killall santasyncservice
root@macos-13 Desktop # santactl status         
>>> Daemon Info
  Mode                      | Lockdown
  Log Type                  | file
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 0  (Peak: 8.99%)
  Watchdog RAM Events       | 0  (Peak: 35.72MB)
>>> Cache Info
  Root cache count          | 5
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 1
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 5
>>> Watch Items
  Enabled                   | No
>>> Sync Info
  Sync Server               | https://testX.com/api/santa/
  Clean Sync Required       | No
  Last Successful Full Sync | 2023/05/25 17:26:37 +0800
  Last Successful Rule Sync | 2023/05/25 17:26:37 +0800
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Rules          | Yes
root@macos-13 Desktop # santactl sync           
Missing Machine Owner.
Preflight starting
Performing request, attempt 1
Server Trust: /O=(null)/OU=(null)/CN=*.testX.com/SHA-1=X
Clean sync requested by server
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Received 1 rules
Processed 1 rules
Rule download complete
Postflight starting
Performing request, attempt 1
Postflight complete
Sync completed successfully
```
I also tried to upgrade Santa to the latest version, but the issue still exists.

```
root@macos-13 ~ # profiles list -verbose -o stdout-xml | grep -A1 SyncEnableCleanSyncEventUpload
                                                                                        <key>SyncEnableCleanSyncEventUpload</key>
                                                                                        <true/>
root@macos-13 ~ # santactl version
santad          | 2023.4 (build 527579445)
santactl        | 2023.4 (build 527579445)
SantaGUI        | 2023.4 (build 527579445)
root@macos-13 ~ # santactl status
>>> Daemon Info
  Mode                      | Lockdown
  Log Type                  | file
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 0  (Peak: 8.99%)
  Watchdog RAM Events       | 0  (Peak: 30.63MB)
>>> Cache Info
  Root cache count          | 5
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 1
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 5
>>> Watch Items
  Enabled                   | No
>>> Sync Info
  Sync Server               | https://testX.com/api/santa/
  Clean Sync Required       | No
  Last Successful Full Sync | 2023/05/25 17:37:08 +0800
  Last Successful Rule Sync | 2023/05/25 17:37:08 +0800
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Rules          | Yes
root@macos-13 ~ # santactl sync  
Missing Machine Owner.
Preflight starting
Performing request, attempt 1
Server Trust: /O=(null)/OU=(null)/CN=*.testX.com/SHA-1=X
Clean sync requested by server
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Received 1 rules
Processed 1 rules
Rule download complete
Postflight starting
Performing request, attempt 1
Postflight complete
Sync completed successfully
root@macos-13 ~ # 
```

**Comment by izzh** [comment]
> 
I have been thinking, if the community doesn't have a good solution, I will temporarily change the strategy for distributing the clean_sync:true field. For example, I will only distribute it to the Santa client once a day, so that we won't lose too many event logs.

**Comment by izzh** [comment]
> 

I tested it with the open source version of sync server, and the problem still exists. Can you provide the profile configuration items during your test and the response body of the preflight interface? I want to compare and confirm whether I have configured something wrong. Thank you~

**Comment by izzh** [comment]
> I ran some additional tests and still have not been able to reproduce the issue.
> 
> I ran a setup to force `clean_sync`, `EnableAllEventUpload` and `SyncEnableCleanSyncEventUpload` to all be true. Further I added some debug log lines around the if-statement linked above. I see this working as expected and attempt event uploads for all events, including `ALLOW_XYZ` events.


I tested it with the open source version of sync server, and the problem still exists. Can you provide the profile configuration items during your test and the response body of the preflight interface? I want to compare and confirm whether I have configured something wrong. Thank you~

**Comment by pmarkowsky** [comment]
Folks have been out for a bit I'll try to get something next week.

**Comment by mlw** [comment]
Due to some internal limitations with installed MDM profiles making it difficult to work around modifying configurations, I instead put together a custom Santa build with the following modifications made that I believe to be a good-faith recreation of the configuration changes described.

1. [SNTSyncPreflight.m:150-153](https://github.com/google/santa/blob/2023.5/Source/santasyncservice/SNTSyncPreflight.m#L150-L153) - At the bottom, force the linked if-condition to always be true so that `self.syncState.cleanSync = YES;` (`clean_sync`)

2. [SNTConfigurator.m:858](https://github.com/google/santa/blob/2023.5/Source/common/SNTConfigurator.m#L858) - Force `enableCleanSyncEventUpload` to always return `YES` (`SyncEnableCleanSyncEventUpload`)

3. [SNTConfigurator.m:863](https://github.com/google/santa/blob/2023.5/Source/common/SNTConfigurator.m#L863) - Force `enableAllEventUpload` to always return `YES` (`EnableAllEventUpload`)

4. [SNTSyncEventUpload.m:59](https://github.com/google/santa/blob/2023.5/Source/santasyncservice/SNTSyncEventUpload.m#L59) - I added a log statement at the top of this if-block that is responsible for first uploading the events ([as previously commented](https://github.com/google/santa/issues/1101#issuecomment-1559776342)).

The above steps allowed me to mimic the configuration items being set. Logs confirmed I was hitting the if-block in step 4, and the event upload took place.

**Comment by izzh** [comment]
> Due to some internal limitations with installed MDM profiles making it difficult to work around modifying configurations, I instead put together a custom Santa build with the following modifications made that I believe to be a good-faith recreation of the configuration changes described.
> 
> 1. [SNTSyncPreflight.m:150-153](https://github.com/google/santa/blob/2023.5/Source/santasyncservice/SNTSyncPreflight.m#L150-L153) - At the bottom, force the linked if-condition to always be true so that `self.syncState.cleanSync = YES;` (`clean_sync`)
> 2. [SNTConfigurator.m:858](https://github.com/google/santa/blob/2023.5/Source/common/SNTConfigurator.m#L858) - Force `enableCleanSyncEventUpload` to always return `YES` (`SyncEnableCleanSyncEventUpload`)
> 3. [SNTConfigurator.m:863](https://github.com/google/santa/blob/2023.5/Source/common/SNTConfigurator.m#L863) - Force `enableAllEventUpload` to always return `YES` (`EnableAllEventUpload`)
> 4. [SNTSyncEventUpload.m:59](https://github.com/google/santa/blob/2023.5/Source/santasyncservice/SNTSyncEventUpload.m#L59) - I added a log statement at the top of this if-block that is responsible for first uploading the events ([as previously commented](https://github.com/google/santa/issues/1101#issuecomment-1559776342)).
> 
> The above steps allowed me to mimic the configuration items being set. Logs confirmed I was hitting the if-block in step 4, and the event upload took place.

Modifying the code and testing it indeed has no problem. Thanks a lot~

**Comment by pmarkowsky** [comment]
@izzh to clarify is this the behavior you're reporting is this.

If you have `EnabledAllEventUpload` set to true and you have 4 pending events then do the following

```mermaid
sequenceDiagram
santa ->> sync_service:  preflight req /santa/api/preflight/<machine ID>
sync_service -->> santa: preflight response `clean_sync: true`
 Note right of sync_service: You're seeing zero events uploaded here if there's an pending events as reported by santactl status
santa ->> sync_service: eventupload request /santa/api/eventupload/<machine ID>
sync_service -->> santa: eventupload response
```

Looking at the sync state code we can see the following:

https://github.com/google/santa/blob/cd719ccef4427cfe10a9e0db656315387118c2be/Source/santasyncservice/SNTSyncEventUpload.m#L58-L69

In which case setting the clean_sync state will avoid uploading the events and then delete them unless `SyncEnableCleanSyncEventUpload` is enabled. 

Your logs are also not showing the expected `Uploaded 5 events` logline from the  `SLOGI(@"Uploaded %lu events", uploadEvents.count);`  

So it seems like you're not taking the branch.

We know that you've set `clean_sync` in the preflight response so `!self.syncState.cleanSync` should be false as you set it in your preflight response and `[[SNTConfigurator configurator] enableCleanSyncEventUpload])` should be true for your Santa instance to upload events which it isn't.

That code comes from:

https://github.com/google/santa/blob/cd719ccef4427cfe10a9e0db656315387118c2be/Source/common/SNTConfigurator.m#L860-L863

Which is really just accessing the key: 

https://github.com/google/santa/blob/cd719ccef4427cfe10a9e0db656315387118c2be/Source/common/SNTConfigurator.m#L60

I've tried testing with a hacked up version of [moroz](https://github.com/groob/moroz) and using a `config-overrides.plist` 

```xml
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>    
    <key>SyncBaseURL</key>
    <string>http://localhost:8080/v1/santa/</string>
    <key>SyncEnableCleanSyncEventUpload</key>
    <true/>
    <key>EnableDebugLogging</key>
    <true/>
  </dict>
</plist>
```

It looks like we're not properly getting the value of `SyncEnableCleanSyncEventUpload`. After adding it to the `__forcedConfigKeyTypes` 
https://github.com/google/santa/blob/cd719ccef4427cfe10a9e0db656315387118c2be/Source/common/SNTConfigurator.m#L168

And trying again. Events are correctly uploaded. I've filed #1123 to fix this.

**Comment by izzh** [comment]
Thank you for your work~
