### ISSUE TITLE
Support conditions on the parent process in binary execution rules

### ISSUE THREAD

**Issue by slashnick** [google/santa#1104]
The specific use case I'm after is the Google Chrome Helper.

Chrome runs in multiple processes that communicate with each other over IPC (mach ports on macOS). The Chrome process that reads your cookies is the "Network Service" process, one of a few processes launched through the Chrome Helper binary (`signing_id = com.google.Chrome.helper`).

If malicious code on your Mac wants to access your Chrome cookies, it can launch the Network Service process by directly invoking the Chrome Helper binary, and communicate with that process over IPC while pretending to be a real Chrome process.

(Malicious code can also read your cookies by reading and decrypting your "Cookies" sqlite file, or [launching Chrome with the remote debugger](https://mango.pdf.zone/stealing-chrome-cookies-without-a-password). Let's suppose you've already fixed those with a File Authorization rule, and the RemoteDebuggingAllowed enterprise policy)

It'd be cool if Santa could support a rule that only allows the Chrome Helper process to execute if its parent process is also signed by Google.

**Comment by pmarkowsky** [comment]
Definitely something we're interested in.

In addition to supporting the use case you're describing authorizing on parent PID attributes helps with tuning out trusted things that run python.

**Comment by slashnick** [comment]
I'm a bit fuzzy on how Santa would get the signing info for the parent process.

I feel like the options are:
1. Cache the signing info for every process, so we have it later when we need to look it up
  - This cache would go away when Santa reloads
  - If this takes too much memory, maybe you can be smart and only cache signing info for processes that match the "parent" condition for at least one rule
2. Look up info about the parent process when evaluating the child process launch event

Is option 2 too slow to do within the deadline?

**Comment by slashnick** [comment]
Oh wait, you can capture the parent process's signing info via the fork() event, and keep the info around in a very short-lived cache until the child process exec()s.

If the cache is very short-lived, that would change the semantics of my example rule to "only allow the Chrome Helper process to execute if its parent process is signed by Google, and has recently called fork()".

**Comment by mlw** [comment]
As @pmarkowsky mentioned, this is something we're very interested in and have started some preliminary design discussions. We have the events and data we need to make this possible now (which wasn't as true when #293 was filed).

Closing out this issue as it is a duplicate. We'll track further updates on #293.
