### ISSUE TITLE
Can't install the sample profile- The profile must originate from a user approved MDM server.

### ISSUE THREAD

**Issue by gauravphoenix** [google/santa#1125]
I am on Mac `13.4.1 (22F82)` and per instructions available [here](https://santa.dev/deployment/getting-started.html) when I try to install the system extension, I get the error- `The profile must originate from a user approved MDM server.` Google led me to [this](https://apple.stackexchange.com/questions/460701/how-to-import-mobileconfig-files-without-mdm-server) link which has no answers. 

If anyone on the latest macOS has been able to install this profile, please comment on how did you go about it.

**Comment by russellhancox** [comment]
The sample profiles are intended to be deployed using an MDM.

How to set up an MDM and deploy profiles with it is far out of the scope we can help with, but there are lots of sites online that deal with this.

If you want to run Santa on an unmanaged machine, the profiles aren't really necessary. Install the package, the OS will prompt you to allow the system extension (which is done in System Settings). After that's done, visit the Privacy and Security panel -> Full Disk Access, find com.google.santa.daemon and check the box next to it.

**Comment by gauravphoenix** [comment]
Thanks, I was under the wrong impression that profiles are required even for unmanaged installation.
