### ISSUE TITLE
Blocked Execution system notification is not processed unless receiver is focussed

### ISSUE THREAD

**Issue by jamiestrachan-shopify** [google/santa#1139]
Hi there,
I am writing an electron app that subscribes to the Santad notification `com.google.santa.notification.blockedeexecution`.
My app only receives the notification when it is focussed.  However, it receives other notifications while not focussed, such as `AppleShowScrollBarsSettingChanged` and my other experimental notifications.

In the [electron documentation](https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencespostnotificationevent-userinfo-deliverimmediately-macos), there is a `deliverImmediately` flag.
Setting this flag to false shows the same behaviour - the receiver will not get the notification until the receiving app is focussed.

The Apple documentation appears to include a [version of PostNotificationName](https://developer.apple.com/documentation/foundation/nsdistributednotificationcenter/1418360-postnotificationname) that includes this flag.

I am hoping that this flag can be turned on, like so: 
SNTNotificationManager.m:165
```
  [dc postNotificationName:@"com.google.santa.notification.blockedeexecution"
                    object:@"com.google.santa"
                  userInfo:userInfo
+                  deliverImmediately:YES];
```

Thanks for looking!

**Comment by mlw** [comment]
On the surface this seems maybe ok, though I am admittedly not super familiar with details on how distributed notifications work and have some minor concerns.

The documentation for [Posting Distributed Notifications](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Notifications/Articles/Posting.html#//apple_ref/doc/uid/20000724-97476-BAJEAFJD) has some interesting tidbits:

> An observer of a given notification may be in a suspended state and not processing notifications immediately. If an object posting a notification wants to ensure that all observers receive the notification immediately (for example, if the notification is a warning that a server is about to shut down), it can invoke postNotificationName:object:userInfo:deliverImmediately: with deliverImmediately:YES. The notification center delivers the notification ***as if the observers had registered with NSNotificationSuspensionBehaviorDeliverImmediately***

Looking into documentation for [Registering for Distributed Notifications](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Notifications/Articles/Registering.html#//apple_ref/doc/uid/20000723-98486): 

>  `NSNotificationSuspensionBehaviorDeliverImmediately`: The server delivers notifications matching this registration irrespective of whether it has received the setSuspended:YES message. When a notification with this suspension behavior is matched, it has the effect of first flushing any queued notifications. The effect is as if the server received setSuspended:NO while the application is suspended, followed by the notification in question being delivered, followed by a transition back to the previous suspended or unsuspended state.

Can you test if you get the desired behavior by setting the appropriate `suspensionBehavior`? If so this would likely be preferable rather than Santa forcing delivery.

**Comment by jamiestrachan-shopify** [comment]
Thanks for the response!
I am looking, but so far I am not sure I can set the suspensionBehavior inside electron.

**Comment by jamiestrachan-shopify** [comment]
Here is what I have found out:

The Electron code to register for a notification [is here](https://github.com/electron/electron/blob/e6931a788fad3d3315d3911c1997f3cd98fa34d0/shell/browser/api/electron_api_system_preferences_mac.mm#L223).
It is using the [addObserverForName](https://developer.apple.com/documentation/foundation/nsdistributednotificationcenter/1414151-addobserver) method.

As noted in the [discussion](https://developer.apple.com/documentation/foundation/nsdistributednotificationcenter/1414151-addobserver#discussion), that method uses [NSNotificationSuspensionBehaviorCoalesce](https://developer.apple.com/documentation/foundation/nsnotificationsuspensionbehavior/nsnotificationsuspensionbehaviorcoalesce) for the suspensionBehaviour.

Still looking...

**Comment by mlw** [comment]
I dug through a bit of the docs you linked to and agree that it doesn't seem possible to set with the currently exposed electron API. We've discussed this internally and don't think we have any major reservations to add `deliverImmediately`. Will get a PR up soon.

**Comment by jamiestrachan-shopify** [comment]
Wow! Thanks very much!
