### ISSUE TITLE
System Extension or Kernel? 

### ISSUE THREAD

**Issue by macnotes** [google/santa#1201]
Minor edit... the readme's opening paragraph says "system extension", but there's a bullet that says "kernel". I'm guessing it's the former in the current version? 

<img width="712" alt="image" src="https://github.com/google/santa/assets/25835285/97548c29-8c54-4355-a2fa-bfd5af092cea">

**Comment by pmarkowsky** [comment]
@macnotes Thanks for spotting this. I've opened #1202 to address it.
