### ISSUE TITLE
santactl status discrepancy when running as root/non-root

### ISSUE THREAD

**Issue by kallsyms** [google/santa#1217]
When USB blocking/remounting is configured via sync server, there can be a discrepancy between what `santactl status` reports when run as root vs. non-root.

The `santactl status` command [reads `SNTConfigurator.blockUSBMount`](https://github.com/google/santa/blob/main/Source/santactl/Commands/SNTCommandStatus.m#L194) which first reads from [`syncState` then falls back to `configState`](https://github.com/google/santa/blob/d2cbddd3fbca7c9da49d531f35ca6617b406190f/Source/common/SNTConfigurator.m#L972) if it was not configured via sync. The `SNTConfigurator` singleton init loads `syncState` by [calling `readSyncStateFromDisk`](https://github.com/google/santa/blob/d2cbddd3fbca7c9da49d531f35ca6617b406190f/Source/common/SNTConfigurator.m#L248), but this bails immediately if [running with `euid != 0`](https://github.com/google/santa/blob/d2cbddd3fbca7c9da49d531f35ca6617b406190f/Source/common/SNTConfigurator.m#L1077).

Found this while working on #1214.

**Comment by russellhancox** [comment]
santactl should retrieve this from santad through an XPC method in SNTDaemonControlXPC service.
