### ISSUE TITLE
Postinstall scripts during Office2011 upgrade get blocked, daemonized puppet doesn't

### ISSUE THREAD

**Issue by arubdesu** [google/santa#123]
Pardon that this is a fact-finding issue, but I'm not sure why puppet, as run from the official 4 agent installers and their associated launchd job DOESN'T seem to be tracked in santa's log. Also, Office 2011 updates have perl and python postinstall scripts that get blocked, which is odd because they're not in a directory I have a blacklist regex for. If it isn't apparent in the docs and I'm just missing something, could we clarify why this is happening? I wouldn't expect the fact the script is being called by installer to have anything to do with it, and even if puppet is ruby I'm still expecting it to get logged.

**Comment by pmarkowsky** [comment]
Closing this as it's gone unanswered for 5+ years.
