### ISSUE TITLE
santactl status --json exception

### ISSUE THREAD

**Issue by dbcm** [google/santa#124]
2016-10-24 15:44:12.169 santactl[34293:1793803] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9599648b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffaa0f7cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff958936a0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 352
	3   CoreFoundation                      0x00007fff9589350b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   santactl                            0x000000010032acb7 +[SNTCommandStatus runWithArguments:daemonConnection:] + 3511
	5   santactl                            0x000000010032bfd5 +[SNTCommandController runCommandWithName:arguments:] + 181
	6   santactl                            0x0000000100324a7d main + 621
	7   libdyld.dylib                       0x00007fffaa9d6255 start + 1
	8   ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by tburgin** [comment]
Thanks for finding this bug.
Fixed pending release.
