### ISSUE TITLE
Preflight `clean_sync` has no effect when no rules are sent.

### ISSUE THREAD

**Issue by np5** [google/santa#1255]
See: https://github.com/google/santa/blob/2e69370524ebebe88e74830b696ceba18e890020/Source/santad/DataLayer/SNTRuleTable.m#L408-L411

I think I understand the logic behind this. If there is a bug in the sync server, we do not want to wipe all the rules. It is also easy to fix on the server by just adding a single rule. It might be just a documentation issue ?

**Comment by pmarkowsky** [comment]
Correct if a sync server sends zero rules we simply return out of the function without deleting the rules in the database. If you look at the lines below that check you'll see that we start a database transaction. It's in that transaction that we delete the rules from the database. 

Can you elaborate on what you're looking to do that would require sending zero rules? 

As you pointed out if you wanted to achieve this you could send a `ALLOWLIST` rule for something like a platform binary in which case, you'd achieve the same effect. 

In general sending zero rules could be especially troublesome in lockdown mode as the client would effectively only be able to run critical system binaries or any static rules it has.

**Comment by np5** [comment]
The only use-case is for the test devices that are always being re-enrolled. The risks clearly outweigh the benefits. This is why I suggested maybe just adding a warning in the docs.

**Comment by pmarkowsky** [comment]
This is addressed via #1259. Marking as closed.
