### ISSUE TITLE
`santactl rule --check` is broken

### ISSUE THREAD

**Issue by mlw** [google/santa#1261]
There are various issues with `santactl rule --check` not working appropriately. This is true for at least TeamID and SigningID based rule checks, possibly others.

There are some invalid assumptions made about data available in the SNTPolicyProcessor that are not true when a rule check is performed. These assumptions lead to TID/SID data not being used when performing rule evaluations on the rule check path 

**IMPORTANT:** This does ***not*** affect Santa's ability to evaluate rules at runtime during real executions, that is working as expected! This is only affecting `santactl rule --check ...`

**Comment by pmarkowsky** [comment]
We definitely need integration tests for these.

**Comment by mlw** [comment]
The main issue here is that `SNTPolicyProcessor`'s `decisionForFilePath:...` method assumes that there is a path. But coming from `SNTCommandRule` that is not true. When checking rule information for identifiers that would otherwise require a binary with valid codesign status, this breaks the implemented logic and lookup fails.
