### ISSUE TITLE
Symbolic Link Scope

### ISSUE THREAD

**Issue by eopeter** [google/santa#1289]
We are seeing a situation where binaries in a path with scope rules are getting blocked when accessed on the real path. The scope rule is for the symbolic link. Does Santa allow the symbolic and real path if the regex is only for the symbolic link?

**Comment by russellhancox** [comment]
Santa doesn't follow symlinks, the path that we're provided to authorize is the full path after normalization and the path regexes are simple string matches against this provided path.

**Comment by eopeter** [comment]
Thank you!
