### ISSUE TITLE
About Xcode 8.1 with SDK 10.11

### ISSUE THREAD

**Issue by stanfordzhang** [google/santa#131]
When I user Xcode 8.1 with SDK 10.11, [NSAttributedString:initWithHTML:] in SNTBlockMessage.m(line 56) always crash.

**NSAppKitVersionNumber10_0 is defined!!!**

```
#ifdef NSAppKitVersionNumber10_0
// !!!enter here!!!
  NSData *htmlData = [fullHTML dataUsingEncoding:NSUTF8StringEncoding];
  return [[NSAttributedString alloc] initWithHTML:htmlData documentAttributes:NULL];
#else
  NSString *strippedHTML = [self stringFromHTML:fullHTML];
  if (!strippedHTML) {
    return [[NSAttributedString alloc] initWithString:@"This binary has been blocked."];
  }
  return [[NSAttributedString alloc] initWithString:strippedHTML];
#endif
```

> **NSAppKitVersionNumberXXX is alway defined. I think the NSAppKitVersionNumberXXX usage is like [Runtime Version Check](https://gist.github.com/devxoul/3daeb6597339a6c0cf92)**

 I test it in Xcode 7.3.1, it's Okay. Then, I test [NSMutableAttributedString:initWithHTML:options:documentAttributes:] good.

BTW: I can not go back to the OS X 10.11, meanwhile Xcode 7.3.1 alway crash in macOS 10.12. I have no choice.

Appendix:
        
        NSString * fullHTML = @"<html><head><style>body {  font-family: 'Lucida Grande', 'Helvetica', sans-serif;  font-size: 13px;  color: #666;  text-align: center;}</style></head><body>The following application has been blocked from executing<br />because it has been deemed malicious.</body></html>";
        
        NSData *htmlData = [fullHTML dataUsingEncoding:NSUTF8StringEncoding];
        NSAttributedString * as = [[NSAttributedString alloc] initWithHTML:htmlData documentAttributes:nil];
        NSLog(@"as = %@", as);
        
        NSDictionary *options = @{NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType, NSCharacterEncodingDocumentAttribute: @(NSUTF8StringEncoding)};
        NSMutableAttributedString *as1 = [[NSMutableAttributedString alloc] initWithHTML:htmlData options: options documentAttributes:nil];
        NSLog(@"as = %@", as1);
        //NSString * fullHTML2 = @"<html></html>";
        //NSString *fullHTML3 = @"“Hello” World";
        //NSData *htmlData = [fullHTML dataUsingEncoding:NSUTF8StringEncoding];
        //NSAttributedString * as = [[NSAttributedString alloc] initWithHTML:htmlData documentAttributes:nil];
        //NSLog(@"as = %@", as);

**Comment by russellhancox** [comment]
How are you using Xcode 8.1 with the 10.11 SDK?

FWIW, I can't reproduce this crash on Xcode 7.3.1 or Xcode 8.1 on 10.12.

> NSAppKitVersionNumber10_0 is defined!!!

Yes, that's expected. The `ifdef` is there because that code is used in the `Santa.app` (which **is** linked to AppKit) and `santad`/`santactl`/`LogicTests` (which **is not** linked to AppKit) targets. In the latter, the _else_ branch is used.

**Comment by russellhancox** [comment]
We've removed the need to use the 10.11 SDK.
