### ISSUE TITLE
'Whitelisted (Scope)': how to manage scripts, pkg files

### ISSUE THREAD

**Issue by juju4** [google/santa#137]
Hello,

Testing santa (0.9.14 on macos 10.11 and 10.12). Mostly working well with 2 limitations: both scripts file and pkg file still execute all the time.
They are tagged 'Whitelisted (Scope)' by fileinfo and don't create any log entries in santa.log.

Code seems to have a block option. so is it something which is possible to change now or under work for future?

Thanks
(and Happy new year! :)

**Comment by arubdesu** [comment]
Hey there, pkg files are not executables, and as mentioned in the README scripts are explicitly allowed (see Known Issues... which could possibly be re-phrased 'design considerations - it's not a bug that it doesn't block these things by default): "Santa is currently written to ignore any execution that isn't a binary". You _can_ get different behavior with path blacklisting, but that's usually not a tenable position.

**Comment by juju4** [comment]
Thanks @arubdesu for the quick response.

I'm fine with no block for script. I agree it can get very complex.
It surprised me a bit more for pkg file but I suppose that, yes, they are mostly scripts too.

Still one nice option would be to able to log their execution, even if not blocking.

And what this code https://github.com/google/santa/search?utf8=%E2%9C%93&q=scope do ?

**Comment by arubdesu** [comment]
All executions, even scripts running as part of pre/post-installs, should be getting logged. Is there a publicly-available installer that you're not seeing that for? 

As far as I crudely understand it, scope is a construct used for rule evaluation, sha256 vs. cert vs. path being progressively wider scopes, and white vs. blacklisting being ordered scopes as well. I can't quite speak intelligently about what that means in terms that are specific to your original intent opening this issue (if I'm correct you would like pkg and script conditions to be configurable using some sort of logic). I _can_ say that I know path-based blacklisting stops scripts or apps running from a directory, but it being trivial to circumvent for actual malicious apps it's not a recommended practice. If you were hoping to blacklist installer pkgs based on cert I'm guessing that would require significant work and plumbing changes for probably little real-world coverage - the majority of stuff is drag-drop these days.
