### ISSUE TITLE
Add ability to edit the Ignore button text

### ISSUE THREAD

**Issue by float0n** [google/santa#1398]
When a user launches a blocked app and an app blocked pop up appears, the Dismiss button text defaults to `Ignore`. For example:

<img width="652" alt="Screenshot 2024-07-19 at 3 09 33 PM" src="https://github.com/user-attachments/assets/289dcadf-6a68-4a69-988d-7884f262a4b1">

To make the button action more clear to the end-user, it'd be helpful to adjust the text to something more end user friendly and understandable (i.e. `Dismiss` or `Close`).  This would also match the gif on the project's readme in which a button with the `Dismiss` text is shown: https://github.com/google/santa?tab=readme-ov-file#screenshots

**Comment by russellhancox** [comment]
I don't remember why we changed the button from Dismiss to Ignore. I think that as well as making the button customizable we should return the default back to Dismiss
