### ISSUE TITLE
Meta: Debugging driver from Xcode

### ISSUE THREAD

**Issue by wagerlabs** [google/santa#144]
How do you guys debug the driver?

I have figured out how to do this using VMware Fusion with a MacOS guest. 

I haven't figured out a way to debug this from within Xcode, though, since it insists on launching the kernel or reports that attaching is not supported in kdp-remote.

Also, what is the best way to intercept driver startup, assuming that the driver is loaded manually?

**Comment by tburgin** [comment]
Nope, have not tried with a VM.
For our kernel tests we disconnect our main daemon that is usually communicates with and launch a simple kernel tests binary.

https://github.com/google/santa/blob/master/Tests/KernelTests/main.mm
