### ISSUE TITLE
Processes that start before santad don't get blocked

### ISSUE THREAD

**Issue by anaisbetts** [google/santa#147]
If a process that is being blocked by Santa gets executed before santad starts up, it gets to start anyways. This seems like a security issue

**Comment by russellhancox** [comment]
That's true but other than hardcoding a whitelist into the kernel there isn't really a way of fixing that. We could kill processes after santad starts if they wouldn't have been allowed but that's not really worthwhile as there's no knowing what those processes have done.

We don't really consider this a security issue as it's beyond Santa's scope - if something is starting before santad it has already been installed as a persistence item, your machine is already compromised. We expect anyone using Santa to already be monitoring for installation of persistence agents (possibly using Santa's file watching ability) and remediating that by other means.

**Comment by paulcbetts** [comment]
@russellhancox I actually use santa to nerf annoying software installed by my IT department, so in a sense, it's "compromised". It works quite well for this purpose, except for the bug above. Blocking non-Apple software from starting until santad starts would be a good intermediate step.

**Comment by paulcbetts** [comment]
(cue look of horror)

**Comment by pmarkowsky** [comment]
I think this is now fixed with #750.
