### ISSUE TITLE
Content-Encoding header zlib vs deflate

### ISSUE THREAD

**Issue by np5** [google/santa#155]
According to the [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.5), the value tokens for the Content-Encoding header should be registered at the [Internet Assigned Numbers Authority](https://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding).  `zlib` doesn't seem to be one of them. `deflate` should probably be used instead [here](https://github.com/google/santa/blob/543ac7c649fdea69ffeeafc8dc0aba7d0c85f169/Source/santactl/Commands/sync/SNTCommandSyncStage.m#L72).

**Comment by russellhancox** [comment]
You're correct, this is technically invalid. However, this would only matter to servers that are receiving Santa requests and we'd expect those to be written to handle this. If we change to using deflate now, several different server implementations would need to be changed and as there are _very_ few servers that properly handle compressed requests automatically I don't see there being any benefit, other than to strictly follow the RFC.
