### ISSUE TITLE
Kernel trap causing panic.

### ISSUE THREAD

**Issue by ShikiSuen** [google/santa#166]
Today I failed to wake up my laptop's built-in screen. Tried to connect it to a DisplayPort display and restart the system, then the built-in display of my laptop finally shows things but the kernel panics. I unplugged the display and restart, the system shows a panic report which shows the Google santa driver in backtrace:

<pre><code>Anonymous UUID:       DA54FA3D-DC08-76F7-3A36-1ED62EDD1EF4

Fri Apr 14 09:17:43 2017

*** Panic Report ***
panic(cpu 2 caller 0xffffff80042011bd): Kernel trap at 0xffffff80041c388e, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x00000004480c3006, CR4: 0x00000000003627e0
RAX: 0x0000000000000001, RBX: 0x0000000000000000, RCX: 0x000000000000002f, RDX: 0x0000000000000000
RSP: 0xffffff91efd0bad0, RBP: 0xffffff91efd0bad0, RSI: 0xffffff7f848f2f77, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0xffffff80048671b0, R11: 0xffffff81a151a000
R12: 0x7b710ba2b5d400b7, R13: 0x0000000000000003, R14: 0x0000000000000000, R15: 0xffffff8026786d00
RFL: 0x0000000000010286, RIP: 0xffffff80041c388e, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff91efd0b760 : 0xffffff80040ec3ec 
0xffffff91efd0b7e0 : 0xffffff80042011bd 
0xffffff91efd0b9c0 : 0xffffff800409d543 
0xffffff91efd0b9e0 : 0xffffff80041c388e 
0xffffff91efd0bad0 : 0xffffff7f848f26aa 
0xffffff91efd0bcc0 : 0xffffff7f848f1c68 
0xffffff91efd0bd00 : 0xffffff8004543543 
0xffffff91efd0bd60 : 0xffffff80043322a0 
0xffffff91efd0bf50 : 0xffffff8004625695 
0xffffff91efd0bfb0 : 0xffffff800409dd46 
      Kernel Extensions in backtrace:
         com.google.santa-driver(0.9.12)[E441379C-DF5A-307D-9F84-4B1D157C0A26]@0xffffff7f848ef000->0xffffff7f848f4fff

BSD process name corresponding to current thread: logd

Mac OS version:
16E195

Kernel version:
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
Kernel UUID: 06F94FD7-451F-34A1-B13C-D68FF7EDE0A0
Kernel slide:     0x0000000003e00000
Kernel text base: 0xffffff8004000000
__HIB  text base: 0xffffff8003f00000
System model name: MacBookPro13,2 (Mac-66E35819EE2D0D05)

System uptime in nanoseconds: 7630831958
last loaded kext at 7607059407: com.apple.driver.usb.cdc.ncm	5.0.0 (addr 0xffffff7f86423000, size 61440)
loaded kexts:
com.google.santa-driver	0.9.12
com.apple.driver.AppleGraphicsDevicePolicy	3.14.41
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDAHardwareConfigDriver	279.48
com.apple.driver.AppleHDA	279.48
com.apple.driver.AppleIntelPCHPMC	1.1
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.iokit.IOBluetoothSerialManager	5.0.4f18
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleEmbeddedOSSupportHost	1
com.apple.driver.AppleIntelSKLGraphics	10.2.4
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.driver.AppleMuxControl	3.14.41
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelSKLGraphicsFramebuffer	10.2.4
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleBacklight	170.9.14
com.apple.driver.AppleMCCSControl	1.3.1
com.apple.driver.CoreStorageFsck	540.30.1
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.50.19
com.apple.driver.AppleTopCaseHIDEventDriver	114
com.apple.driver.AirPort.Brcm4360	1150.9.1a2
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.driver.usb.AppleUSBiBridge	1.0
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.DspFuncLib	279.48
com.apple.kext.OSvKernDSPLib	525
com.apple.iokit.IOBluetoothHostControllerUARTTransport	5.0.4f18
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.4f18
com.apple.iokit.IOBluetoothFamily	5.0.4f18
com.apple.iokit.IOSurface	159.6
com.apple.driver.AppleThunderboltEDMSink	4.1.1
com.apple.driver.AppleThunderboltDPOutAdapter	5.0.2
com.apple.driver.AppleGraphicsControl	3.14.41
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleHDAController	279.48
com.apple.iokit.IOHDAFamily	279.48
com.apple.iokit.IOAudioFamily	205.15
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.AppleGraphicsDeviceControl	3.14.41
com.apple.iokit.IOAcceleratorFamily2	311.11
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	514.10
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOGraphicsFamily	514.10
com.apple.iokit.IOSCSIArchitectureModelFamily	394.50.1
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.CoreStorage	540.30.1
com.apple.driver.AppleXsanScheme	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleHIDKeyboard	199
com.apple.driver.AppleMultitouchDriver	368.14
com.apple.driver.AppleInputDeviceSupport	76.6
com.apple.driver.AppleHPM	3.0.9
com.apple.driver.AppleIntelLpssI2CController	3.0.60
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.2
com.apple.driver.AppleHSSPIHIDDriver	49
com.apple.driver.AppleThunderboltNHI	4.5.3
com.apple.iokit.IOThunderboltFamily	6.5.6
com.apple.driver.AppleHSSPISupport	49
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.50.16
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
</code></pre>

**Comment by tburgin** [comment]
Looks like you have `v0.9.12` loaded. The latest release is `v0.9.17`. There have been a number of [bug fixes](https://github.com/google/santa/compare/0.9.12...0.9.17
) since applied since `v0.9.12`. Can you install the latest release and let us know if your issue persists?

https://github.com/google/santa/releases

According to the backtrace `strprefix` read into memory it wasn't supposed to. Could be that the path string wasn't null terminated.

```c
// https://opensource.apple.com/source/xnu/xnu-3789.51.2/osfmk/device/subrs.c
/*
 * Return TRUE(1) if string 2 is a prefix of string 1.
 */
int
strprefix(const char *s1, const char *s2)
{
	int c;

	while ((c = *s2++) != '\0') {
		if (c != *s1++)
			return (0);
	}
	return (1);
}
```

```
Current executable set to '/Library/Developer/KDKs/KDK_10.12.4_16E195.kdk/System/Library/Kernels/kernel' (x86_64).
(lldb) image lookup -a 0xffffff800409dd46
      Address: kernel[0xffffff800029dd46] (kernel.__TEXT.__text + 23878)
      Summary: kernel`hndl_unix_scall64 + 22
(lldb) image lookup -a 0xffffff8004625695
      Address: kernel[0xffffff8000825695] (kernel.__TEXT.__text + 5822101)
      Summary: kernel`unix_syscall64 + 597 at systemcalls.c:376
(lldb) image lookup -a 0xffffff80043322a0
      Address: kernel[0xffffff80005322a0] (kernel.__TEXT.__text + 2728608)
      Summary: kernel`renameat_internal + 3760 at vfs_syscalls.c:7514
(lldb) image lookup -a 0xffffff8004543543
      Address: kernel[0xffffff8000743543] (kernel.__TEXT.__text + 4896067)
      Summary: kernel`kauth_authorize_fileop + 339 [inlined] kauth_authorize_action + 126 at kern_authorization.c:567
               kernel`kauth_authorize_fileop + 213 at kern_authorization.c:567

Current executable set to '~/Downloads/santa-0.9.12/binaries/santa-driver.kext/Contents/MacOS/santa-driver' (x86_64).
(lldb) image lookup -a 0xffffff7f848f1c68                                                                                                                                       Address: santa-driver[0x0000000000002c68] (santa-driver.__TEXT.__text + 6760)
      Summary: santa-driver`::fileop_scope_callback(kauth_cred_t, void *, kauth_action_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t) + 152 [inlined] SantaDecisionManager::DecrementListenerInvocations() at SantaDecisionManager.cc:500
               santa-driver`::fileop_scope_callback(kauth_cred_t, void *, kauth_action_t, uintptr_t, uintptr_t, uintptr_t, uintptr_t) + 152 at SantaDecisionManager.cc:500
(lldb) image lookup -a 0xffffff7f848f26aa
      Address: santa-driver[0x00000000000036aa] (santa-driver.__TEXT.__text + 9386)
      Summary: santa-driver`SantaDecisionManager::FileOpCallback(int, vnode*, char const*, char const*) + 250 at SantaDecisionManager.cc:436

Current executable set to '/Library/Developer/KDKs/KDK_10.12.4_16E195.kdk/System/Library/Kernels/kernel' (x86_64).
(lldb) image lookup -a 0xffffff80041c388e
      Address: kernel[0xffffff80003c388e] (kernel.__TEXT.__text + 1226894)
      Summary: kernel`strprefix + 30 at subrs.c:579
(lldb) image lookup -a 0xffffff800409d543
      Address: kernel[0xffffff800029d543] (kernel.__TEXT.__text + 21827)
      Summary: kernel`trap_from_kernel + 38
(lldb) image lookup -a 0xffffff80042011bd
      Address: kernel[0xffffff80004011bd] (kernel.__TEXT.__text + 1479101)
      Summary: kernel`kernel_trap + 2349 at trap.c:799
(lldb) image lookup -a 0xffffff80040ec3ec
      Address: kernel[0xffffff80002ec3ec] (kernel.__TEXT.__text + 345068)
      Summary: kernel`panic + 236 at debug.c:461
```

**Comment by ShikiSuen** [comment]
I just updated to the latest release. I will let you know if this issue persists.

**Comment by russellhancox** [comment]
Feel free to reopen if the issue returns.
