### ISSUE TITLE
Bundle scan should detect the most-general bundle, not the least-general

### ISSUE THREAD

**Issue by msuozzo** [google/santa#169]
Using Spotify.app as an example below, running "Spotify Helper" inside the "Spotify Helper.app" bundle should map to "Spotify.app" because it is the most general (and, thus, the most user-recognizable) part of the application. However the current logic only walks up the file tree until it finds any bundle which, as in this case, may not always be the best choice.

**/Applications/Spotify.app/**
└── Contents
    ├── Frameworks
    │   ├── Chromium\ Embedded\ Framework.framework
    │   │   └── ...
    │   └── **Spotify\ Helper.app**
    │       └── Contents
    │           ├── Info.plist
    │           ├── MacOS
    │           │   └── **Spotify\ Helper**    <---------- 
    │           └── _CodeSignature
    │               └── CodeResources
    ├── Info.plist
    ├── MacOS
    │   ├── Spotify
    │   ├── SpotifyWebHelper
    │   └── sp_relauncher
    ├── Resources
    │   └── ...
    └── _CodeSignature
        └── CodeResources

**Comment by russellhancox** [comment]
It's expected that the first thing you would launch would be the _primary_ bundle and whitelist everything inside, so in your case you'd execute Spotify and that would whitelist Spotify Helper. The only way the latter would be launched 'first' is if you already had it installed as a login item or something, which should become moot as time goes on.

Unfortunately doing what you suggest can result in picking the wrong, or too general bundle. It also means scanning many many more files than we might intend.

**Comment by msuozzo** [comment]
As discussed offline, apparently there's some weird behavior in the bundle detection code such as "/" being considered a bundle.

My main consideration here is when the main application in a bundle is signed with a whitelisted cert but auxiliary executables aren't. With the current scheme, this results in the user having to vote multiple times on bundles which aren't intended for human view, e.g. "Spotify Helper." I've run into this scenario twice already, notably with Wireshark (which, given that it's a Linux port, might not be a great example), so I'm inclined to believe that it'll be fairly common.

If possible, I think it would be useful to define concrete situations in which the more-general bundle scanning would cause issues.

**Comment by tburgin** [comment]
We could remove the `break` from the search algorithm and let it walk up until it's max depth or until `/`. It would then set and return the highest most valid bundle.

https://github.com/google/santa/blob/master/Source/common/SNTFileInfo.m#L296-L304

That however will add time to every blocked execution, in addition it will expand the scope of files that need to be checked during hashing. This is probably a negligible amount, but we should get some hard numbers.

**Comment by tburgin** [comment]
https://github.com/google/santa/pull/175

**Comment by tburgin** [comment]
Fixed in v0.9.18
