### ISSUE TITLE
Installation Script or Copy/Pasta Instructions

### ISSUE THREAD

**Issue by aes512** [google/santa#17]
An install script would be nice for those that:

1. Do not have a kext signing certificate and with to roll the pre-built, pre-signed version of the kext that Google supplies
2. Users that do not wish to roll kext-dev mode

**Comment by russellhancox** [comment]
Seems reasonable. I'll look into it next week.

**Comment by russellhancox** [comment]
Commit 1501d4 adds an install.sh script that can be run directly from the release tarball and also a Makefile to be used with TheLuggage that makes a package. I'll also upload a generated package for each new release.

Next up, some installation instructions.

**Comment by russellhancox** [comment]
I've added some (slightly rough) instructions on the Wiki that reference the package and install script.

**Comment by aes512** [comment]
Thank you Russel, that's much more elegant than the script I wrote :+1:
