### ISSUE TITLE
How Santa handles compound commands

### ISSUE THREAD

**Issue by michael-myers** [google/santa#171]
Hey this is a great project, I wanted to try it out for home use (although I know that's not the intended audience).

I was worried that logging every execution was going to fill my drive with log files, though, so I set about to configure some "skip" rules in `/etc/asl/com.google.santa.asl.conf`

That's when I realized how error-prone this might be, because of what a log-line looks like in `/var/log/santa.log`. For example (added emphasis on paths, below):

> [2017-05-11T02:41:38.735Z] I santad: action=EXEC|decision=ALLOW|reason=CERT|sha256=7dff6291a29fdaf97dad64c0671dc5d1ecc42189bc5daf8ca08e2a3ae06aff95|path=**/bin/csh|args=/bin/csh -c cd '/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts' && ./get-current-resolvers.sh <pipe> ./get-resolvers-description.sh**|cert_sha256=2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32|cert_cn=Software Signing|pid=7494|ppid=602|uid=501|user=myusername|gid=20|group=staff|mode=M
[2017-05-11T02:41:38.771Z] I santad: action=EXEC|decision=ALLOW|reason=CERT|sha256=c4daaf12bd42adee60549872126e15186c75d89e760f078bfa6a45a861f6400f|**path=/bin/ksh|args=/bin/ksh ./get-current-resolvers.sh**|cert_sha256=2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32|cert_cn=Software Signing|pid=7496|ppid=7494|uid=501|user=myusername|gid=20|group=staff|mode=M
[2017-05-11T02:41:44.066Z] I santad: action=EXEC|decision=ALLOW|reason=CERT|sha256=2bf2d10a7529a88d340ce0255da52dbef9873ccb44e46d23af03abf70b8e54ca|**path=/bin/sh|args=/bin/sh ./get-resolvers-description.sh**|cert_sha256=2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32|cert_cn=Software Signing|pid=7513|ppid=7510|uid=501|user=myusername|gid=20|group=staff|mode=M

I wanted to skip these sorts of entries in the logs, because DNSCrypt executes a handful of shell scripts like, every second. It's launching `csh`, `ksh`, `sh`, etc. and passing various scripts as arguments. But if I filter on a substring like "/bin/sh" I am going to miss things I want to log. Do I need 'skip' entries for every compound statement invocation of a shell that I observe?

Assume I do that. Couldn't a hypothetical bad guy then just execute `thing/I/filtered && /path/to/malicious/thing` and bypass my logs because of the way Santa logs compound statements instead of the executions of the individual components of the command?

Secondly, in these compound statements, is Santa calculating the SHA256 hash of the first process but not anything after that in the statement? So, the following two lines, which are executing different commands but via the same shell, both capture the same hash:

> [2017-05-11T02:41:44.257Z] I santad: action=EXEC|decision=ALLOW|reason=CERT|sha256=7dff6291a29fdaf97dad64c0671dc5d1ecc42189bc5daf8ca08e2a3ae06aff95|path=/bin/csh|args=/bin/csh -c cd '/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts' && exec ./gui-pop-conf-change.sh menubar|cert_sha256=2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32|cert_cn=Software Signing|pid=7523|ppid=602|uid=501|user=myusername|gid=20|group=staff|mode=M

> [2017-05-11T02:41:49.400Z] I santad: action=EXEC|decision=ALLOW|reason=CERT|sha256=7dff6291a29fdaf97dad64c0671dc5d1ecc42189bc5daf8ca08e2a3ae06aff95|path=/bin/csh|args=/bin/csh -c cd '/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts' && ./get-current-resolvers.sh <pipe> ./get-resolvers-description.sh|cert_sha256=2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32|cert_cn=Software Signing|pid=7525|ppid=602|uid=501|user=myusername|gid=20|group=staff|mode=M

**Comment by russellhancox** [comment]
> Do I need 'skip' entries for every compound statement invocation of a shell that I observe?

I think that's the only way to do what you want, due to how syslogd works.

> Assume I do that. Couldn't a hypothetical bad guy then just execute thing/I/filtered && /path/to/malicious/thing and bypass my logs

Yes - the way to avoid that would be to have the substring skip entries be very specific, like:
```|path=/bin/ksh|args=/bin/ksh ./get-current-resolvers.sh|```

> Secondly, in these compound statements, is Santa calculating the SHA256 hash of the first process but not anything after that in the statement

The SHA-256 hash is calculated based on the binary that ran (the file in the _path_ field).

**Comment by russellhancox** [comment]
FYI: we're in the process of reworking the logging to avoid the OS log facilities which should allow smarter filtering in future.
