### ISSUE TITLE
On High Serria there is no /var/log/santa.log

### ISSUE THREAD

**Issue by PickmanSec** [google/santa#198]
Hi Santa team,

I have a beta version of high serria and after installing the Santa.app and approving/Allowing the kext via the security panel I still have no santa.log. Is there a way I can debug this behavior?

**Comment by PickmanSec** [comment]
I also downloaded the presigned Santa.app from this github project.

**Comment by tburgin** [comment]
Ahoy! We moved the default logging location in the [0.9.18 release](https://github.com/google/santa/releases/tag/0.9.18).
The new default location is:`/var/db/santa/santa.log`
Do you see logs there?

**Comment by russellhancox** [comment]
Please re-open if this is still an issue.
