### ISSUE TITLE
Log an error if SyncBaseURL is set but invalid

### ISSUE THREAD

**Issue by oliof** [google/santa#20]
If you try incomplete commands looking for interactive help on the command line, santactl crashes:

        $ sudo santactl rule add --whitelist --path
        2015-07-22 08:54:02.591 santactl[21154:230605] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 2]'
        *** First throw call stack:
        (
        	0   CoreFoundation                      0x00007fff8e96f03c __exceptionPreprocess + 172
        	1   libobjc.A.dylib                     0x00007fff8e61e76e objc_exception_throw + 43
        	2   CoreFoundation                      0x00007fff8e8381e4 -[__NSArrayM objectAtIndex:] + 260
        	3   santactl                            0x0000000105c2e355 +[SNTCommandRule runWithArguments:daemonConnection:] + 853
        	4   santactl                            0x0000000105c36312 +[SNTCommandController runCommandWithName:arguments:] + 193
        	5   santactl                            0x0000000105c2f4e8 main + 514
        	6   libdyld.dylib                       0x00007fff964a75c9 start + 1
        )
        libc++abi.dylib: terminating with uncaught exception of type NSException
        $

I would prefer some usage output (including an early warning if SyncBaseURL is set).

**Comment by russellhancox** [comment]
That fixes the crash and prints usage output. The early warning if SyncBaseURL is set has existed since 0.8, is it not working?

**Comment by oliof** [comment]
It works when you have a full, valid comment, but not when you have an
invalid one.

2015-07-22 19:53 GMT+02:00 Russell Hancox <notifications@github.com>:

**Comment by russellhancox** [comment]
The configuration class tries to parse the setting into a URL so if it's not a valid URL it acts like one isn't set. I guess that should instead be printed out as an error from whatever process is trying to read the configuration.

**Comment by russellhancox** [comment]
Fixed in the just-released v0.9.8
