### ISSUE TITLE
Add support for configuring Santa via mobileconfig

### ISSUE THREAD

**Issue by jesseendahl** [google/santa#209]
Hi!

I think it'd be a really great addition if Santa could read config from a `.mobileconfig`. There are several advantages to supporting this functionality, but I'll just mention the biggest one. The biggest benefit to Google and the Mac admin community is that it would make it possible to easily deploy Santa using only MDM, without the need for any other configuration management tooling (e.g. Puppet/Chef) or custom packages.

This would already be hugely beneficial today, but would also serve to future proof Santa for a potential world where the only way to manage/configure apps on macOS is via MDM.

Thoughts on implementation:

- Santa would need to ignore any existing configuration on disk once a `.mobileconfig` got installed.
- Currently, when operating in sync server mode, `santad` won't read configuration changes without an unload/reload of its launch daemon. This would have to be changed so that `santad` would new config from a `.mobileconfig` automatically, without an unload/reload.

**Comment by russellhancox** [comment]
I think this is great idea and would definitely make managing Santa easier for everyone.

We can use NSUserDefaults' `objectIsForcedForKey:` and `objectIsForcedForKey:inDomain:` to only allow this configuration from a .mobileconfig rather than from the user themselves.

All of the changes should be limited to the SNTConfigurator class, which should make this relatively easy to implement. If you (or anyone) have time to work on this we'd be happy to review contributions, otherwise we'll get to this in the near future.

**Comment by jesseendahl** [comment]
Awesome! Glad you agree :) Unfortunately we don't have the bandwidth to implement it ourselves  right now, but super excited to hear you can make it happen on your end soon(ish).

**Comment by tburgin** [comment]
`objectIsForcedForKey:` and `objectIsForcedForKey:inDomain:` doesn't seem to be able to differentiate between mobile config payload scopes [0]. We would only want to pay attention to the System scope. Allowing users to flip config values would not be good.

We could use `CFPreferencesCopyValue()` to specify the System scope, but that will not tell us if the value is forced or not :/

In light of this, I think CFPreferencesCopyValue is the best way forward . This way we at least know if the config was written by an admin.

Thoughts?

[0] 
```
<key>PayloadScope</key>
<string>User</string>
```
```
<key>PayloadScope</key>
<string>System</string>
```

**Comment by jesseendahl** [comment]
I talked this over with @mikeymike and yes  `CFPreferencesCopyValue` seems like the way to go.

As long as only the values are only respected by Santa when the `PayloadScope` is `System`, it shouldn’t matter whether the value is forced or not, since installing the config will have required admin/root rights regardless.

**Comment by tburgin** [comment]
Hmm `CFPreferencesCopyValue()` does not see mobile configs. We need `CFPreferencesCopyAppValue()` for that, but we are back to the same situation where we can't tell what scope the value is coming from...

**Comment by tburgin** [comment]
Oh, I was missing something obvious. santad runs as root and ignores the user's profiles. So @russellhancox is correct: NSUserDefaults' `objectIsForcedForKey:` and `objectIsForcedForKey:inDomain:` can be used.

The only thing we need to be carful about is the Santa.app. This process does run as the user and does read configs, but I don't think there are any security sensitive keys used.

**Comment by russellhancox** [comment]
Configuration profiles (even user-scoped ones) can only be installed by root, so I don't see any real problem security-wise.

As for whether `objectIsForcedForKey:inDomain:` works:

| Profile Scope | Process User | Key is Forced |
| --- | --- | --- |
| System | User | Yes |
| System | Root | Yes |
| User | User | Yes |
| User | Root | No |

**Comment by tburgin** [comment]
It might be something with 10.13, but I was able to install a user-scoped profile without any privilege escalation. Thus, my initial worry.

The last row in your table highlights the point: we should be fine using NSUserDefaults.

Now we just need determine what config sources take precedence.
I propose this: sync server > profile > config file
Having this clearly defined will make it easy to merge sources.

Alternately we could have the use of a profile or config file be mutually exclusive.
I don't have a strong opinion either way.

**Comment by russellhancox** [comment]
We could just skip all the hassle and read directly from /L/Managed Preferences/com.google.santa.plist:

- the dir is only writable by root
- files in there don't get written if a profile is managing them
- if you do put a plist in there manually (and a profile isn't installed) it tricks `objectIsForcedForKey:` anyway. 
- installing and remove profiles using the profiles command updates the files on-disk immediately.

Doing it that way means the change is a one-line change moving the config file from /var/db/santa to /LIbrary/Managed Preferences and we can easily copy this in the postinstall for the release that changes it.

**Comment by pudquick** [comment]
_LALALA I can't hear you talking about reading preference plist files directly from the disk_

**Comment by pudquick** [comment]
(More seriously, while I would vote for using the API, just having it functional with profiles would be amazing either way)

**Comment by tburgin** [comment]
I am not sure how writing out to the file will work when it is being
managed by a profile. We still need to write some sync state to disk. Maybe
we should move the sync state things to another file?

**Comment by jessfs** [comment]
Moving it to another file seems reasonable to me.

**Comment by jesseendahl** [comment]
Moving it to another file seems reasonable to me.

**Comment by tburgin** [comment]
I have been testing using /Library/Managed Preferences/com.google.santa.plist as the config file. For the most part everything works! Even the sync timestamps are writable and are nmo.

The only thing that does not work anymore is writing to the new config file location with the `defaults` command. Any attempts to change the preference are silently dropped. Editing the file directly does work. I imagine Apple stops `defaults` from writing to Managed Preferences. This would be a departure from how the old config file was managed.

I am mostly okay with this caveat, we will just have to document it properly in the release. Having the postinstall do a one time copy of /var/db/santa.plist to the new location would mitigate this.

**Comment by russellhancox** [comment]
We could make it so the old location is still usable if no file exists at
the new location, just do a one-time check at startup.

**Comment by tburgin** [comment]
True. If no config exists - default to the old location? That way you can
config with the defaults command.

If you wanted to start managing with a mobile config: install one and
restart all santa processes.

I like it!

**Comment by tburgin** [comment]
Dang, I spoke too soon - on reboot or when cfprefsd dies all extraneous values are purged and the mobileconfig values are restored. We do need to store the state key / values in another place. Also we have failed to handle configs set by the sync-server. Those will also need to be stored separately and override values from a mobileconfig or file config. Another smaller problem with this setup is that the SNTConfigurator is initialized per process. So santad could be looking at the config file while "santactl status" is looking at a newly installed mobile config.

State that is generated on the machine:
"FullSyncLastSuccess"
"RuleSyncLastSuccess"
"SyncCleanRequired"

Config that can come from a sync-server:
"ClientMode"
"WhitelistRegex"
"BlacklistRegex"
"SyncCleanRequired"

A new plan:
1) Create a new file that holds the config received from a sync-server.
2) Implement "sync-server > mobileconfig > config file" precedence on a key / value basis.

Take the ClientMode for example:
config file -> Monitor
mobileconfig -> Monitor
sync-server -> Lockdown

The effective configuration should be Lockdown.

Thoughts?

**Comment by tburgin** [comment]
A slight simplification: If a mobileconfig sets a SyncBaseURL, ignore all potential sync-server keys in that same mobileconfig. This will allow us to use the config.plist for storage and not have to introduce a second config file.

**Comment by jesseendahl** [comment]
@tburgin that sounds excellent!
