### ISSUE TITLE
Management server idea

### ISSUE THREAD

**Issue by ha0x7c7** [google/santa#214]
Hi, I know that this is not right place to ask, but I was wondering where can I find ideas about sync server behind santa? How blacklist/whitelist is managed for large groups of endpoints? 

Regards

**Comment by tburgin** [comment]
Hey, good question. There are a few open source implementations of sync servers:
  * https://github.com/zentralopensource/zentral/wiki
  * https://github.com/groob/moroz
We are also going to be talking more about our sync server solution at MacTech next week.
  * https://twitter.com/MacTechConf/status/920313719527235584

**Comment by msuozzo** [comment]
Look for https://github.com/google/upvote real soon :)

**Comment by ha0x7c7** [comment]
@msuozzo what is that? :)

**Comment by zercurity** [comment]
@ha0x7c7 zercurity can mange your Santa blacklist/whitelist for you ;)

**Comment by ha0x7c7** [comment]
@zercurity Thanks for the info, I am not looking for a ready to use product, actually I am looking for some sort of solution for applying black/white list to a big organization, more of a conceptual solution than concrete code, anyway your product seems to give me good idea.

**Comment by groob** [comment]
ha0x7c7  https://github.com/groob/moroz is a lightweight server that can manage santa rules across your fleet. 
It's a relatively small codebase if you just want to poke around.

**Comment by ha0x7c7** [comment]
@groob  Thank you very much for the link, I will have a look, I close this issue until we see what @msuozzo  will have for us :).
