### ISSUE TITLE
Checking IOSharedDataQueue available space before enqueuing new items

### ISSUE THREAD

**Issue by iradization** [google/santa#215]
Hi, 

According to the documentation of `IOSharedDataQueue` in `enqueue` method it says : 

"When attempting to add a new entry towards the end of the queue and there isn't enough space at the end, it wraps back to the beginning"

In Santa, I couldn't see any restriction for enqueueing new item to the decision_dataqueue_ , and I wonder if the design was to accept loosing older decision requests for the sake of new ones ? 

thanks

**Comment by russellhancox** [comment]
> I wonder if the design was to accept loosing older decision requests for the sake of new ones

That's correct, it's more important that we enqueue the newest requests at the expense of old ones.

**Comment by iradization** [comment]
I understand, but when you override old requests before they've reached the daemon (santad), isn't there a chance that you might wait on them forever in `SantaDecisionManager::GetFromDaemon`  

here's the relevant waiting loop : 

    do {
         msleep((void *)message->vnode_id, NULL, 0, "", &ts_);
         return_action = GetFromCache(identifier);
    } while (return_action == ACTION_REQUEST_BINARY && ClientConnected());

**Comment by russellhancox** [comment]
Oh, yes, that is possible. The msleep() call has a timeout but there's no longer a way to break from the inner loop to the outer loop unless the file is written to or the cache expires. We should fix that.

Good catch!
