### ISSUE TITLE
Remote Deployment.

### ISSUE THREAD

**Issue by iradization** [google/santa#217]
Hi, 

Starting from macOS High Sierra, Apple enforce manual authorization for drivers, which breaks my remote automation scripts. The technical note for this feature is [here](https://developer.apple.com/library/content/technotes/tn2459/_index.html)

Perhaps there's any way to avoid this step over and over again ? 
How are you dealing with mass deployment from remote ? 

thanks !

**Comment by groob** [comment]
You need to be enrolled in MDM to whitelist kernel extensions. 

See these articles for context: 
https://openradar.appspot.com/radar?id=4982094870609920
https://micromdm.io/blog/kext-whitelist/
http://www.richard-purves.com/2017/11/09/mdm-and-the-kextpocalypse-2/
