### ISSUE TITLE
Make postinstall script handle kextload failures better, consider GUI notification for kextload failure

### ISSUE THREAD

**Issue by TraderStf** [google/santa#223]
The installation took 1+ minute without any sign of activity.
A spinning or whatever to avoid user to kill the installation.
iMac (Retina 5K, 27-inch, Late 2014)
Net: 120 Gbps

FYI, The about/info is not helping... what will happen in case of? an alert dialog?

**Comment by tburgin** [comment]
Hello, are you running macOS 10.13? Did the install complete? If so what is the output of `santactl status`.

**Comment by TraderStf** [comment]
Yes 10.13.1
santactl status
"An error occurred communicating with the daemon, is it running?"

In Activity Monitor, Santa is running.

I think only app that could intercept are my AVG or Ransomwhere from patrick wardle.

**Comment by tburgin** [comment]
Starting with macOS 10.13, kexts need to be user approved. See https://github.com/google/santa/issues/217

You do need to get santad running. I am not sure how AVG or Ransomwhere work, they may be stomping on santad.

**Comment by pmarkowsky** [comment]
Closing this, as we're planning on deprecating the KEXT in the next release.
