### ISSUE TITLE
macOS update to 10.13.2 (17C205) false warning

### ISSUE THREAD

**Issue by TraderStf** [google/santa#228]
When the mac restarts after the update Santa wakes up to cry =-)

![sa](https://user-images.githubusercontent.com/5954335/34737234-dc2675e2-f575-11e7-8b3f-559e8d9d1a69.jpg)

**Comment by tburgin** [comment]
For any specific machine there could be many reasons for Santa to block an execution. A lot depends on the mode (Lockdown or Monitor) you are running in. In this case it looks to me like the app in question has a missing __PAGEZERO segment. By default `EnablePageZeroProtection` is enabled and will stop apps like that from running.

See https://github.com/google/santa/blob/master/Docs/deployment/configuration.md#local-configuration for more information on all configuration options.

```sh
santactl fileinfo /Applications/World\ Route.app --key "Page Zero"
__PAGEZERO segment missing/bad!
```

**Comment by russellhancox** [comment]
It looks like Tom has identified the cause for this blockage and it looks like it's working-as-intended. If you have any further questions feel free to re-open.
