### ISSUE TITLE
An error occurred communicating with the daemon

### ISSUE THREAD

**Issue by xorrior** [google/santa#236]
macOS 10.12 (VM)

After completing the installation, all santa components seem to be running but I am unable to get any output from santactl status. Both santa and the kernel extension, santad are running. I didn't receive any error messages during the installation process, so I'm not sure what's wrong.

**Comment by russellhancox** [comment]
Does "kextstat | grep santa-driver" give you any output?

If you open System Preferences > Security, do you see a warning that a kext has been blocked from loading?

**Comment by xorrior** [comment]
@russellhancox I don't have any warnings stating that the kext has been blocked. 
![kextstat](https://user-images.githubusercontent.com/9156069/35824387-b5f8cba2-0a80-11e8-9c12-b3e45f73a9f9.png)

**Comment by xorrior** [comment]
I'll also add that this entry is present in the system.log file: 
com.apple.xpc.launchd[1] (com.google.santad): This service is defined to be constantly running and is inherently inefficient.

There is also an entry for com.google.santagui

**Comment by xorrior** [comment]
I set this up on a fresh VM and everything worked fine. This can be closed out.
