### ISSUE TITLE
Unable to get Plist Blacklisting to work

### ISSUE THREAD

**Issue by jdziat** [google/santa#24]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>BlacklistRegex</key>
        <string>^/Applications/Utilities/[.]{1,}|^/Users/[.]{1,}</string>
        <key>ClientMode</key>
        <integer>1</integer>
        <key>WhitelistRegex</key>
        <string>^/Applications/[0-9A-Za-z\ ]{1,}</string>
</dict>
</plist>

Does this look correct? I'm not able to get it to work.

**Comment by russellhancox** [comment]
For the blacklist regex, what are you trying to match? If you're trying to block anything in either /Applications/Utilities and /Users that has a period in it, you'll need: `^(?:/Applications/Utilities|/Users)/.*?\\.{1,}`

If you just wanted to match anything under those two folders, then this should work: `^(?:/Applications/Utilities|/Users)/.*`

If you wanted to match anything in those folders that begins with a period, then what you had should work.

The whitelist regex should work, though you'll need to put two \ in front of the space: `[0-9A-Za-z\\ ]{1,}` or you could probably replace with `\\w`.

Bear in mind that the blacklist is tested before the whitelist.

**Comment by russellhancox** [comment]
Did that help?

**Comment by jdziat** [comment]
Yes that did. Thank you

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On Wed, Oct 14, 2015 at 2:25 PM, google/santa
<reply@reply.github.com>
wrote:
Did that help?

—
Reply to this email directly or view it on GitHub
[https://github.com/google/santa/issues/24#issuecomment-148144907] .[https://github.com/notifications/beacon/ABITys4bfueBcb6M6Y3bGqDBX0MYkSd4ks5o7pWRgaJpZM4GAYAr.gif]

**Comment by russellhancox** [comment]
Excellent.
