### ISSUE TITLE
Possible vnodeID conflicts with APFS

### ISSUE THREAD

**Issue by timo-christ** [google/santa#262]
Hi,
When browsing over your Driver Code I noticed that you combine the File System ID with the File ID to one 64 bit Vnode ID. 
This worked fine with HFS/HFS+ since it restricted itself to use only 32bits for the file id. But If I'm not mistaken APFS takes actually advantage of all 64 bits.
Are you ok with this conflict?

Best Regards
Timo

**Comment by russellhancox** [comment]
We've been keeping an eye on this, thus far it hasn't been an issue but it's something we're going to fix anyway to be on the safe side. I'll keep this open for tracking

**Comment by russellhancox** [comment]
The fix I mentioned was released in 0.9.27 (which has already been superseded by 0.9.28)
