### ISSUE TITLE
Possibility of using Santa without a Configuration Profile?

### ISSUE THREAD

**Issue by Stop-playing** [google/santa#268]
Hey all, 

I've been interested in utilizing santa and it's blacklisting capabilities on my personal Mac.  However, I was wondering if it is still possible, effective, to use santa without a configuration profile.  In other words: downloading the signed installer, installing it, and then using `sudo santactl rule --blacklist --path /path/to/evil.app`.  

My goal is to simply prevent the execution of certain apps/binaries/packages, and wanted to know how, if at all, santa would be effected if my Mac did not have a configuration profile installed, but still had the kext and santa binaries running.

Thanks for any help, and I apologize if this isn't the right place to pose a question.  I checked the santa-dev group, but it looked like the last post was from 2017, so thought I'd ask here.

Thanks again

**Comment by tburgin** [comment]
Hey, good question. You can run without an configuration. It will default to Monitor mode. You can add blacklisted rules with the `santactl rule` command. Let us know if you run into any unexpected.

**Comment by Stop-playing** [comment]
Thank you for the quick response; I'm going to try it out and provide any updates if I encounter issues/unexpected behaviors.

**Comment by russellhancox** [comment]
If you do find any issues, please feel free to re-open this or create a new issue.
