### ISSUE TITLE
ksfetch is annoying

### ISSUE THREAD

**Issue by thevoidboy** [google/santa#27]
Keystone puts an executable into a folder in /tmp.
And constantly gets flagged by Santa, regardless of any futile effort to whitelist it.
There are probably explanations for it, but it is a bit annoying.

Ironic, too.

**Comment by russellhancox** [comment]
ksfetch should be codesigned by "Developer ID: Google Inc" which currently has the SHA256 "15b8ce88e10f04c88a5542234fbdfc1487e9c2f64058a05027c7c34fc4201153".

Is that not what you're seeing?

**Comment by thevoidboy** [comment]
Over and over again. 

- David

**Comment by russellhancox** [comment]
I was going to suggest whitelisting that certificate to whitelist it until I realized the "santactl rule" command doesn't currently support certificate rules. I'm fixing that now.

**Comment by russellhancox** [comment]
Right, with d905f5b09518a7adda8be7f78d0b5ec5780c2e93 it is now possible to add certificate whiltelist rules, like so:

sudo santactl rule --whitelist --certificate --sha256 15b8ce88e10f04c88a5542234fbdfc1487e9c2f64058a05027c7c34fc4201153

This will be included in the next release.

**Comment by thevoidboy** [comment]
Thanks!
I'll test further.

**Comment by russellhancox** [comment]
Did that help?

**Comment by thevoidboy** [comment]
I'm sorry. 
Yes. It appears to have. 
Didn't I notify? My bad. 


-J David Hester, PhD
Alt Pibroch Club 
www.altpibroch.com 

“I believe the only excuse we have for being musicians
     and for making music in any fashion
          is to make it differently.”
               — Glenn Gould

**Comment by russellhancox** [comment]
No worries.
