### ISSUE TITLE
Change rule sync to auto-include required cert rules

### ISSUE THREAD

**Issue by russellhancox** [google/santa#291]
Currently the `addRules:cleanSlate:error` method in SNTRuleTable will fail if the `cleanSlate` is true and the rules array doesn't include the 2 required rules (launchd and santad's signing certs). On reflection, this was a poor design choice that just over-complicates things and makes syncing more likely to fail. This should be changed so that the 2 required rules are prepended to the array implicitly.

**Comment by pmarkowsky** [comment]
Marking closed as it's obsolete.
