### ISSUE TITLE
Rake aborted when building: SecKeychainSearchCopyNext, specified item not found in keychain

### ISSUE THREAD

**Issue by madamadami** [google/santa#294]
I wanted to build by command "rake build:release" and got following error on macOS 10.13.6:

```
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
rake aborted!
OpenSSL::X509::CertificateError: header too long
/Downloads/santa/Rakefile:52:in `initialize'
/Downloads/santa/Rakefile:52:in `new'
/Downloads/santa/Rakefile:52:in `block in <top (required)>'
/Downloads/santa/Rakefile:81:in `block (2 levels) in <top (required)>'
Tasks: TOP => build:build => init
(See full trace by running task with --trace)

```

**Comment by russellhancox** [comment]
Do you have an Apple developer certificate installed in your keychain?

**Comment by madamadami** [comment]
No, I haven't! I am a newbie to building apps.

**Comment by russellhancox** [comment]
Because all of the components of Santa must be code-signed to work, we expect a developer certificate to be installed in your keychain. You can sign up for an Apple Developer account to acquire certificates.

**Comment by madamadami** [comment]
Thank you for explaining me! But as I see, I'll have to pay for a certificate because you have to purchase for the apple developer program. Since I just want to build "santa" from sources, this is too much cost for one app.

**Comment by russellhancox** [comment]
If you don't want to sign up for an Apple developer account, you have 2 options as I see it:

1) Don't build from source, use the prebuilt releases on the Releases page.
2) Self-sign a certificate and modify the Rakefile (line 51-57) and the Xcode project to use this self-signed certificate.
