### ISSUE TITLE
Provide custom parameters to syncBaseURL

### ISSUE THREAD

**Issue by ameyah** [google/santa#306]
Hello,

I want to insert custom parameters in the syncBaseURL (access tokens, etc.). I tried several methods including percent encoding and other hacky stuff, but some code is stripping the parameters (couldn't locate the code).

Is there a way to include GET parameters in the base URL? If not, can this be treated as an enhancement request?

**Comment by tburgin** [comment]
The `SyncBaseURL` doesn't support any expansion. You could use the MachineID configuration options to send something other than the machine uuid.

`MachineID` = 123
The URL would then be build out like this for each request.
https://server.com/api/santa/preflight/123
https://server.com/api/santa/eventupload/123
https://server.com/api/santa/ruledownload/123
https://server.com/api/santa/postflight/123

You can get a little more dynamic by specifying a plist and a key that will be used to fetch the value.
`MachineIDPlist` = /Library/Preferences/com.server.awesomecompany.config.plist
`MachineIDKey` = AwesomeKey
https://server.com/api/santa/preflight/AwesomeValue
etc...

Key | Type | Description
-- | -- | --
MachineID | String | The machine ID.
MachineIDPlist | String | The path to a plist that contains the MachineOwnerKey / value pair.
MachineIDKey | String | The key to use on MachineIDPlist.

It all depends on sync server you are using / developing with how these requests will be interpreted.

For strong machine identification you may want to look at the ClientAuthCertificate* configuration options.

https://github.com/google/santa/blob/master/Docs/deployment/configuration.md

**Comment by ameyah** [comment]
Thanks for the detailed explanation @tburgin :)

The machineID trick worked. I was trying out access tokens for simplicity.
