### ISSUE TITLE
Unclear rule enforcement behavior and possible bugs

### ISSUE THREAD

**Issue by thehesiod** [google/santa#314]
I think what's really missing is a decision graph.

From what I gather the code flow looks something like:

```
Decision for a file path:
	SNTPolicyProcessor:decisionForFilePath (https://github.com/google/santa/blob/master/Source/santad/SNTPolicyProcessor.m#L132) ->
		SNTPolicyProcessor.decisionForFileInfo (https://github.com/google/santa/blob/master/Source/santad/SNTPolicyProcessor.m#L39) ->
			SNTRuleTable:ruleForBinarySHA256 (https://github.com/google/santa/blob/master/Source/santad/DataLayer/SNTRuleTable.m#L184) ->
				find first file/cert rule: "SELECT * FROM rules WHERE (shasum=? and type=1) OR (shasum=? AND type=2) LIMIT 1" 
				
				SNTRuleTable:ruleFromResultSet (https://github.com/google/santa/blob/master/Source/santad/DataLayer/SNTRuleTable.m#L176)
		(decisionForFileInfo)
		if rule, make decision for rule returned (binary: whitelist/silent-blacklist/blacklist/whitelist-compiler/whitelist-transitive), or (certificate: whitelist/silent-blacklist/blackist)
		
		if blacklisted scope (regex), blacklist
		if whitelisted scope (regex), whitelist
```

First issue it seems is that when it's looking up rules from the local DB, it just picks the first rule returned by the statement `SELECT * FROM rules WHERE (shasum=? and type=1) OR (shasum=? AND type=2) LIMIT 1`.  There could be a certificate rule AND a binary rule, and they may not both have the same policy (white/black list).

The other part I couldn't figure out is how Bundle based rules are enforced, if at all.  Could someone clarify?

Another issue is that it seems that Blacklist should always outweigh whitelist.  Right now for example if there's a path based blacklist, but a binary whitelist, the binary whitelist will out weight the path blacklist.

The end goal for me is updating https://github.com/farmersbusinessnetwork/upvote/blob/master/upvote/gae/modules/upvote_app/frontend/web_ui/components/statechip/statechip-filter.js#L39 to do the right thing

**Comment by russellhancox** [comment]
We don't have a graph but the [documentation](https://santa.readthedocs.io/en/latest/details/rules/#rule-evaluation) does describe the process. 

To your other questions:

> There could be a certificate rule AND a binary rule, and they may not both have the same policy (white/black list).

That's true - in this case it will return the binary rule if there is one. A binary rule is more specific than a certificate rule, so it wins.

> The other part I couldn't figure out is how Bundle based rules are enforced, if at all. Could someone clarify?

There is no such thing as a Bundle rule - Santa uploads details about bundles to the server, which allows the server to allow voting on a bundle as a single entity but the rules that come down from these votes are for the specific binaries themselves. Evaluating bundle information during execution time would be far too expensive.

> Another issue is that it seems that Blacklist should always outweigh whitelist. Right now for example if there's a path based blacklist, but a binary whitelist, the binary whitelist will out weight the path blacklist.

As I mention above, rule evaluation is done from most to least specific. While on the face it seems obvious that a blacklist should always overrule a whitelist, it makes rule evaluation slower and prevents some useful management opportunities.

Does that help?

**Comment by thehesiod** [comment]
great thanks, that helps, however:

> > There could be a certificate rule AND a binary rule, and they may not both have the same policy (white/black list).
> 
> That's true - in this case it will return the binary rule if there is one. A binary rule is more specific than a certificate rule, so it wins.

how is it that the binary rule will win?  To my understanding, the SQL statement does not guarantee an ordering to the rows returned, and in this case there would be two rows to return, the the limit causes it to pick the first one the DB decided to return first.

**Comment by russellhancox** [comment]
You're right, thought at least with current versions of SQLite the ordering is stable and skipping the `ORDER BY type DESC` that we'd need to make this explicit saves 14 ops in each query.

**Comment by thehesiod** [comment]
ok, well, it may be stable, but's not determinable, and thus to clients random ;)  Sounds like it needs to be done?

**Comment by thehesiod** [comment]
hmm, per: https://stackoverflow.com/a/24238164/1241593 

```
By default, the rows are logically stored in order of increasing rowid.

And if your select stament does not include an order by, or the table has no index, the default sorting order will always be the primary key column, which is the _ID column in this case
```

do you guys re-create the table each time, and maintain the order?  If so, this merits some giant comments where the table is updated + on this select line.

**Comment by thehesiod** [comment]
looks like it is a bug, you guys don't enforce the binary rules come before certs in the table: https://github.com/google/santa/blob/master/Source/santad/DataLayer/SNTRuleTable.m#L234

**Comment by russellhancox** [comment]
No, it's stable and deterministic. There is an index on the table and the query is run against the index in order of the provided constraints and short-circuited upon a match - you can use the EXPLAIN statement on the rules.db to see what happens or just do a query for binary/cert rules in various orders to see the result.

**Comment by thehesiod** [comment]
probably worth a comment where the index is created and where the select is performed so it's not changed in the future
