### ISSUE TITLE
Changing lockdown mode on local machine

### ISSUE THREAD

**Issue by ThunderousDreamer** [google/santa#340]
So I'm not sure if the documentation is missing items or I'm just not reading this right (I truly tried...).

I'm testing this out on a macbook using a local db. I've added roughly 6 apps to whitelist, and now want to change the mode from monitor to lockdown. I can't find the command line or config file where to do this. Is this documented, am I just missing something?

Thanks

**Comment by tburgin** [comment]
No worries!
https://github.com/google/santa/blob/master/Docs/details/mode.md#changing-modes

**Comment by ThunderousDreamer** [comment]
Thank you. I was reading that but got a bit confused as there seems to be no default configurationprofile file for the local machine without a sync server (or I missed it) and I also don't have the .plist file as it's retired, which most articles from 2016 are suggesting I look.

`profiles-list` also comes up blank.

Do I need to generate a custom .mobileconfig with the LOCKDOWN mode and my file hashes specified, load it using `profile install <filename>`  and then reload Santa? Or are you suggesting it will dynamically pick up the rules I added using `santactl rule --whitelist --path <X>`

Thanks again for the help

**Comment by tburgin** [comment]
There is no default profile. You can choose to install one if you wish. Here is an example:
https://github.com/google/santa/blob/master/Docs/deployment/com.google.santa.example.mobileconfig

You can modify that example for your needs. If you just wanted to manage the ClientMode, you could install a profile like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.google.santa</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>ClientMode</key>
								<integer>2</integer>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>0342c558-a101-4a08-a0b9-40cc00039ea5</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>0342c558-a101-4a08-a0b9-40cc00039ea5</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>com.google.santa</string>
	<key>PayloadDisplayName</key>
	<string>com.google.santa</string>
	<key>PayloadIdentifier</key>
	<string>com.google.santa</string>
	<key>PayloadOrganization</key>
	<string></string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>9020fb2d-cab3-420f-9268-acca4868bdd0</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
```

The profile is not associated with rules. You add rules either manually or by using a sync server.

**Comment by ThunderousDreamer** [comment]
Thank you, very clear! I create/modify this file for my Mac, load it, and it will switch Santa into the mode needed. Then when (or if) I conclude my initial testing I can even update the config to use a sync server too, thanks!

**Comment by eopeter** [comment]
I am trying to change a client from monitor to lockdown without using a sync server or local mobileconfig. Is there way to do this? Can `santactl` be used to lockdown? I do not see any such options in the CLI help

**Comment by russellhancox** [comment]
No, you can only manage this with a profile or a sync server. We're planning this year to add better support for "standalone" clients but as of right now Santa isn't designed for this use-case.
