### ISSUE TITLE
Not being able to re-install Santa.app after deleting from ‘Application folder

### ISSUE THREAD

**Issue by tonynotears** [google/santa#341]
Not being able to install from the .dmg in the release after manually deleting the Santa.app. Santactl is there, but SantaGUI is still shown as null in santactl verision

**Comment by tburgin** [comment]
Ooops, that is most likely the case. We will make sure the next release does not allow relocation.
```
⇒  pkgutil --expand-full /Volumes/santa-0.9.30/santa-0.9.30.pkg /tmp/santa-0.9.30
⇒  grep /relocate -B2 /tmp/santa-0.9.30/PackageInfo
    <relocate>
        <bundle id="com.google.SantaGUI"/>
    </relocate>
```
