### ISSUE TITLE
Driver: replace some scalar interfaces with structs

### ISSUE THREAD

**Issue by russellhancox** [google/santa#342]
Two existing methods on the driver interface exist just to expose stats:

`cache_count`
`cache_bucket_count`

These could be unified and extended with a `get_stats` method that returns a struct containing all the counters we'd want to expose. Some additional stats that would be nice to have: cache hits, cache misses, EXEC counts, WRITE counts, etc.

In the same vein, we have some methods for setting things that could be unified and replaced:

`clear_cache`
`filemod_prefix_filter_add`
`filemod_prefix_filter_reset`

These could be replaced with a `set_options` method that again takes a struct containing the new values. Other options that could be added: cache sizes, cache load factors.

**Comment by pmarkowsky** [comment]
Marking this as closed as we're deprecating the driver soon.
