### ISSUE TITLE
New to Santa: any public Santa sync servers for individual users? (monitor mode)

### ISSUE THREAD

**Issue by JayBrown** [google/santa#358]
I've been running santa for a couple of months, and except for one malware test it remained quiet in the background.

I haven't synchronized to any server, because I don't know any, so my question is: are there already public Santa sync servers that can be used by Santa set up on an individual machine? Maybe a server that specializes on known malware and code-signing certificates used to sign malware?

If not, does Santa come with any baked-in rules? I'm asking because even though I never synched to anything Santa still detected & blocked a malware launch (my own test).

**Comment by russellhancox** [comment]
> are there already public Santa sync servers that can be used by Santa set up on an individual machine

Not that we're aware of. There's nothing stopping someone from setting one up except convincing others to trust their judgement. I've long thought a community sync server could work really well but establishing the governance model would take some serious thought.

Unfortunately, for legal reasons, we're not allowed to run a public server nor distribute the rules we use internally.

> does Santa come with any baked-in rules?

Sort of:

1. On startup, santad will get the code signature for itself and for pid 1 (launchd) and ensure the signing certificates for both are whitelisted. This is to prevent Santa from blocking itself or core parts of the OS.

2. Santa will, by default, block any 32-bit binary with a missing __PAGEZERO segment. The OS already blocks 64-bit binaries missing this segment.

> even though I never synched to anything Santa still detected & blocked a malware launch

The 2 easiest ways to find out /why/ Santa blocked something are to either look in the logs or, if you still have the binary, run `santactl fileinfo /path/to/binary` and it will tell you what decision would be made.
