### ISSUE TITLE
santa/Conf/uninstall.sh update?

### ISSUE THREAD

**Issue by 3skr0** [google/santa#360]
can you update the uninstall script regarding the last release ?

**Comment by russellhancox** [comment]
I don't believe any changes are needed to uninstall.sh from the last release. The line that removes `/Applications/Santa.app` is arguably unnecessary now but it's also harmless and ensures we clean up from any older releases.

Am I missing something?

**Comment by tburgin** [comment]
Are you referring to this line?
https://github.com/google/santa/blob/8198e597363d5c3068e6470e95ff7fe02559b369/Conf/uninstall.sh#L17
We decided to keep this around in case someone was still running a version older and wanted to run the uninstall script.
