### ISSUE TITLE
Pls update docs (re config) for standalone users

### ISSUE THREAD

**Issue by hardmac** [google/santa#368]
Hello

New to santa. Running 0.93 on Sierra. Trying to work out how configuration (specifically ClientMode setting) is done. plist file is no longer used since santa moved to Apple's configuration profile method (documented).  As I understand it, the system is set up to apply profiles hierarchically: Sync server > .mobileconfig (gleaned from issue 295). Don't see any evidence of any .mobileconfig files so i am assuming that clientMode is being defaulted and in order to change it i would need to set up my own .mobileconfig file and then load it using the profiles command. Is that correct (am also new to profiles)?

Thanks in advance
mainoo

**Comment by russellhancox** [comment]
(cross-post from the santa-dev list)

We have a bit of documentation about this here: https://santa.readthedocs.io/en/latest/deployment/configuration/

That doc includes an example mobileconfig that you can modify as you see fit. 

To install the configuration profile, either double-click the mobileconfig file in Finder or from the command-line use

`sudo profiles -I -F <path-to-mobileconfig>`

The profiles command has a number of options for installing and removing profiles. There's also a **Profiles** preference pane that you can use for viewing, adding and removing profiles.

Hope that helps.
