### ISSUE TITLE
Question re: macOS Configuration Profile used to enroll client to Upvote server

### ISSUE THREAD

**Issue by ghigliottyc** [google/santa#371]
Hiya,

This isn't an issue but rather a question about enrolling macOS clients to the Google Upvote sync server—

Once the SyncBaseURL is set what does the enrollment process for a macOS Santa client <> Upvote sync server look like? Does the macOS Santa client present a client cert or shared secret to the Upvote server or will the Upvote server accept any Santa client that has the enroll endpoint?

**Comment by tburgin** [comment]
Santa can be configured to present a client certificate with the` ClientAuthCertificate*` keys. You can also pin with the `ServerAuthRoots*` keys.

https://github.com/google/santa/blob/master/Docs/deployment/configuration.md

I forget what auth options Upvote + App Engine support. I think it may be tricky to get client cert auth configured correctly.
