### ISSUE TITLE
Blacklisted binaries still allow the apps to open.

### ISSUE THREAD

**Issue by lgmke** [google/santa#385]
To preface: I am extremely new to the command-line.

I've installed Santa on a Mac and even after blacklisting a few applications (/applications/news.app, /applications/messages.app, etc), it still allows the apps to open. Santa is in monitoring mode, 

`santactl fileinfo` for the apps shows "Rule: Blacklisted (Binary)". 

`santactl rule --blacklist --certificate ####` for blacklisting the SHA-256 certs returns "Unknown argument: ####"

Has anyone got an idea of how to fix or try next?

**Comment by russellhancox** [comment]
Could you paste some of the fileinfo output here?

I'm also confused by the certificate blacklist bit in your comment - you won't be able to blacklist things like News.app or Messages.app because they're signed with the same certificate that the rest of the OS is signed with and Santa won't let you break your machine that easily. You should be able to block both of those binaries by the hash though.

For example, this worked for me:

```shell
» sudo santactl rule --blacklist --path /Applications/News.app
Added rule for SHA-256: 5e1f42bd2533117c4c2c61b844a7848414f70be37c0787cc8f93c5a6cfe87ff1.
» open /Applications/News.app
LSOpenURLsWithRole() failed with error -54 for the file /Applications/News.app.
```

**Comment by lgmke** [comment]
```
machine:~ root# sudo santactl rule --blacklist --path /Applications/News.app
Added rule for SHA-256: 5e1f42bd2533117c4c2c61b844a7848414f70be37c0787cc8f93c5a6cfe87ff1.
machine:~ root# open /Applications/News.app
machine:~ root# santactl fileinfo /Applications/News.app
Path                   : /Applications/News.app/Contents/MacOS/News
SHA-256                : 5e1f42bd2533117c4c2c61b844a7848414f70be37c0787cc8f93c5a6cfe87ff1
SHA-1                  : 0011ac561e967cd10ce204f6a245c82352d40552
Bundle Name            : News
Bundle Version         : 2166
Bundle Version Str     : 4.4
Type                   : Executable (x86_64)
Code-signed            : Yes
Rule                   : Blacklisted (Binary)
Signing Chain:
    1. SHA-256             : 2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32
       SHA-1               : 013e2787748a74103d62d2cdbf77a1345517c482
       Common Name         : Software Signing
       Organization        : Apple Inc.
       Organizational Unit : Apple Software
       Valid From          : 2013/04/12 17:34:35 -0500
       Valid Until         : 2021/04/12 17:34:35 -0500

    2. SHA-256             : 5bdab1288fc16892fef50c658db54f1e2e19cf8f71cc55f77de2b95e051e2562
       SHA-1               : 1d010078a61f4fa4694aff4db1ac266ce1b45946
       Common Name         : Apple Code Signing Certification Authority
       Organization        : Apple Inc.
       Organizational Unit : Apple Certification Authority
       Valid From          : 2011/10/24 12:39:41 -0500
       Valid Until         : 2026/10/24 12:39:41 -0500

    3. SHA-256             : b0b1730ecbc7ff4505142c49f1295e6eda6bcaed7e2c68c5be91b5a11001f024
       SHA-1               : 611e5b662c593a08ff58d14ae22452d198df6c60
       Common Name         : Apple Root CA
       Organization        : Apple Inc.
       Organizational Unit : Apple Certification Authority
       Valid From          : 2006/04/25 16:40:36 -0500
       Valid Until         : 2035/02/09 15:40:36 -0600

machine:~ root# 
```

News.app did open when I typed the second command. Messages.app does the same thing.

**Comment by russellhancox** [comment]
Is the kernel extension loaded?

`santactl status`
`kextstat | grep com.google.santa`

**Comment by lgmke** [comment]
```
machine~ root# santactl status
>>> Daemon Info
  Driver Connected          | No
  Mode                      | Monitor
  File Logging              | No
  Watchdog CPU Events       | 0  (Peak: 0.68%)
  Watchdog RAM Events       | 0  (Peak: 11.46MB)
>>> Kernel Info
  Root cache count          | 0
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 2
  Certificate Rules         | 2
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 0
machine:~ root# kextstat | grep com.google.santa
machine:~ root# 
```

Thanks for taking the time to troubleshoot with me by the way.

**Comment by russellhancox** [comment]
OK, the driver isn't loaded which is why it's not blocking anything. This is almost certainly caused by "user-approved extension loading". 

If you run this:

```sudo kextload /Library/Extensions/santa-driver.kext```

And then open `System Preferences`, `Security` you may see something like "System software from developer "Google LLC" was blocked from loading. If you click the Allow button, Santa should then be loaded, you can verify with `santactl status` again (look at the "Driver Connected" line).

See Apple [TN2459](https://developer.apple.com/library/archive/technotes/tn2459/_index.html) for more info

**Comment by lgmke** [comment]
You are my savior, I've been working on this for a day!! Thank you so much, this solved the problem immediately.
