### ISSUE TITLE
How to utilize Message feature?

### ISSUE THREAD

**Issue by lgmke** [google/santa#386]
Hello, I'm feeling dumb again. When setting rules, you can set a custom message and I cannot figure out the syntax of how to make it work and the Docs don't have anything about it.

I've tried:
sudo santactl rule --message {message}
sudo santactl rule --message {message}: message
sudo santactl rule --message {message}: "message"
sudo santactl rule --blacklist --path <path> --message
etc.

Does anyone know how I can write a custom block message?

**Comment by russellhancox** [comment]
```shell
sudo santactl rule --blacklist --path /Applications/News.app --message "The news is bad, you don't need to read it."
open /Applications/News.app
```

**Comment by lgmke** [comment]
Thank you so much! And is there a way to put it back to the default if need be?

**Comment by russellhancox** [comment]
Just add the rule again without the message:

```
sudo santactl rule --blacklist --path /Applications/News.app
```

That'll replace the existing rule and drop the custom message.

**Comment by lgmke** [comment]
You're a hero, Russell.
