### ISSUE TITLE
Stop pop up from appearing when something is blocked

### ISSUE THREAD

**Issue by bfuzzy1** [google/santa#399]
Is there a way I can prevent the pop up from occurring every time something is blocked on the endpoint?

**Comment by russellhancox** [comment]
There are several options here, depending on what you're trying to achieve:

1. If you just want to block a single binary or certificate and produce no notifications when those blacklisted items are blocked, you can create a "silent-blacklist" rule. Using `santactl` to do that: 

    `santactl rule --silent-blacklist --path /path/to/file`

2. If you want to stop repeated notifications for something that's being blocked regularly, there's a checkbox at the bottom of the block window labelled: "Prevent future notifications for this application for a day". This only prevents the notifications for 24 hours but can be helpful.

3. If you want to prevent **all** GUI notifications, there isn't a _fully supported_ way of doing that but you can unload the GUI agent:

    `launchctl remove com.google.santagui`

    If you want to make this persist across reboots (which will remain until you undo it or install a new version of Santa)

    `launchctl unload -w /Library/LaunchAgents/com.google.santagui.plist`

    If this is what you want, can I ask why? I would expect things being blocked but having no notification of why would be confusing to whoever is using the machine. If there's a use case for this that we haven't thought of, we can consider adding a preference for it.

**Comment by bfuzzy1** [comment]
Ok, this helps somewhat. I knew the end-user could silence for 24hrs, which is fine for most binaries. My use case is that a product is due to be removed from endpoints but in the meantime needs to be "disabled" from each endpoint. The product does try to execute every day and I am unsure of the timeline for the product removal from all the endpoints so it would be best to block and prevent pop up from happening for "user experience" purposes. 

I think it would be a good idea to have this built-in so that we could just push an updated config file instead.

**Comment by russellhancox** [comment]
Gotcha. It sounds like option 1 might fit well - you could add silent blacklist rules for the product you're going to remove (either by hash, or if you don't need to run anything else by the same publisher the signing cert) - the product will be disabled and users won't get notifications.

**Comment by bfuzzy1** [comment]
Awesome. Thank you.
