### ISSUE TITLE
Transitive rules with Xcode

### ISSUE THREAD

**Issue by leohidalgo** [google/santa#407]
It's possible to configure the transitive rules to allow me to run the apps compiled by Xcode?

I currently have to put santa in monitor mode 🙁 .

**Comment by leohidalgo** [comment]
I'm enabling both and it's still blocking execution.

```
sudo santactl rule --compiler --path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
```

```
sudo santactl rule --compiler --path /usr/bin/codesign
```

**Comment by leohidalgo** [comment]
I don't have multiple Xcode version.

> santactl status | grep Transitive

**output**
`Transitive Rules          | 0`

**Comment by russellhancox** [comment]
OK, can you provide the full output of `santactl status` and `santactl version` ?

**Comment by leohidalgo** [comment]
To add a transitive rule should I run this?

`sudo santactl rule --compiler --sha256 XCODE_HASH`

**Comment by leohidalgo** [comment]
I missed compiler rule for `/Applications/Xcode.app/Contents/MacOS/Xcode`, now works well, thank for help me

**Comment by russellhancox** [comment]
You're welcome

**Comment by leohidalgo** [comment]
I formatted my machine and only needed to add `/usr/bin/codesign` as a compilation rule.
