### ISSUE TITLE
Update build instructions in docs

### ISSUE THREAD

**Issue by craig-merchant** [google/santa#411]
I've done a git clone of the repository and done a git checkout 0.9.33.

I cd into the santa directory and try to run bazel.  I get the following errors:

bash-3.2# bazel build :santa-driver -c opt
INFO: Writing tracer profile to '/private/var/tmp/_bazel_root/325f304470cf2fbcf3959069b35e113a/command.profile.gz'
ERROR: Skipping ':santa-driver': no such target '//:santa-driver': target 'santa-driver' not declared in package '' defined by /Users/tokenvault/santa/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//:santa-driver': target 'santa-driver' not declared in package '' defined by /Users/tokenvault/santa/BUILD
INFO: Elapsed time: 0.136s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

I'm running the most recently patched version of Mojave.

**Comment by russellhancox** [comment]
Try:

`bazel build //Source/santa_driver -c opt`

**Comment by russellhancox** [comment]
I see now that the instructions in our docs are wrong, we'll get those fixed up.
