### ISSUE TITLE
Untrusted kexts are not allowed

### ISSUE THREAD

**Issue by craig-merchant** [google/santa#412]
I've built the santa-driver on Mojave.  When I try and load the kext, I get the following error:

Untrusted kexts are not allowed
Kext with invalid signature (-67050) denied: /Library/StagedExtensions/Library/Extensions/BD39B022-DD5F-4185-907D-DD1390BDB66A.kext
Bundle (/Library/Extensions/santa-driver.kext) failed to validate, deleting: /Library/StagedExtensions/Library/Extensions/BD39B022-DD5F-4185-907D-DD1390BDB66A.kext
Unable to stage kext (/Library/Extensions/santa-driver.kext) to secure location.
bash-3.2# kextload santa-driver.kext
/Library/Extensions/santa-driver.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).

Is it possible to install santa without disabling SIP?  I don't think Mojave gives you a way to whitelist an individual, unsigned kext.

**Comment by russellhancox** [comment]
You have 2 options:

1. Disable SIP
2. Install the pre-signed version of the kext that we provide (https://github.com/google/santa/releases).

Unless you want to make changes the kext, I'd stick with option 2.
