### ISSUE TITLE
[QUESTION] If a user copies an application to a separate location, Santa will not block it if it's only blocking by file path and not by signature, correct?

### ISSUE THREAD

**Issue by lgmke** [google/santa#417]
I'm trying to block the Messages app which cannot be blocked by signature as that would block most other parts of macOS. So, I've created a rule to block it by file path: sudo santactl rule --blacklist --path /applications/messages.app 

By this reasoning, if the user somehow copies the entire Messages program onto their Desktop (for example, you can choose any other folder besides Applications), Santa would not block it, correct? Is there a way to block Messages by signature that won't block most of the OS? I'm not a dev so the Docs are a bit hard to understand from the technical level.

**Comment by tburgin** [comment]
Good question: Santa doesn't have rules that block based on path. The `--path` flag is a convenience used to create rules based on the passed in app.

`sudo santactl rule --blacklist --path /Applications/Messages.app` will create a binary blacklist rule for the Messages.app. It will be blocked from executing, no matter where it lives on disk.

Binary rules only apply to the exact version of the app they represent. If Apple updates the Messages.app, a new rule must be added to blacklist it.

`santactl help rule` has some more info on the rule command.

**Comment by lgmke** [comment]
Okay, thanks. I'm trying to set my MDM to run a command as root every time the user logs in to run the command `santactl rule --blacklist --path /applications/messages.app`, but I'm receiving an error that says `/bin/bash: santactl: command not found`

Do you know why that might be? Wouldn't the root directory have access to the program on the machine that I've confirmed has Santa installed?

**Comment by tburgin** [comment]
The environment that is running the command might not have PATH set to search "/usr/local/bin/". Try using the full path: `/usr/local/bin/santactl`

**Comment by lgmke** [comment]
That solved the issue, thank you!
