### ISSUE TITLE
santa 0.9.9 doesn't report all names correctly 

### ISSUE THREAD

**Issue by headmin** [google/santa#44]
I've noticed certain machine names will not reported back correctly while running santa 0.9.9 connected to Zentral as TLS server for santa policies/event reporting ( compared to munki and other tools providing similar information ). Noticed for 10.11.4 / 10.11.5 clients tested with some UTF-8 characters in name:
i.e. a Mac named "testømat" will result in "testmat"
or "t€apot" will result in "tapot", etc.

**Comment by russellhancox** [comment]
I just tested both of those hostnames and they uploaded into our backend system without issue. The JSON coming out of Santa just contains the unicode characters in the strings

```js
{"hostname":"testømat"}
```

Which loaded with Python's built-in JSON parser results in:

```py
>>> hostname = json.loads('{"hostname":"testømat"}')['hostname']
>>> hostname
u'test\xf8mat'
>>> print hostname
testømat
```

Has anything in Zentral changed?

**Comment by headmin** [comment]
yes you are correct. when tracking down the issue we've noticed once touched the `hostname` from CLI santa reported exactly the hostname - the confusion popped up when some user machines set hostname from SystemPrefs Pannel (which doesn't allow the characters).
