### ISSUE TITLE
Blacklisted binaries still allowed to run

### ISSUE THREAD

**Issue by mjhuber** [google/santa#457]
I've installed santa on a mac and despite successfully blacklisting a test binary, I'm still able to execute it.  

```
❯ santactl fileinfo ./hello
Path                   : /Users/micahhuber/Downloads/hello
SHA-256                : 29979d015ee7896b2ad78fa5df03fc6dcb435de4cb95a2fb2c4ad4a181f3d2b5
SHA-1                  : ae176018f9c8e0077b3472c0f0ba6ccad4197b20
Type                   : Executable (x86_64)
Code-signed            : No
Rule                   : Blacklisted (Binary)
```
```
❯ ./hello
Hello, World!
```
```
❯ kextstat | grep com.google.santa
  123    0 0xffffff7f83ede000 0x6000     0x6000     com.google.santa-driver (0.9.33) C2EC6FF8-36C1-354C-ABB9-3BFA74B9A718 <6 5 3 1>
```
```
❯ santactl status
>>> Daemon Info
  Driver Connected          | Yes
  Mode                      | Monitor
  File Logging              | No
  Watchdog CPU Events       | 0  (Peak: 7.92%)
  Watchdog RAM Events       | 0  (Peak: 24.88MB)
>>> Kernel Info
  Root cache count          | 39
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 1
  Certificate Rules         | 5
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 4361
```

**Comment by russellhancox** [comment]
What macOS version are you running on?

This is likely caused by TCC changes in 10.15.

**Comment by mjhuber** [comment]
> What macOS version are you running on?
> 
> This is likely caused by TCC changes in 10.15.

this is on `10.15.4`

**Comment by russellhancox** [comment]
Yeah, so what is most likely happening is that TCC is blocking santad from reading the file, so it lets it by (we're adding a flag to change this behavior to default to block). The solution is in System Preferences > Security > Privacy, find Full Disk Access and grant the "santad" binary access. An enterprise would normally do this using a profile distributed by an MDM.

**Comment by mjhuber** [comment]
i added that permission via MDM though i'm still able to run the binary:

![image](https://user-images.githubusercontent.com/19253559/77960792-e0361600-72a6-11ea-8a43-1651491acfe7.png)

**Comment by russellhancox** [comment]
Yeah, that policy doesn't look quite right - it's giving access to system directories but not full disk access so files in your home directory are still blocked. It should look more like this:

![image](https://user-images.githubusercontent.com/69123/77961357-b16c6f80-72a7-11ea-9554-406eab38b28b.png)

**Comment by mjhuber** [comment]
forgive my ignorance, i'm not too familiar with mdm and managing desktop apps.  I actually have that further down in the profile, just didn't think it was as relevant.

![image](https://user-images.githubusercontent.com/19253559/77964332-db746080-72ac-11ea-8367-133837106187.png)

Interestingly though, I tried executing outside of my user dir and it works.  So the only place it _doesn't_ work is within a user directory.

```
❯ cp hello /Applications
❯ /Applications/hello
zsh: operation not permitted: /Applications/hello

Santa

The following application has been blocked from executing
because it has been deemed malicious.

Path:       /Applications/hello
Identifier: 29979d015ee7896b2ad78fa5df03fc6dcb435de4cb95a2fb2c4ad4a181f3d2b5
Parent:     zsh (16533)
```

**Comment by tburgin** [comment]
Can you try adding santa-driver's bundle id too? The TCC checker stuff seems to ignore the santad entry, but should respect the hosting bundle.
```
  "com.google.santa-driver" => {
    "kTCCServiceSystemPolicyAllFiles" => {
      "Allowed" => 1
      "CodeRequirement" => "identifier "com.google.santa-driver" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = EQHXZ8M8AV"
      "CodeRequirementData" => {length = 164, bytes = 0xfade0c00 000000a4 00000001 00000006 ... 5a384d38 41560000 }
      "Comment" => "Allow SystemPolicyAllFiles control for Santa"
      "Identifier" => "com.google.santa-driver"
      "IdentifierType" => "bundleID"
    }
  }
```

**Comment by tburgin** [comment]
FWIW santad will need to be relaunched after the TCC profiles take effect.

**Comment by mjhuber** [comment]
adding santa-driver worked, it now blocks binaries across the entire filesystem.  thanks @tburgin @russellhancox for your help!
