### ISSUE TITLE
An error occurred communicating with the daemon, is it running?

### ISSUE THREAD

**Issue by ngerasimatos** [google/santa#460]
➜  ~ santactl status
An error occurred communicating with the daemon, is it running?
➜  ~ santactl version
santa-driver    | un-needed (SystemExtension being used)
santad          | 1.13
santactl        | 1.13
SantaGUI        | 1.13
➜  ~ sw_vers -productVersion
10.15.5

Approved the software after the installation but santactl still wont work properly.

**Comment by leohidalgo** [comment]
@ngerasimatos check if this is ok

![](https://user-images.githubusercontent.com/2117646/71289447-27714a00-233b-11ea-98a1-71e78425f8cb.png)

**Comment by nl5887** [comment]
And also make sure the system extension is allowed to start:

![Screenshot 2020-04-24 at 09 42 09](https://user-images.githubusercontent.com/3748903/80187436-eef6bb00-860f-11ea-90cc-4da293ae44fe.png)

Executing this will give you some more information about the reason **santad** is not being started.

```cat /var/log/system.log |grep santa```

**Comment by sdoering** [comment]
I have the same problem so far. My system.log shows the following:

`sd@XXX cwd: [/~]  10:19 $ cat /var/log/system.log |grep santa`

```
Aug 24 10:16:07 XXX com.apple.xpc.launchd[1] (com.google.santad): This service is defined to be constantly running and is inherently inefficient.
Aug 24 10:16:07 XXX com.apple.xpc.launchd[1] (com.google.santa.bundleservice): ThrottleInterval set to zero. You're not that important. Ignoring.
Aug 24 10:16:07 XXX com.apple.xpc.launchd[1] (com.google.santa): This service is defined to be constantly running and is inherently inefficient.
	ASL Module "com.google.santa.asl.conf" claims selected messages.
Aug 24 10:16:21 XXX com.apple.xpc.launchd[1] (EQHXZ8M8AV.com.google.santa.daemon): This service is defined to be constantly running and is inherently inefficient.
Aug 24 10:16:51 XXX com.apple.xpc.launchd[1] (EQHXZ8M8AV.com.google.santa.daemon[51060]): Service exited with abnormal code: 4
```

**Comment by russellhancox** [comment]
```
Aug 24 10:16:51 XXX com.apple.xpc.launchd[1] (EQHXZ8M8AV.com.google.santa.daemon[51060]): Service exited with abnormal code: 4
```

Exit code 4 suggests that Santa has not been granted Full-Disk Access. See nl5887's comment just above yours.

**Comment by pmarkowsky** [comment]
Closing as this issue seems stale. If folks are still having issues feel free to reopen.

**Comment by newkton1** [comment]
I am getting the same problem and the application has full disk access. Also the terminal command cat /var/log/system.log |grep santa returns no output!
This is on Monterey 12.2. 

roberthancock@MacBooPro2016-82 ~ % santactl status
An error occurred communicating with the daemon, is it running?
roberthancock@MacBooPro2016-82 ~ % cat /var/log/system.log |grep santa
roberthancock@MacBooPro2016-82 ~ % santactl version
santa-driver    | un-needed (SystemExtension being used)
santad          | 2022.1
santactl        | 2022.1
SantaGUI        | 2022.1

![Screen Shot 2022-02-08 at 11 47 32](https://user-images.githubusercontent.com/13056263/152908517-cfd2116d-afcf-43a1-bda1-2849626da883.png)
Pro2016-82 ~ %

**Comment by newkton1** [comment]
The EQHXZ8M8AV.com.google.santa.daemon does appear to be running accoding to sudo launchcvtl list!

roberthancock@MacBooPro2016-82 ~ % sudo launchctl list
Password:
PID	Status	Label
-	0	com.apple.mobile.obliteration
395	0	com.apple.CoreAuthentication.daemon
192	0	com.apple.coreservicesd
365	0	com.apple.touchbarserver
-	0	com.apple.deleted_helper
-	0	com.apple.avbdeviced
630	0	com.apple.cvmsServ
-	0	com.apple.applessdstatistics
-	0	com.apple.hdiejectd
-	0	com.apple.corestorage.corestoraged
-	0	com.apple.storagekitd
375	0	com.apple.EmbeddedOSInstallService
-	0	com.apple.ospredictiond
-	0	com.apple.storereceiptinstaller
-	0	com.apple.mobileactivationd
707	0	com.apple.seld
-	0	com.apple.emond
393	0	com.apple.iconservices.iconservicesagent
-	0	com.apple.asr
-	0	com.apple.logkextloadsd
141	0	com.apple.syslogd
381	0	com.apple.symptomsd-diag
178	0	com.apple.WindowServer
-	0	com.apple.NetworkSharing
-	0	com.apple.afpfs_checkafp
-	0	com.apple.systemstats.microstackshot_periodic
151	0	com.apple.securityd
152	0	com.apple.auditd
-	0	com.apple.nesessionmanager
-	0	com.apple.cfnetwork.cfnetworkagent
-	0	com.apple.ocspd
227	0	com.apple.symptomsd
156	0	com.apple.autofsd
158	0	uk.co.canimaansoftware.ClamXAV.HelperTool
107	0	com.apple.UserEventAgent-System
-	0	com.apple.Kerberos.kadmind
181	0	com.apple.loginwindow.39E51D48-6340-440E-A8A5-8EA0482BC63F
696	0	com.apple.coresymbolicationd
237	0	com.apple.PerfPowerServicesExtended
360	0	com.apple.suhelperd
-	0	com.apple.RFBEventHelper
-	0	com.apple.racoon
-	0	com.apple.bosreporter
-	0	com.apple.metadata.mds.scan
174	0	com.apple.AirPlayXPCHelper
114	0	com.apple.mediaremoted
-	0	com.apple.mbusertrampoline
-	0	com.apple.RemoteDesktop.PrivilegeProxy
-	0	com.apple.diskimagesiod
-	0	com.apple.accessoryupdaterd
-	0	com.apple.sysdiagnose
-	0	com.apple.installd
-	0	com.apple.system_installd
-	0	com.apple.dvdplayback.setregion
-	0	com.apple.SafeEjectGPUStartupDaemon
226	0	com.apple.nehelper
-	0	com.apple.boswatcher
106	0	com.apple.logd
179	0	com.apple.tccd.system
-	0	com.apple.accessoryd
-	0	com.apple.appleseed.fbahelperd
-	0	com.apple.memory-maintenance
-	0	com.apple.IFCStart
136	0	com.apple.kernelmanagerd
-	0	com.apple.mdmclient.daemon
401	0	com.apple.ctkd
314	0	com.apple.icloud.searchpartyd
-	0	com.apple.xpc.roleaccountd
345	0	com.apple.nsurlsessiond_privileged
238	0	com.apple.awdd
189	0	com.apple.contextstored
245	0	com.apple.mDNSResponderHelper.reloaded
-	0	com.apple.diagnosticextensions.osx.wifi.helper
-	0	com.apple.periodic-monthly
826	0	com.apple.online-authd.xpc
-	0	com.apple.screensharing
-	0	com.apple.findmymacmessenger
149	0	uk.co.canimaansoftware.ClamXAV.Engine
-	0	com.apple.appleh13camerad
582	0	com.apple.nearbyd
-	0	com.apple.CSCSupportd
596	0	com.apple.cloudd
352	0	com.apple.secinitd
-	0	com.apple.kuncd
-	0	com.apple.corecaptured
-	0	com.apple.scsid
-	0	com.apple.IOAccelMemoryInfoCollector
-	0	com.apple.nfrestore
-	0	com.apple.msrpc.lsarpc
-	0	com.apple.diskimagesiod.spb
-	0	com.apple.filesystems.userfs_helper
168	0	com.apple.KernelEventAgent
180	0	com.apple.aslmanager
-	0	com.apple.taskgated-helper
425	0	com.apple.IOUserBluetoothSerialDriver-0x100000990
350	0	com.apple.hidd
-	0	com.apple.RemotePairTool
175	0	com.apple.cmio.registerassistantservice
203	0	com.apple.runningboardd
-	0	com.apple.tzlinkd
-	0	com.apple.XprotectFramework.PluginService
369	0	com.apple.coreservices.appleevents
117	0	com.apple.systemstats.analysis
-	0	com.apple.iomfb_fdr_loader
-	0	com.apple.diagnosticd
658	0	com.apple.AssetCacheTetheratorService
-	0	com.apple.mobilegestalt.xpc
121	0	com.apple.powerd
188	0	com.apple.authd
-	78	com.apple.iomfb_bics_daemon
256	0	com.apple.driver.ethcheck
191	0	com.apple.PowerUIAgent
-	0	com.apple.corekdld
-	0	com.apple.oahd-root-helper
-	0	com.apple.DumpPanic
-	0	com.apple.vsdbutil
-	0	com.apple.mobile.NRDUpdated
-	0	com.apple.nfsd
212	0	com.apple.airportd
217	0	com.apple.audio.coreaudiod
402	0	com.apple.akd
130	0	com.apple.watchdogd
-	0	com.apple.pfd
135	0	com.apple.iconservices.iconservicesd
-	0	com.apple.testmanagerd.remote
-	0	com.apple.InstallerProgress
-	0	com.apple.AXMediaUtilitiesService
-	0	com.apple.nlcd
-	0	com.apple.systemkeychain
-	0	com.apple.filesystems.userfsd
-	0	com.apple.security.agent.login.00000000-0000-0000-0000-0000000186A4
378	0	com.apple.netbiosd
-	0	com.apple.SCHelper
-	0	com.apple.softwareupdate_firstrun_tasks
-	0	com.apple.periodic-weekly
-	0	com.apple.preferences.timezone.admintool
-	0	com.apple.statd.notify
-	0	org.cups.cupsd
943	4	EQHXZ8M8AV.com.google.santa.daemon
-	0	com.apple.appinstalld
-	0	com.apple.noticeboard.state
246	0	com.apple.lsd
335	0	com.apple.metadata.mds.index
148	0	com.apple.timed
150	0	com.apple.usbmuxd
362	0	com.apple.biokitaggdd
691	0	com.apple.CrashReporterSupportHelper
392	0	com.apple.MobileSoftwareUpdate.CleanupPreparePathService
-	0	com.apple.DumpGPURestart
157	0	com.apple.displaypolicyd
-	0	com.apple.powerlogHelperd
-	0	com.apple.wifip2pd
436	0	com.apple.securityd_service
-	0	com.apple.periodic-daily
164	0	com.apple.PerfPowerServices
-	0	com.apple.alf
-	0	com.openssh.sshd
-	0	com.apple.dspluginhelperd
166	0	com.apple.logind
170	0	com.apple.bluetoothd
334	0	com.apple.msrpc.netlogon
110	0	com.google.santa.metricservice
-	0	com.apple.diagnosticextensions.osx.spotlight.helper
569	0	com.apple.logd_helper
-	0	com.apple.TrustEvaluationAgent.system
-	0	com.apple.newsyslog
-	89	com.apple.MRTd
-	0	com.apple.taskgated
428	0	com.apple.GSSCred
400	0	com.apple.audio.systemsoundserverd
119	0	com.apple.configd
380	0	com.apple.captiveagent
-	0	com.apple.diagnosticextensions.osx.getmobilityinfo.helper
394	0	com.apple.AccountPolicyHelper
-	0	com.apple.fontmover
-	0	com.apple.audio.toolbox.reporting.service
-	0	com.apple.ManagedClient.mechanism
-	0	com.apple.oahd
-	0	com.apple.UserNotificationCenter
-	0	com.apple.trustdFileHelper
354	0	com.apple.BlueTool
272	0	com.apple.icloud.findmydeviced
437	0	com.apple.dt.remotepairingdeviced
-	0	com.apple.MobileInstallationHelperService
-	0	com.apple.AppleQEMUGuestAgent
-	0	com.apple.security.authtrampoline
-	0	com.apple.DumpPanic.Accessory
-	0	com.apple.rpcbind
708	0	com.apple.fairplayd
140	0	com.apple.coreduetd
-	0	com.google.santa.bundleservice
-	0	com.apple.DesktopServicesHelper
-	0	com.apple.ucupdate.plist
-	0	com.apple.sysdiagnose_helper
-	0	com.apple.diskimagesiod.ram
-	0	com.apple.ManagedClient.enroll
-	0	com.apple.recoveryos-lockout-service
-	0	com.apple.timezoneupdates.tzd
656	0	com.apple.AssetCache.builtin
-	0	com.apple.powerdatad
-	0	com.apple.memoryanalyticsd
-	0	com.apple.multiversed
-	0	com.apple.siri.acousticsignature
358	0	com.apple.locationd
263	0	com.apple.containermanagerd
660	0	com.apple.rtcreportingd
-	0	com.apple.smbd
-	0	com.apple.Kerberos.kcm
376	0	com.apple.coreservices.sharedfilelistd
-	0	com.apple.BluetoothUIService
-	0	com.apple.efilogin-helper
-	0	com.apple.loginwindow
-	0	com.apple.ReportMemoryException
329	0	com.apple.sysextd
-	0	com.apple.cmio.iOSScreenCaptureAssistant
-	0	com.apple.rapportd
171	0	com.apple.notifyd
-	0	com.apple.wifiFirmwareLoader
113	0	com.apple.fseventsd
-	0	com.apple.Kerberos.digest-service
-	0	com.apple.systempreferences.cacheAssistant
488	0	com.apple.automountd
-	0	com.apple.applefileutil
363	0	com.apple.wifianalyticsd
-	0	com.vix.cron
348	0	com.apple.thermald
467	0	com.apple.FileCoordination
-	0	com.apple.eapolcfg_auth
316	0	com.apple.audio.AudioComponentRegistrar
-	0	com.apple.AssetCacheLocatorService
125	0	com.apple.remoted
-	0	com.apple.InstallerDiagnostics.installerdiagd
346	0	com.apple.softwareupdated
874	0	com.apple.systemadministration.writeconfig
-	0	com.apple.diskmanagementstartup
-	0	com.apple.signpost.signpost_reporter
-	0	com.apple.postfix.master
-	0	com.apple.emond.aslmanager
587	0	com.apple.SubmitDiagInfo
-	0	com.microsoft.office.licensingV2.helper
374	0	com.apple.bootinstalld
-	0	com.apple.mbsystemadministration
-	0	com.apple.XprotectFramework.scan
-	0	com.apple.cmio.AppleCameraAssistant
-	0	com.apple.msrpc.mdssvc
-	0	com.apple.dpd
-	0	com.apple.corestorage.corestoragehelperd
-	0	com.apple.devicemanagementclient.teslad
-	0	com.apple.ReportCrash.Root
183	0	com.apple.trustd
-	0	com.microsoft.OneDriveStandaloneUpdaterDaemon
-	0	com.apple.cmio.IIDCVideoAssistant
187	0	com.apple.security.syspolicy
-	0	com.apple.ioupsd
-	0	fr.madrau.switchresx.helper
258	0	com.apple.biometrickitd
255	0	com.apple.usbd
162	0	com.apple.distnoted.xpc.daemon
236	0	com.apple.mDNSResponder.reloaded
-	0	com.apple.bridgeOSUpdateProxy
-	0	com.apple.bsd.dirhelper
167	0	com.apple.revisiond
-	0	com.daisydiskapp.DaisyDiskStandAlone.AdminHelper
-	0	com.apple.smb.preferences
-	0	com.apple.applecamerad
298	0	com.apple.findmymacd
177	0	com.apple.cfprefsd.xpc.daemon
259	0	com.apple.xartstorageremoted
-	0	com.apple.unmountassistant.sysagent
-	0	com.apple.mobile.notification_proxy
-	0	com.apple.relatived
843	0	com.apple.lskdd
112	0	com.apple.uninstalld
383	0	com.apple.siriinferenced
367	0	com.apple.colorsync.displayservices
421	0	com.apple.xpc.smd
-	0	com.apple.gkreport
120	0	com.apple.endpointsecurity.endpointsecurityd
368	0	com.apple.colorsyncd
244	0	com.apple.backupd
341	0	com.apple.eoshostd
-	0	com.apple.airport.wps
-	0	com.apple.dt.automationmode-writer
176	0	com.apple.MobileFileIntegrity
-	0	com.apple.netauth.sys.auth
-	0	com.apple.nfsconf
127	0	com.apple.mobile.keybagd
-	0	com.apple.filesystems.livefileproviderd
-	0	com.apple.configureLocalKDC
128	0	com.apple.mobile.softwareupdated
584	0	com.apple.spindump
-	0	com.apple.lockd
134	0	com.apple.metadata.mds
-	0	com.apple.wwand
257	0	com.apple.cmio.VDCAssistant
-	0	com.apple.driver.eficheck
-	0	com.apple.printtool.daemon
-	0	com.apple.pfctl
-	0	com.apple.security.authhost
-	0	com.apple.misagent
-	0	com.apple.security.agent.login
-	0	com.apple.ionodecache
144	0	com.apple.thermalmonitord
-	0	com.apple.gssd
347	0	com.apple.driverkit.AppleUserHIDDrivers-0x100000697
-	0	com.apple.remotemanagementd
396	0	com.apple.CryptoTokenKit.ahp
-	0	com.apple.afpfs_afpLoad
147	0	com.apple.coreservices.launchservicesd
-	0	com.apple.dynamic_pager
-	0	com.microsoft.OneDriveUpdaterDaemon
-	0	com.apple.csrutil.report
-	0	com.apple.iokit.ioserviceauthorized
160	0	com.apple.Kerberos.kdc
-	0	com.apple.aned
-	0	com.apple.coreaudio.AudioHistoryXPC
163	0	com.apple.AppleCredentialManagerDaemon
-	0	com.apple.msrpc.srvsvc
-	0	com.apple.tracd
-	0	com.apple.osanalytics.osanalyticshelper
-	0	com.apple.mobile.storage_mounter
-	0	com.apple.bnepd
-	0	com.apple.dpaudiothru
-	0	com.apple.familycontrols
109	0	com.bombich.ccchelper
-	0	com.apple.installcoordination_proxy
-	0	com.apple.diagnosticextensions.osx.timemachine.helper
-	0	com.apple.kcproxy
405	0	com.apple.adid
423	0	com.apple.AmbientDisplayAgent
562	0	com.apple.wifivelocityd
-	0	com.apple.installandsetup.systemmigrationd
-	0	com.apple.BTServer.le
-	0	com.apple.metadata.mds.spindump
-	0	com.apple.Kerberos.kpasswdd
550	0	com.apple.WirelessRadioManager
313	0	com.apple.mobileassetd
-	0	com.apple.nand.aspcarry
-	0	com.apple.InstallerDiagnostics.installerdiagwatcher
-	0	com.apple.UpdateSettings
-	0	uk.co.canimaansoftware.ClamXAV.HelperToolUpdater
-	0	com.apple.msrpc.wkssvc
-	0	com.apple.erasecontentsettingshelperd
-	0	com.apple.mobile.storage_mounter_proxy
-	0	us.zoom.ZoomDaemon
382	0	com.apple.nfcd
-	0	com.apple.warmd
-	0	com.teamviewer.Helper
-	0	com.apple.powerd.swd
-	0	com.apple.ManagedClient
-	0	com.apple.xpc.uscwoap
137	0	com.apple.diskarbitrationd
384	0	com.apple.cmio.uvcassistantextension
-	0	com.apple.dprivacyd
325	0	com.apple.backupd-helper
648	0	com.apple.installcoordinationd
-	0	com.microsoft.autoupdate.helper
-	0	com.apple.netauth.sys.gui
-	0	com.apple.postfix.newaliases
-	0	com.apple.systemstats.daily
-	0	com.apple.startupdiskhelper
247	0	com.apple.ifdreader
145	0	com.apple.opendirectoryd
-	0	com.apple.appstored
-	0	com.apple.DataDetectorsSourceAccess
146	0	com.apple.apsd
-	0	com.apple.security.authhost.00000000-0000-0000-0000-0000000186A4
-	0	com.apple.internal.aupbregistrarservice
-	0	com.apple.ManagedClient.cloudconfigurationd
-	0	com.apple.batteryintelligenced
439	0	com.apple.GameController.gamecontrollerd
649	0	com.apple.AppStoreDaemon.StorePrivilegedTaskService
250	0	com.apple.apfsd
159	0	com.apple.dasd
-	0	com.apple.sessionlogoutd
-	0	com.apple.AssetCacheManagerService
262	0	com.apple.systemstatusd
-	0	com.apple.cmio.AVCAssistant
182	0	com.apple.analyticsd
249	0	com.apple.diskmanagementd
251	0	com.apple.CodeSigningHelper
172	0	com.apple.sandboxd
410	0	com.apple.sysmond
173	0	com.apple.corebrightnessd
248	0	com.apple.tailspind
roberthancock@MacBooPro2016-82 ~ %

**Comment by newkton1** [comment]
Ignore the last 2 posts-the daemon seems to be running now but I have no idea why it suddenly started!
 % santactl status
>>> Daemon Info
  Driver Connected          | Yes
  Mode                      | Monitor
  File Logging              | No
  Watchdog CPU Events       | 0  (Peak: 1.55%)
  Watchdog RAM Events       | 0  (Peak: 29.23MB)
>>> Cache Info
  Root cache count          | 130
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 0
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 0
