### ISSUE TITLE
Incorrect result when checking certificate rule via "santactl rule --check ..."

### ISSUE THREAD

**Issue by serrc-techops** [google/santa#463]
I've blacklisted the Mozilla certificate using:

`santactl rule --blacklist --certificate --sha256 96f18e09d65445985c7df5df74ef152a0bc42e8934175a626180d9700c343e7b`

The blacklisting is successful, Firefox is blocked from loading.

I then do a check on the rule using:

`santactl rule --check --certificate --sha256 96f18e09d65445985c7df5df74ef152a0bc42e8934175a626180d9700c343e7b`

The output of the check is `Whitelisted (Unknown)`.

However, `santctl fileinfo /Applications/Firefox.app` for Rule produces `Blacklisted (Certificate)`.

```
santactl version
santa-driver    | un-needed (SystemExtension being used)
santad          | 1.13
santactl        | 1.13
SantaGUI        | 1.13

**Comment by russellhancox** [comment]
Looks like I broke this in #433, SNTPolicyProcessor took over fetching of the signature for binaries and so the certificate SHA-256 argument became unnecessary and we pass nil. As there's also no filepath being passed in it has no way to fetch the signature itself, so it returns the default rule depending on your client mode.

I'll have to figure out how to fix this gracefully.
