### ISSUE TITLE
Santa Daemon not running after upgrading to 1.13 via Homebrew

### ISSUE THREAD

**Issue by tddschn** [google/santa#485]
macOS version: 10.15.6
santa version: 1.13
Full disk access is enabled for santa, while a kext from developer `Placeholder Developer` is blocked. I'm not sure if it has anything to do with santa and for security I don't want to unblock it and test if santa works.

```zsh
$ sudo santactl rule --blacklist --path /Applications/myapp.app
Password:
An error occurred communicating with the daemon, is it running?

$ ps auxww | grep -i santa
me             17206   0.0  0.0  4269948    756 s012  R+    4:34PM   0:00.01 grep -i santa
me             9638    0.0  0.1  4411828  14924   ??  S     4:07PM   0:01.78 /Applications/Santa.app/Contents/MacOS/Santa --syslog
```
Blocked kexts:
![image](https://user-images.githubusercontent.com/45612704/88640044-11f1a900-d0f0-11ea-9b22-4a3f878dc405.png)

Full disk access:
![image](https://user-images.githubusercontent.com/45612704/88640103-233ab580-d0f0-11ea-95c8-269070bcc726.png)

After upgrading santa to 1.13 with `brew cask upgrade santa`, it stopped working.

I've tried these to fix the issue with no luck:
- `brew cask reinstall santa`
- `brew cask uninstall santa && brew cask install santa`
- `sudo Conf/uninstall.sh && brew cask install santa`

What can I do to make santa daemon run? Thanks!

**Comment by russellhancox** [comment]
I have no idea what the "Placeholder Developer" extension is but that should not be anything to do with Santa.

For version 1.13 on macOS 10.15, Santa will default to using a system extension but it looks like it hasn't loaded properly. Can you provide the output of the following command?

`sudo systemextensionsctl list`

**Comment by tddschn** [comment]
@russellhancox Thanks for the quick reply!
Here's the output:
```zsh
$ sudo systemextensionsctl list
Password:
1 extension(s)
--- com.apple.system_extension.endpoint_security
enabled	active	teamID	bundleID (version)	name	[state]
	*	EQHXZ8M8AV	com.google.santa.daemon (1.13/1.13)	santad	[activated waiting for user]
```

**Comment by russellhancox** [comment]
If I recall correctly `activated waiting for user` means the extension is currently blocked by the OS and is awaiting your approval in the _Security & Privacy_ prefpane under the _General_ tab. If you don't see it there, try running this to load the extension again:

`/Applications/Santa.app/Contents/MacOS/Santa --load-system-extension`

Which should produce a pop-up dialog asking you to authorize the request.

**Comment by tddschn** [comment]
Thank you so much! Turned out it WAS the `Placeholder Developer`:

```zsh
/Applications/Santa.app/Contents/MacOS/Santa --load-system-extension
2020-07-30 00:56:35.657 Santa[14762:3328921] Using your own bundle identifier as an NSUserDefaults suite name does not make sense and will not work. Break on _NSUserDefaults_Log_Nonsensical_Suites to find this
2020-07-30 00:56:35.658 Santa[14762:3328921] Requesting SystemExtension activation
2020-07-30 00:56:35.751 Santa[14762:3328924] SystemExtension "com.google.santa.daemon" request needs user approval
2020-07-30 00:57:00.927 Santa[14762:3328928] SystemExtension "com.google.santa.daemon" request did finish: 0
```
Blocked extension didn't show up when I ran the command, so I unblocked the extension from `Placeholder Developer` and santa worked!! :) 
Still couldn't figure out why it was shown as `Placeholder Developer` instead of `Google LLC` though.

**Comment by russellhancox** [comment]
Yeah that doesn't make sense to me, the output from systemextensionsctl shows the Google TeamID so the signature is correct. Maybe a bug in the OS? Glad you got it working!
