### ISSUE TITLE
does not contain a toolchain for cpu 'darwin_x86_64' ERROR: Analysis of target '//:release' failed; build aborted: Analysis failed

### ISSUE THREAD

**Issue by svinusje** [google/santa#489]
I'm following https://santa.readthedocs.io/en/latest/development/building/ 

but when i try to make a build with Bazel, i get this error message:

![image](https://user-images.githubusercontent.com/57441837/91443635-e3442b00-e873-11ea-93a7-897753b39ab0.png)

**Comment by russellhancox** [comment]
Do you have Xcode or the Developer Command-Line Tools installed? What does `xcode-select -p` output?

**Comment by svinusje** [comment]
output for "xcode-select -p":
/Library/Developer/CommandLineTools

**Comment by russellhancox** [comment]
- What macOS version are you using?

- What bazel version (`bazel info release`)?

- Can you try a `bazel clean --expunge` and then building with `bazel build //:release --announce_rc`?

**Comment by russellhancox** [comment]
Is this still an issue? Can you provide the answers above?

**Comment by ScottifyShopson** [comment]
I am also experiencing this issue, when trying to build 2021.8 on both an Apple M1 Mac and an Intel Mac, and when trying to build main (ad8aafbd07b76406e75fad913b634fa6b3cffe96) on an Intel Mac. Building main on an M1 Mac gets a different error (https://github.com/google/santa/issues/735). 

Here's what I get when building 2021.8 on my M1 Mac:
```sh
➜  santa git:(82b71c0) bazel build //Source/santa_driver
DEBUG: Rule 'build_bazel_rules_apple' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1633038018 -0700"
DEBUG: Repository build_bazel_rules_apple instantiated at:
  /Users/newson/src/github.com/google/santa/WORKSPACE:9:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: /private/var/tmp/_bazel_newson/56b2aa8eaf8cf3df53b3feed9448d4f4/external/local_config_cc/BUILD:48:19: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: Analysis of target '//Source/santa_driver:santa_driver' failed; build aborted: 
INFO: Elapsed time: 3.115s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (60 packages loaded, 470 targets configured)
➜  santa git:(82b71c0) 
```

Here's some system information:
```sh
➜  santa git:(82b71c0) xcode-select --print-path
/Library/Developer/CommandLineTools
➜  santa git:(82b71c0) bazel info release
release 5.0.0-homebrew
➜  santa git:(82b71c0) sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
➜  santa git:(82b71c0) sysctl -n machdep.cpu.brand_string
Apple M1 Pro
```

**Comment by ScottifyShopson** [comment]
Aha, I was not including a cpu architecture in the build command. See https://github.com/google/santa/issues/735#issuecomment-1057344726 for details
