### ISSUE TITLE
Certificate rule check not working in 1.13

### ISSUE THREAD

**Issue by ameyah** [google/santa#499]
Hello,

I just realized the certificate rule check is not working 1.13, the same works in 0.9.32

0.9.32 - 
```
% sudo santactl rule --check --certificate --sha256 2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32
Whitelisted (Certificate)
```

1.13 - 
```
% sudo santactl rule --check --certificate --sha256 2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32
Blacklisted (Unknown)
```

**Comment by russellhancox** [comment]
I believe this is fixed in v1.14, which I just released. Could you give it a try?

**Comment by russellhancox** [comment]
(or [v1.15](https://github.com/google/santa/releases/tag/1.15), which should continue to work)

**Comment by ameyah** [comment]
Yes can confirm. Thank you!
