### ISSUE TITLE
ASL config does not appear to create log file when running in syslog mode

### ISSUE THREAD

**Issue by uptycs-rmack** [google/santa#514]
Hi, I am trying to route the Santa logs through ASL while still keeping a text log file on disk. Configuring Santa to use syslog through a configuration profile works fine. The logs are visible running "log stream". Where I'm having problems is that using the supplied asl.conf file does not appear to be generating an output log file in the expected location. SIGHUP sent to syslogd does show that the santa.asl.conf file is being parsed, but it does not seem to have the desired effect. Adding an additional store line so that the Santa logs get written to the ASL DB also doesn't appear to be doing anything. And writing a dead simple asl.conf for Santa doesn't work either. Tested on Sierra and Big Sur. My best guess is that something about the way that Santa is generating its ASL log entries is making them miss the asl.conf rules intended for them, but I'm having a hard time figuring out how that would be possible.

**Comment by tburgin** [comment]
ASL was replaced by ULS in macOS 10.12. Anything we log to ALS just gets sent over to ULS when running on macOS 10.12 and above. You can use `SNTEventLogTypeFilelog` to send event logs to a file, but the info logs will still be sent to ULS.

https://github.com/google/santa/blob/main/Source/common/SNTConfigurator.h#L141-L149

**Comment by uptycs-rmack** [comment]
Ah, ok, thank you. I thought that if you were still using the deprecated APIs it would still go through the ASL system. Didn't realize it was just a bridge these days. Thank you.
