### ISSUE TITLE
Santa 1.16 release to incorporate recent changes

### ISSUE THREAD

**Issue by radsec** [google/santa#517]
Just wondering if I need to bump the version for a new build to be released or if that is handled by repo owners and there is a slated/scheduled release soon.

Re: #516 and #515
Re Others: 

- #512
- #509
- #505
- #502 
- #501
- #500

**Comment by russellhancox** [comment]
Releases are handled by us once we have enough changes to warrant one and we know there's no pressing work pending. We want to get a fix for #510 committed before the next release.
