### ISSUE TITLE
Broken docs links in GH Pages

### ISSUE THREAD

**Issue by russellhancox** [google/santa#527]
_Originally posted by @headmin in https://github.com/google/santa/issues/480#issuecomment-768301041_

Actually there's two links broken with 404 on the live GH page over at https://santa.dev 
They are already updated in `mkdocs.yml`, work well at ReadTheDocs,  but mkdocs state atm not reflected well on the santa.dev page.

### Binary Authorization
- GH page link broken: https://santa.dev/introduction/binary-authorization.md
- mkdocs.yml, already correct: `- Binary Authorization Overview: introduction/binary-authorization-overview.md`
https://github.com/google/santa/blob/main/mkdocs.yml#L11

### Development
- GH page link: https://santa.dev/CONTRIBUTING.md
- link is no longer present in mkdocs.yml 
https://github.com/google/santa/blob/main/mkdocs.yml#L15
```
- Development:
  - Building: development/building.md
```

**Comment by headmin** [comment]
I ran ino another broken link here: <https://santa.readthedocs.io/en/latest/details/santactl/#sync>
When in current readthedocs `santctl` section about sync, a link results in a 404 - Page not found. 

I guess this should link to <https://github.com/google/santa/blob/main/docs/introduction/syncing-overview.md>
