### ISSUE TITLE
Santa showing the block dialog only the first time when self-managed cache is enabled

### ISSUE THREAD

**Issue by ameyah** [google/santa#532]
Santa version - 2021.1

Steps to reproduce -
1. Enable Santa Lockdown and enable the self-managed cache
2. Execute a UNKNOWN binary; Santa dialog will pop up
3. Execute the same binary again; Santa dialog doesn't show up, silently blocks the binary, and doesn't show up in `santa.log`

**Comment by russellhancox** [comment]
Please check-out the v2021.2 release, which includes the fix.
