### ISSUE TITLE
santactl fileinfo results on binaries suddenly includes "Bundle Name/Version/Version Str" printed in 2021.x releases

### ISSUE THREAD

**Issue by headmin** [google/santa#536]
Curious to notice with last 2021.x Santa releases the output of `santactl fileinfo` getting info about any unsigned and signed binaries looks a bit odd,  well least different to the former 1.1x Santa versions.

Observation made running on several macOS 10.15.7 computers here (checking behaviour in macOS11 not done yet).

We do see keys for "Bundle Name", "Bundle Version",  "Bundle Version Str" in the resulting output:

Bundle Name            : santactl
Bundle Version         : 2021.2
Bundle Version Str     : 2021.2

Could be it's like that for a valid reason I don't know about.

We just tried here i.e. on unsigned binaries like `gh` cli, `jq` cli, but also on signed `terraform` binaries.

In contrast on a signed App  `santactl fileinfo` the keys for "Bundle Name", "Bundle Version",  "Bundle Version Str" output value match the App details Santa collects info about and as to be expected prints  "Bundle Name", "Bundle Version",  "Bundle Version Str" for the app accordingly.

Would be great to know if this is the expected behaviour from now on or something as result of a bug, so gets reverted back to former `santactl fileinfo` output as seen in older Santa versions.

--

See the familiar`santactl fileinfo` from fomer Santa version 1.17:

<img width="643" alt="Screenshot 2021-01-29 at 16 43 26" src="https://user-images.githubusercontent.com/46750/106298777-9dd9be80-6254-11eb-8e8e-50e42a6f4a8c.png">

And in contrast variations from Santa both 2021.2 release:

<img width="720" alt="Screenshot 2021-01-29 at 16 55 10" src="https://user-images.githubusercontent.com/46750/106299033-f90bb100-6254-11eb-9ce8-4ead716e24a9.png">

<img width="867" alt="Screenshot 2021-01-29 at 17 05 47" src="https://user-images.githubusercontent.com/46750/106299065-02951900-6255-11eb-8005-b9e066278767.png">

and one test result from a client in "lockdown" mode, connected to TLS sync server

<img width="1235" alt="Screenshot 2021-01-29 at 16 49 45" src="https://user-images.githubusercontent.com/46750/106300001-36247300-6256-11eb-983d-b7397fdfe8de.png">

finally same client again with "santa configuration" completely removed (lifted the profile on mdm server side)
![Image 29 01 21 at 17 25](https://user-images.githubusercontent.com/46750/106300909-54d73980-6257-11eb-8458-fbf5c6b6d8a1.png)

**Comment by russellhancox** [comment]
This is definitely a bug, it seems to affect `/usr/local/bin` in particular because of the `santactl` symlink.

**Comment by russellhancox** [comment]
Interesting: `[NSBundle bundleWithPath:@"/usr/local/bin]` returns an invalid bundle **unless** the binary being executed is inside `/usr/local/bin` (even as a symlink) and it has an embedded Info.plist, which santactl does. I'm not sure whether this is a change to NSBundle behavior or this was introduced as a result of fixing embedded plist parsing. Either way, I've opened a PR that should prevent this, which will be included in the next release.

**Comment by russellhancox** [comment]
(by the way: thank you for the very detailed bug report!)
