### ISSUE TITLE
M1 ARM binary support

### ISSUE THREAD

**Issue by thehesiod** [google/santa#541]
just checked the most recent release and it doesn't seem like ARM is supported yet

**Comment by russellhancox** [comment]
The latest release is a universal binary. What are you seeing that's unexpected?

**Comment by thehesiod** [comment]
ah ok, I did a check on santa-2021.2.dmg and it seemed like it was not:
```
/tmp/santa $ otool -vf Applications/Santa.app/Contents/MacOS/Santa 
/tmp/santa $ file Applications/Santa.app/Contents/MacOS/Santa
Applications/Santa.app/Contents/MacOS/Santa: Mach-O 64-bit executable x86_64
```
perhaps I did something wrong

**Comment by tburgin** [comment]
v1.17, v2021.1 and v2021.2 are all universal builds - maybe the version you are inspecting is an older version?

```
plutil -extract CFBundleVersion xml1 -o - /Applications/Santa.app/Contents/Info.plist
```
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<string>2021.2</string>
</plist>
```

**Comment by thehesiod** [comment]
ya weird, I did it again and worked!  sorry for disruption
