### ISSUE TITLE
Permanently disable notification when a blacklisted binary's execution is blocked?

### ISSUE THREAD

**Issue by tddschn** [google/santa#542]
I use santa to block a binary that is invoked by a launchd job of a GUI app, and only remove the rule when I need to use that app. I need to select `disable notification for this app for 24 hours` everyday or I'll get very frequent santa pop-up notification, which is kind of annoying. Is there a way to permanently disable notification when a blacklisted binary's execution is blocked?

**Comment by headmin** [comment]
There is a “silent- block” option. Have you tried that ?

https://github.com/google/santa/blob/d17aeac2f4331584db51de432ace3465026e1259/Source/santactl/Commands/SNTCommandRule.m#L54

**Comment by tddschn** [comment]
Thank you! I think that's exactly what I need. :)
