### ISSUE TITLE
Is there a way to view all created rules in one place?

### ISSUE THREAD

**Issue by tddschn** [google/santa#544]
I'm having trouble using a GUI app. I remember silently blocking some of the binaries required by the app and have removed the associated rules after that, but the app still doesn't function as expected. 

I ran `tail -F /var/db/santa/santa.log` and launched the app but nothing is shown blocked, but I think I might still be missing some of the blocking rules. 

Is there a way to view all created rules in one place to help debugging this issue? Thanks!

**Comment by russellhancox** [comment]
We purposefully didn't include a way to easily list all the rules on a machine, it seemed like making it too easy to avoid. We could maybe add one that only works when not syncing to a server and requires root to run.

You should be able to see any blocking by Santa in the logs even if silently blocking (the silent part only refers to the GUI/TTY notifications); how about:

`tail -F /var/db/santa/santa.log | grep "action=EXEC|decision=DENY"`

**Comment by tddschn** [comment]
> We purposefully didn't include a way to easily list all the rules on a machine, it seemed like making it too easy to avoid.

@russellhancox May I ask why you decided not to include that feature?
