### ISSUE TITLE
Santa not recognizing the client certificate in the system keychain

### ISSUE THREAD

**Issue by ameyah** [google/santa#553]
Hello Santa devs,

I have been seeing this issue with some Santa clients. The problem doesn't seem to be with the certificate - other apps (like Chrome) can access the same client certificate.

Sync log:

```
Preflight starting
Clean sync requested by user
Performing request, attempt 1
Server Trust: <server-trust>
Server asked for client authentication but no usable client certificate found.
Failed to decode JSON response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Preflight complete
Event upload starting
Performing request, attempt 1
Failed to decode JSON response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Uploaded 3 events
Event upload complete
Rule download starting
Performing request, attempt 1
Failed to decode JSON response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Rule download failed, aborting run
```

The cert CN matches with the `ClientAuthCertificateCN` value. `find-certificate` does locate that certificate

```
$ /usr/bin/security find-certificate -a -c <cn> -m -Z':
SHA-256 hash: B0319D238A72933EC5C3C2EE430F696F5DAD32E05CBC1C1575DE619ABCAF5097
<redacted>
    "labl"<blob>="<cn>"
    ...
```

Any other logs that might help the debugging?

Thanks!

**Comment by ameyah** [comment]
FWIW adding a new certificate (and deleting the previous one) with the same CN sometimes works, but is unreliable.

**Comment by russellhancox** [comment]
Does `sudo security find-identity -v` list the certificate?

**Comment by ameyah** [comment]
Found the issue:

The previous certificates (expired at this point) with the same CN were seemingly deleted with `security delete-certificate`. The private key isn't deleted as per the documentation, but it seems the certificate isn't deleted as well, just hidden from the keychain UI. `security find-certificate` does show up the expired certificate.

My theory is Santa is picking up the older certificate, but doesn't use it because its expired.

We are using `security delete-identity` to remove the older certs, but can Santa also look for all certificates matching the CN instead of the first one?

**Comment by russellhancox** [comment]
> My theory is Santa is picking up the older certificate, but doesn't use it because its expired.

Ah interesting, that could be it. The filtering should probably filter out any expires certs.

> an Santa also look for all certificates matching the CN instead of the first one

We can only present a single cert in the response so the filtering has to ultimately select an identity somehow. One way we could improve this would be to find all identities and then order by most recently issued, which I'm guessing would have solved the problem here?

**Comment by ameyah** [comment]
> One way we could improve this would be to find all identities and then order by most recently issued, which I'm guessing would have solved the problem here?

Yup, that would have worked.

**Comment by russellhancox** [comment]
v2021.5 contains the fix for this.
