### ISSUE TITLE
Team ID Based Rules

### ISSUE THREAD

**Issue by pmarkowsky** [google/santa#634]
We'd like to extend rule types in Santa to incorporate Team IDs. This allows us to block / allow entire teams.

## Proposed New Rule Precedence (in-order of highest to lowest)
- SHA256
- Certificate
- Team ID

## Steps to Completion
- [x] Update `SNTEventState` enum in `SNTCommonEnums` to include new entries for rule types
- [x] Update `SNTPolicyProcessor` `decisionForFileInfo`  to also take team ID
- [x] Update santactl rule command to allow adding / viewing the new rule types
- [x] Update santactl sync command to allow retrieving rules of the new types.
- [x] Update notifications / logging to display why something was blocked / allowed based on the new rules

**Comment by pmarkowsky** [comment]
@tnek what's left for this?

**Comment by np5** [comment]
It seems that TeamID (or CDHash) rule downloads are not supported:

https://github.com/google/santa/blob/6f2ae62bcecd0067b911ac97df09e475af1521eb/Source/santasyncservice/SNTSyncRuleDownload.m#L135-L139

Are there any plans to add this functionality?
