### ISSUE TITLE
Running sync clean in parallel with multiple pages of rules can corrupt rule database

### ISSUE THREAD

**Issue by thehesiod** [google/santa#653]
we have an issue where if you run `sync --clean` in parallel the first process will finish multiple pages of 50 to yield >700 rules, whereas the second set will have its pagination terminated early and yield ~500 rules, and committing this to the local repository.  A query at this point will yield ~500 rules, and in incremental sync will not download the missing rules, only a further `--clean` will reset the database to ~700 rules.

**Comment by thehesiod** [comment]
btw I also validated that if we have the syncservice running in the background, and then a user runs `--clean`, then you can get into a similar scenario.

**Comment by pmarkowsky** [comment]
That makes sense the sync service isn't really implemented. That said I'm hope to get more time to work on the transition to the sync service that @russellhancox  talked about next week.

**Comment by tburgin** [comment]
Work is underway!
