### ISSUE TITLE
Feature Request - Change install location away from /Applications

### ISSUE THREAD

**Issue by fauxserve** [google/santa#660]
Since the Santa.app does not have any user accessible functionality, can it be moved to a location less visible?
Maybe /Applications/Utilities or /Library/Application Support or something like that?

Since it should operate silently, it only invites discussions from users back to IT with "why is this here" that causes extra tickets. For many places "out of sight out of mind" makes software deployments easier when the users don't notice what happens.

**Comment by tburgin** [comment]
Unfortunately the System Extension system requires that the hosting app be installed in Applications. 

https://developer.apple.com/documentation/systemextensions/installing_system_extensions_and_drivers?language=objc
