### ISSUE TITLE
how can i stop it

### ISSUE THREAD

**Issue by yuluofan** [google/santa#691]
I wanted to uninstall the program, but there was a process that kept restarting automatically.
the process name is 'com.google.santa.daemon'

**Comment by arubdesu** [comment]
Try the uninstall script, https://github.com/google/santa/blob/main/Conf/uninstall.sh

**Comment by yuluofan** [comment]
i have try ,but this process will still restart automatically

**Comment by yuluofan** [comment]
This process is acting like a rogue

**Comment by arubdesu** [comment]
I'm not good with rogue-likes myself, (maybe something is reinstalling it?) but launchd uses jobs in the directory this line in the uninstall script references:

`/bin/rm -f /Library/LaunchDaemons/com.google.santad.plist`

launchctl would also have unloaded it. 
If you've restarted the computer post-uninstall and the job is still running, then yes, your computer may benefit from further looking into what's launching the process. I would either check out the file system/logs, throw it into the ocean, or use utilities like KnockKnock, Lingon, or LaunchControl to figure out what's going on.
