### ISSUE TITLE
Return string incorrect, when santactl rule --block --identifier <teamID> is used

### ISSUE THREAD

**Issue by headmin** [google/santa#699]
If Santa is run in standalone and the new TeamID `santactl rule --block --identifier <teamID_here>` is used, the return will be a string with the content "Added rule for SHA-256: <teamID_here>".
 
The return looks a bit misleading, as of course a teamID is stored in the sqlite DB as expected, no sha-256 is added  

The exact string that will be printed on return can be found in the if/else section in Commands/SNTCommandRule.m:
https://github.com/google/santa/blob/d20455252d4c43de52c7ef12c295c413b5ebe21a/Source/santactl/Commands/SNTCommandRule.m#L189

**Comment by pmarkowsky** [comment]
Marking closed as #701 should fix this.
