### ISSUE TITLE
How to purge events from events.db when using santactl locally (without a sync server)

### ISSUE THREAD

**Issue by imkaihao** [google/santa#705]
I use santa in monitor mode locally(without a sync server). Events in events.db accumulate and they can't be purged. So the size of events.db now grows to dozens of GB.

So how can I purge events from events.db or even disable generating events, since I won't evaluate those events later.

Here is my status
```
➜  ~ santactl status
Failed to retrieve some stats from daemon

>>> Daemon Info
  Driver Connected          | Yes
  Mode                      | Monitor
  File Logging              | No
  Watchdog CPU Events       | 3  (Peak: 140.07%)
  Watchdog RAM Events       | 0  (Peak: 164.69MB)
>>> Cache Info
  Root cache count          | 146
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 22
  Certificate Rules         | 0
  TeamID Rules              | 0
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | -1
```

**Comment by tburgin** [comment]
Good question. Without unloading Santa's System Extension I don't think there is a way to clear out the events.db.

I think these FRs would would wonderful:
* Add a events clear command to santactl
* Add an option to disable storing events in events.db.

These shouldn't be hard to add. Marking this issue as a FR.

**Comment by tburgin** [comment]
In the mean time you can manually clear out the events.db like this:
```sh
/Applications/Santa.app/Contents/MacOS/Santa --unload-system-extension
sudo rm -rf /var/db/santa/events.db
/Applications/Santa.app/Contents/MacOS/Santa --load-system-extension
```

**Comment by tburgin** [comment]
Chatted with @russellhancox about this. We are thinking about making this change:

* If you don't have a sync server set we will not store events. For folks who don't use a sync server it doesn't make sense to store events. In fact it probably makes things worse if you ever wanted to add sync server at a later date. You would have a huge backlog of events to upload.
* If we do implement this, it will not be retroactive. We will not clear out any events currently stored in the events.db. While possible there are too many edge cases to make this feasible.
