### ISSUE TITLE
Wiki tweaks - blacklistregex example, update fileinfo commands/clarify expected output  

### ISSUE THREAD

**Issue by arubdesu** [google/santa#71]
On Getting Started and Configuration, there's incorrect syntax for adding a BlacklistRegex:
```sh
$ sudo defaults write /var/db/santa/config.plist BlacklistRegex '^(?:/Users)/.*'
Password:
2016-08-28 15:25:52.813 defaults[1324:124497] Could not parse: ^(?:/Users)/.*.  Try single-quoting it.
``` 

With the new fileinfo output, we should update the syntax for gathering a leaf cert sha256 in step 2 of Getting Started's Recommended Deployment section. 
I also think we should clarify that if the daemon is stopped, you wouldn't see Rule information in fileinfo full output, to proactively address what could be a FAQ for the nervous.

**Comment by russellhancox** [comment]
Done
