### ISSUE TITLE
How to create a rule that blocks USB mass storage mounting

### ISSUE THREAD

**Issue by newkton1** [google/santa#724]
I have the latest Santa beta running on Monterey 12.2 and have read the section on creating rules but am at a loss about creating a local rule to block mounting of USB mass storage.
Could someone point me in the right direction with a For Dummies explanation.
I did find this referenced elsewhere but the explanation is a bit thin.

block_usb_mass_storage	Bool	If set to 'True' blocking USB Mass storage feature is enabled. Defaults to False.

**Comment by tnek** [comment]
This feature doesn't support granular blocking of individual devices - it'll block/remount all devices.

To use it, enable the BlockUSBMount (and the RemountUSBMode if you'd like to enable that too) in your Santa configuration profile. Here's an example of a profile with this enabled: https://github.com/google/santa/blob/main/Testing/com.google.santa.mobileconfig#L19

**Comment by newkton1** [comment]
Thank you for the link tnek.
