### ISSUE TITLE
discussion - BannedBlockMessage not applicable when BlacklistRegex rule triggered

### ISSUE THREAD

**Issue by arubdesu** [google/santa#74]
I think I'm not clearing the launchagent properly while testing, so I'm therefore having some difficulty reproducing what I'm talking about cleanly, but I'm hoping to make end users less concerned while in trial data-gathering mode. During this time, I'm pretty sure I want path-based blocks to use the UnknownBlockMessage instead of Banned, as it is more applicable to the reality of what users have encountered. (i.e., there isn't an explicit blacklist entry for the binary/dev cert, but instead is just being launched from a blacklist path that doesn't have an explicitly whitelisted binary/cert.)
It almost makes sense to me that the common case would instead call for the default message when a BlacklistRegex rule is triggered should be what the UnknownBlockMessage is unless overridden, as that may be more faithful to the recommended workflow admins should be encouraged to follow. I don't want this to be death by a thousand customizations, but would PathBlockMessage be a useful pref to expose?

**Comment by russellhancox** [comment]
You could configure the _BannedBlockMessage_ to have the same text as _UnknownBlockMessage_ if that's what you want. I see path-based blocks as something you've explicitly said you want not to run, i.e. banned, rather than being blocked because it was unknown which would be the message for it being blocked in lockdown.

**Comment by arubdesu** [comment]
Sure, as configs should be updated anyway I can understand avoiding pref bloat.
