### ISSUE TITLE
santametricservice running after uninstall

### ISSUE THREAD

**Issue by ronnieleblanc** [google/santa#740]
I'm doing some testing with the latest Santa release (2022.2) and I noticed after running the [uninstall script](https://github.com/google/santa/blob/main/Conf/uninstall.sh) the `servicemetricservice` is still running in activity monitor. Not sure if this is unintended or something we've missed on our own side of things.

Pre removal script
![Screen Shot 2022-03-07 at 3 41 38 PM](https://user-images.githubusercontent.com/17990847/157121271-17ef6405-95d2-42f1-a6ba-6dd422671baf.png)

Post removal script
![Screen Shot 2022-03-07 at 3 42 15 PM](https://user-images.githubusercontent.com/17990847/157121280-1aebf577-3997-438c-8f32-2dfffd34720d.png)

**Comment by pmarkowsky** [comment]
Thanks, that was an oversight. This should be fixed once #743 is merged.

**Comment by ronnieleblanc** [comment]
Awesome thanks for the heads up!
