### ISSUE TITLE
How to temporarily disable santa?

### ISSUE THREAD

**Issue by CaledoniaProject** [google/santa#75]
I need to install XtraFinder and but santa blocked the execution of preflight binary

![screen 2016-08-29 at 21 22 53](https://cloud.githubusercontent.com/assets/1357701/18052770/d35cae88-6e2e-11e6-9f79-d9f106d59a29.jpg)

I tried to remove the config file completely, nothing changes.

```
sudo rm -f /var/db/santa/config.plist
```

Is there a way to temporarily disable Santa?

**Comment by arubdesu** [comment]
`sudo launchctl unload /Library/LaunchDaemons/com.google.santad.plist`

**Comment by tddschn** [comment]
@arubdesu 

How do I do this with santa `2022.8`?

I've unloaded all the plists I can find, but the process `/Library/SystemExtensions/DE5679A3-EF30-4695-A0C1-C3219E45418C/com.google.santa.daemon.systemextension/Contents/MacOS/com.google.santa.daemon` keeps running.

`brew uninstall santa`, which is supposed to unload and remove the plists / kext, did not stop the `com.google.santa.daemon` process.

**Comment by arubdesu** [comment]
This is a closed issue, please open a new one if you're having a new issue. https://github.com/google/santa/blob/main/Conf/uninstall.sh is the approved removal method, but if you remove all rules and confirm that santa is not in lockdown mode and no configurations are enforcing restrictions it should be noop. You may need to restart after removing a system extension before it stays quiet.
