### ISSUE TITLE
Problem with the daemon

### ISSUE THREAD

**Issue by secureinfo42** [google/santa#780]
# Problem with the daemon

Hello, I have the problem, that I don't know how to solve, I tried to reinstall ,to remove SystemExtension with `systemextensionsctl`, to start manually, and to create the exemple profile from the doc, but I still the error :

```
An error occurred communicating with the daemon, is it running?
```

Is there a easy way to install and use Google Santa like the previous build (1.15) ?

*Edit : i'm on macOS Monterey, using Little Snitch, Murus, Macports

**Comment by russellhancox** [comment]
Is the daemon running? You can use `systemextensionsctl list` and `ps -ef | grep com.google.santa.daemon` to see. 

+ If it *is* running and you're getting this error, make sure you've enabled Full Disk Access for the daemon (either by way of a profile or manually). 

+ If it *isn't* running, is it listed in the output of systemextensionsctl at all? Is it showing up in the Security & Privacy pane of system preferences as awaiting approval?

**Comment by secureinfo42** [comment]
Here is what I have :

```
$ sudo systemextensionsctl list|grep santa
*	*	EQHXZ8M8AV	com.google.santa.daemon (2022.3/2022.3.436270740)	santad	[activated enabled]
```

No results in process :
```
$ sudo ps -ef |grep -v grep | grep com.google.santa.daemon
```

I approved the extensions.

When I want to load the daemon `launchctl load -w /Library/LaunchDaemons/com.google.santad.plist`
the file `/Library/LaunchDaemons/com.google.santad.plist` is removed.

And when I try to manually launch the daemon :

```
# /Applications/Santa.app/Contents/Library/SystemExtensions/com.google.santa.daemon.systemextension/Contents/MacOS/com.google.santa.daemon --syslog
2022-04-18 14:59:17.792 Santa[2309:20548] Requesting SystemExtension activation
2022-04-18 14:59:17.822 Santa[2309:20550] SystemExtension "com.google.santa.daemon" request did finish: 0
```

**Comment by russellhancox** [comment]
Manually launching the daemon should not work. Do you see any crash reports in /Library/Logs/DiagnosticReports? If you run the ps command multiple times do you see the daemon running briefly?

**Comment by secureinfo42** [comment]
> Manually launching the daemon should not work. Do you see any crash reports in /Library/Logs/DiagnosticReports? If you run the ps command multiple times do you see the daemon running briefly?

Hi, sorry, i don't have my Mac, i'll reinstall macOS when I get it back, then I'll check it again. I'll keep you in touch

**Comment by secureinfo42** [comment]
Hi, a lot of weird things happened in my system after my hardening tries. Had to reinstall it. So I installed Google Santa again before hardening scripts (which are drafts), and it works.
For you to know, after my hardening scripts, i have :

```
/dev/disk6 on /private/var/tmp (hfs, local, nodev, noexec, nosuid, nobrowse)
/dev/disk5 on /private/var/log (hfs, local, nodev, noexec, nosuid, nobrowse)
/dev/disk3s7 on /Library/Cache (apfs, local, nodev, noexec, nosuid, journaled, nobrowse, protect)
/dev/disk3s8 on /Users/Shared (apfs, local, nodev, noexec, nosuid, journaled, nobrowse, protect)
```

**Comment by russellhancox** [comment]
That is, indeed, an unusual setup. Those mounts should have no impact on Santa though.
