### ISSUE TITLE
Upload event logs while `clean_sync` is set.

### ISSUE THREAD

**Issue by j-steig** [google/santa#789]
When `clean_sync` is set to true, event logs aren't uploaded.

This prevents us from leaving `clean_sync` on all the time since no logs will show up.

Can there be a way of allowing event uploads to occur during while that flag is set so that it can be on all the time and still collect data?

**Comment by russellhancox** [comment]
That should be easy enough to add as a configurable option.

**Comment by russellhancox** [comment]
This will be included in the 2022.5 release, which is slated for the event of this month.
