### ISSUE TITLE
PrinterProxy & Santa Integrations

### ISSUE THREAD

**Issue by spbkaizo** [google/santa#814]
We're having issues with Santa and it's interactions with 'PrinterProxy'.  Users (and ourselves) are reporting they can't open the 'Print Queue' from the SysPreferences printing pane.

We're on the latest Santa release, running in 'lockdown' mode and we've never had much luck with the interactions between the two - indeed, we've ignored the problem for quite some time but we've got a point where we need to get 'PrinterProxy' working again.

We've tried adding the location to the allowed regex'es, and have also toggled enable/disable bad signature protection controls, to no avail.

If we completely remove Santa from an affected machine, we can interact with the 'Open Print Queue' setting pane once again.

Is this expected behaviour, and are there any work arounds to try and correct this?

**Comment by russellhancox** [comment]
Background: When you add a new printer to the machine it makes a copy of a template PrinterProxy app but modifies it for the particular printer you've added and is then re-signed with a per-system certificate. We have found that the modification is unnecessary and copying the "original" over the top fixes the signature and allows the print queue to function normally. When Santa sees you executing PrinterProxy from ~/Library/Printers or /Library/Printers it will perform this copy automatically and then reject the original execution request, so the second attempt to open the print queue _should_ work. 

This workaround still seems to be working for us, so a few questions:

1. Which version of macOS are you using? 
2. Does Santa show a block dialog or is the "print queue" button appearing to do nothing? What if you click the "Open Print Queue" button multiple times?
3. Does `/var/db/santa/santa.log` show any attempts at executing PrinterProxy?

**Comment by spbkaizo** [comment]
So it's consistenly inconsistent 👎 

1) A whole mix, but generally 12.3,12.3.1, 12.4 as of today.  For now, we'll use my machine which is on 12.4 as of this morning.
2) It depends :-) (see below)
3) Yep - some samples below.

Initially today I've had the 'block dialog' box appear today, you can see the decision here:

`[2022-05-17T08:12:55.869Z] I santad: action=EXEC|decision=DENY|reason=CERT|explain=Blocked due to signature error: -67030|sha256=7dacb7493f9e1e02121be12093ad39600bd57a32b96adb238460b7d2c4099465|pid=8164|pidversion=18506|ppid=1|uid=501|user=first.lastname|gid=20|group=staff|mode=L|path=/Users/first.lastname/Library/Printers/XXXXXX-REDACTED-MODEL.app/Contents/MacOS/PrinterProxy`

Then, I've removed the printer and re-added it, then observed the 'first' exec silently failing, then tried to open it again.  After this the icon did a bounce for a while, before ultimately being killed by a 'SIGKILL'.  I'll attach the trace.  

```
[2022-05-17T08:46:45.203Z] I santad: action=EXEC|decision=ALLOW|reason=BINARY|explain=critical system binary|sha256=34c8c1a6d767e1144a482db61fc2d0552e9e6dfd5f7477d80d0939b79d397328|cert_sha256=d84db96af8c2e60ac4c851a21ec460f6f84e0235beb17d24a78712b9b021ed57|cert_cn=Software Signing|pid=12424|pidversion=27714|ppid=1|uid=0|user=root|gid=0|group=wheel|mode=L|path=/usr/libexec/xpcproxy|args=xpcproxy application.com.apple.print.PrinterProxy.3619041.3619222
[2022-05-17T08:47:35.773Z] I santad: action=EXEC|decision=ALLOW|reason=BINARY|explain=critical system binary|sha256=34c8c1a6d767e1144a482db61fc2d0552e9e6dfd5f7477d80d0939b79d397328|cert_sha256=d84db96af8c2e60ac4c851a21ec460f6f84e0235beb17d24a78712b9b021ed57|cert_cn=Software Signing|pid=12524|pidversion=27933|ppid=1|uid=0|user=root|gid=0|group=wheel|mode=L|path=/usr/libexec/xpcproxy|args=xpcproxy application.com.apple.print.PrinterProxy.3619041.3619222
[2022-05-17T08:48:17.819Z] I santad: action=EXEC|decision=ALLOW|reason=CERT|sha256=7dacb7493f9e1e02121be12093ad39600bd57a32b96adb238460b7d2c4099465|cert_sha256=d84db96af8c2e60ac4c851a21ec460f6f84e0235beb17d24a78712b9b021ed57|cert_cn=Software Signing|pid=12524|pidversion=27934|ppid=1|uid=501|user=first.lastname|gid=20|group=staff|mode=L|path=/Users/first.lastname/Library/Printers/XXXXXX-REDACTED-MODEL.app/Contents/MacOS/PrinterProxy|args=/Users/first.lastname/Library/Printers/XXXXXX-REDACTED-MODEL.app/Contents/MacOS/PrinterProxy
```



A colleague has seen the same behaviour I described, however today when testing their machine appears to load the app successfully.  I asked another colleague to add a printer, theirs did work using the 'two-click-trick'.

Debug info:
```Process:             PrinterProxy [12524]
Path:                /Users/USER/Library/Printers/XXXXXX-REDACTED-MODEL.app/Contents/MacOS/PrinterProxy
Identifier:          com.apple.print.PrinterProxy
Version:             20 (594)
Code Type:           ARM-64 (Native)
Role:                Background
Parent Process:      launchd [1]
Coalition:           com.apple.print.PrinterProxy [2961]

Date/Time:           2022-05-17 09:48:17.7410 +0100
Launch Time:         2022-05-17 09:47:35.7486 +0100
OS Version:          macOS 12.4 (21F79)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Subtype: UNKNOWN_0x32 at 0x000000010287c000
Exception Codes: 0x0000000000000032, 0x000000010287c000
VM Region Info: 0x10287c000 is in 0x10287c000-0x102880000;  bytes after start: 0  bytes before end: 16383
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  mapped file                 10287c000-102880000    [   16K] r-x/r-x SM=COW  ...t_id=77337575
      mapped file                 102880000-102884000    [   16K] rw-/rw- SM=COW  ...t_id=77337575
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 2 
```

**Comment by spbkaizo** [comment]
@russellhancox thanks - have shared the dumps.

**Comment by spbkaizo** [comment]
Hi @russellhancox no probs - have deployed it and behaviour is as expected.

We'll selectively push it out to all our users after a few days testing and see how it goes.

**Comment by russellhancox** [comment]
Hey @spbkaizo, did you have any luck with this test release? We're nearing the point of cutting a release for 2022.6 and we'd love to be able to declare this issue fixed, if it is 😄

**Comment by spbkaizo** [comment]
We've not had any negative reports, observations do indicate it's a fix for the issue.  Happy to close it, and thanks for the fix!
