### ISSUE TITLE
Add BUILD rules for fuzz tests

### ISSUE THREAD

**Issue by russellhancox** [google/santa#815]
We have fuzz tests in the repo but they're not buildable by the existing BUILD rules (they were originally added with cmake rules but those got out of date quickly). 

https://github.com/bazelbuild/rules_fuzzing is a good start though it doesn't support macOS out of the box.

**Comment by pmarkowsky** [comment]
Minor update on this.

After including the `rules_fuzzing`, the main blocker, is that libfuzzer isn't packaged with XCode.  We can work around this by `brew installing llvm` in the GitHub VMs. 

Past that we need to update the fuzzing tests source, create BUILD files etc.

**Comment by pmarkowsky** [comment]
@kallsyms figured out that we can just install libfuzzer in the local xcode and it works. #976 does this and uses `rules_fuzzing`.
