### ISSUE TITLE
santa-0.9.13 symlink incorrect

### ISSUE THREAD

**Issue by MrGeek81** [google/santa#82]
**Error:** /usr/local/bin is a symlink to the santactl file instead of /usr/local/bin/santactl being the symlink.

**Reason:** During the postinstall script for santa-0.9.13.pkg a symlink is created with the command `/bin/ln -sf /Library/Extensions/santa-driver.kext/Contents/MacOS/santactl /usr/local/bin` which incorrectly creates /usr/local/bin as the link if /usr/local/bin does not exist as a directory prior to installing the package.

**How to reproduce:** Install the santa-0.9.13.pkg without first having a /usr/local/bin directory such as on a clean install of macOS 10.11.

**Comment by russellhancox** [comment]
This will be fixed in the next release, sorry for the trouble.
