### ISSUE TITLE
ES message deadline handler bug

### ISSUE THREAD

**Issue by uptycs-brian** [google/santa#821]
I was doing a code review and noticed that the ES AUTH deadline handler does not copy the ES message. According to the ES docs the original message is only guaranteed to be valid within the ES callback scope. The deadline handler executes outside this scope. So this could potentially lead to a missed auth response and crash if the deadline is reached (assuming ES actually free's the scoped message):

`
  es_new_client_result_t ret = es_new_client(&client, ^(es_client_t *c, const es_message_t *m) {
  // ...
          dispatch_after(dispatch_time(m->deadline, NSEC_PER_SEC * -5), self.esAuthQueue, ^(void) {
            if (responded->load()) return;
            LOGE(@"Deadline reached: deny pid=%d ret=%d", pid,
                 es_respond_auth_result(self.client, m, ES_AUTH_RESULT_DENY, false));
          });
          // Copy the message and return control back to ES
          es_message_t *mc = es_copy_message(m);
  //...
  }
`

**Comment by russellhancox** [comment]
This can only only cause problems on macOS 10.15, on 11+ es_copy_message is an alias of es_retain_message. As we're calling that a few lines below the original message (that is then referenced inside the block) is valid until we release it.

I'll send a PR to fix.

**Comment by russellhancox** [comment]
Thank you for the report and feedback while we worked through the pull request, much appreciated!

**Comment by uptycs-brian** [comment]
No problem. Async code can be horribly tricky. I ended up using a double-atomic solution instead (an additional one to protect the `free` with no polling).
