### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by MatthewFromKiszkowo** [google/santa#867]
Hey, 

I would like to uninstall this app from my computer which I bought from eBay, and I can't afford this.
Could You be so kind and advice what to do in an easy way.

Reinstaling OS didn't helped.
When I try to open this app, appears communicate - this app is working in system,
When I try to uninstall - appears info that app is open.

Best regards,
Mateusz

**Comment by russellhancox** [comment]
Reinstalling the OS will remove Santa. The only reason that wouldn't work is if the machine is MDM-managed by an organization and auto-enrollment is reinstalling that organization's management tools.

If you open "System Preferences" and then the "Profiles" preference pane, does it say "This Mac is supervised and managed by ..." in the lower left corner? If so, the Mac is owned by an organization and you'll need to contact them to determine what to do.
