### ISSUE TITLE
Blacklist Applications basted on exact location

### ISSUE THREAD

**Issue by GameEnder** [google/santa#87]
Would it be possible to add the ability to blacklist applications based on specific location path instead of hash. Such as a application in "/Applications/Safari.app" with that exact path and name could not be ran.

Enabling you to blacklist applications, that constantly being updated such stock Apple apps without having to constantly update the hash ever time they update.

edit:fixed :)

**Comment by arubdesu** [comment]
Currently the only way to achieve what you're asking is a BlacklistRegex. https://github.com/google/santa/wiki/Configuration#whitelistregexblacklistregex
Note that there can only be one entry, so that could get really long, and the end user could just move the app to another un-blacklisted-path to run it. I'm not sure but I'd be concerned about webkit breaking if you blacklisted safari… 
Also I think you have a typo in your first sentence.

**Comment by GameEnder** [comment]
I was looking at BlacklistRegex in the wiki, but from my understanding it is for blacklisting specific folders from running programs not files. So i could block "/Applications" but not "/Applications/Safari.app"

I am attempting to block Safari to prevent our teachers and kids at our school from using Safari instead of Chrome, as Safari has compatibility problems with some google apps and a lot of testing software. From what I tested all other webkit apps such as the Appstore ran fine if I blocked Safari using Santa.

**Comment by arubdesu** [comment]
Bundle apps like Safari are folders... I don't have great regex resources off the top of my head, but you can use it to do what you're trying to accomplish.

**Comment by arubdesu** [comment]
Do you still require assistance with this issue? The intended use of Santa may fall outside of your needs, but if you're controlling the patches applied to machines you should be able to maintain a blacklist of hashes. Safari updates with the OS, and that only is every two months or so if historical data is any indication.

**Comment by GameEnder** [comment]
I guess not. I ended up creating a script to periodically remove and reapply the Line for Safari aver few weeks to work around the problem.
