### ISSUE TITLE
Missing SyncBaseURL. Can't sync without it.

### ISSUE THREAD

**Issue by eopeter** [google/santa#898]
`Missing SyncBaseURL. Can't sync without it.`

this is reported by `sudo santactl sync` when using a sync server. No further details with `--debug` flag. 

`santactl status` shows there is a SyncUrl. Rebooting resolves the issue. This happens right after applying a new .mobileconfig when there was no sync server and then adding one with sync server

**Comment by pmarkowsky** [comment]
How are you applying the `.mobileconfig`?  Also are you changing the `SyncBaseURL` when applying the new config?

You shouldn't need to restart your machine. Santa _should_ pick this up from a config change. Worst comes to worst you should just have to restart Santa.

That error messages comes from:

https://github.com/google/santa/blob/cc3177502c1729530f134769a9dcc223c3db3680/Source/santasyncservice/SNTSyncManager.m#L333-L337

`santactl status` retrieves that value from:

https://github.com/google/santa/blob/d6c73e0c6cfcffcad1ac9fc849624bd4a40a03b4/Source/santactl/Commands/SNTCommandStatus.m#L173 

Both come from `SNTConfigurator's syncBaseURL` method:

https://github.com/google/santa/blob/d6c73e0c6cfcffcad1ac9fc849624bd4a40a03b4/Source/common/SNTConfigurator.m#L593-L598

Which gets its state from the application config profile. And is watching for updates with KVO.

https://github.com/google/santa/blob/d6c73e0c6cfcffcad1ac9fc849624bd4a40a03b4/Source/common/SNTConfigurator.m#L298

**Comment by eopeter** [comment]
I double clicked to install it. I am going from No SyncUrl to SyncUrl in the new config. So not really change the value but switching from local mode to using sync server.

Yes i did expect it to pick up the change right away since the status shows the sync Url right away after apply the profile.

**Comment by pmarkowsky** [comment]
@eopeter you can do `sudo launchctl stop EQHXZ8M8AV.com.google.santa.daemon` to stop the daemon. It'll restart automatically.

**Comment by eopeter** [comment]
Thank you!!
