### ISSUE TITLE
【Question】please tell me，the ide is？xcode appcode

### ISSUE THREAD

**Issue by rockingl** [google/santa#899]
Hi，i want to know，santa used ide？xcode or appcode.
I use AppCode, but i can't find correct way to configuration and compilation santa.
Mayme someone can tell me correctly way. thanks!

**Comment by arubdesu** [comment]
Santa is built with [bazel](https://bazel.build)... but you can assume configuration interacts with at least the xcode CLI tools at some point. I believe some devs use or have used VSCode as an IDE.

**Comment by pmarkowsky** [comment]
Most of the Santa team uses VSCode.

**Comment by pmarkowsky** [comment]
Wanted to elaborate on this more.

As @arubdesu pointed out, we use [bazel](https://bazel.build/) to build and drive clang/xcode. For development  a lot of the Santa team uses VSCode with [hedron's bazel compile commands extractor](https://github.com/hedronvision/bazel-compile-commands-extractor) to get support for completion etc.
