### ISSUE TITLE
Moroz Rule Not Showing After Santa Sync

### ISSUE THREAD

**Issue by eopeter** [google/santa#901]
Why is the rule set returned by Moroz not being accepted by Santa? What am I missing? Note that this does not use WhiteList but Allow. Is this json a valid Santa rule?

```json
{
	"rules": [{
		"type": "BINARY",
		"state": "ALLOW",
		"identifier": "ab737383d8ab3cc783bb4edf4ddf85486077106d69b35d89866ae866944bb69b",
		"custommsg": "Allows Xcode - Testing"
	}]
}

```

**Comment by pmarkowsky** [comment]
It's close but not quite. 

As defined in the [sync protocol docs](https://santa.dev/development/sync-protocol.html#rule-download).  The `state` key isn't expected and should be `policy`: where valid values are one of “ALLOWLIST”,”ALLOWLIST_COMPILER”, “BLOCKLIST”, “REMOVE”, “SILENT_BLOCKLIST”

The rule object is required to have the fields:  `identifier`, `policy` and `rule_type`. 

## Example Payload for `/rulesdownload`

```json
{
	"rules": [{
		"identifier": "ff2a7daa4c25cbd5b057e4471c6a22aba7d154dadfb5cce139c37cf795f41c9c",
		"rule_type": "CERTIFICATE",
		"policy": "BLOCKLIST",
		"custom_msg": "My custom message",
		"creation_time": 1573543803.349378}]
}
```

**Comment by eopeter** [comment]
Thank you!!
