### ISSUE TITLE
Sync Server Download Disk I/O Error

### ISSUE THREAD

**Issue by eopeter** [google/santa#906]
I am running a sync with `sudo santactl sync --debug` and getting the following error:

```
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Received 1 rules
Failed to add rule(s) to database: A database error occurred while inserting/replacing a rule
Failure reason: disk I/O error
Rule download failed, aborting run
```

How do I see more details on whats wrong? My `santactl status` is shown below:

```
>>> Daemon Info
  Mode                      | Monitor
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 1  (Peak: 33.11%)
  Watchdog RAM Events       | 0  (Peak: 197.93MB)
>>> Cache Info
  Root cache count          | 551
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 0
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 0
>>> Sync Info
  Sync Server               | https://localhost:18380/v1/santa/
  Clean Sync Required       | Yes
  Last Successful Full Sync | Never
  Last Successful Rule Sync | Never
  Push Notifications        | Disconnected
  Bundle Scanning           | Yes
  Transitive Rules          | Yes
```

**Comment by russellhancox** [comment]
A disk I/O error would suggest something wrong with the database file or the directory it's stored in. Could you provide the output of `ls -al /var/db/santa`?

**Comment by russellhancox** [comment]
I see `rules_copy.db` there, has `rules.db` been overwritten at some point? The `rules.db-journal` file is part of the database file and if `rules.db` is modified separately at any point (including being copied and later copied back) it will break the integrity of the journal and could lead to I/O errors.

**Comment by eopeter** [comment]
rules.db was never overwritten. rules_copy.db is a copy of rules.db we use to read the current rules using Osquery. Had to make a copy in order to be able to read the data.

**Comment by eopeter** [comment]
Seems the process of copying the rules.db changed the integrity of the the database and causing the issue. Starting from a fresh install resolves the issue

**Comment by eopeter** [comment]
This seems to be happening across reinstall of Santa even after removing the copy functionality. So it is working and then I remove Santa using the install script and then reinstall it from the installer package and then it is not able to write to the database.
