### ISSUE TITLE
How to uninstall santa completely?

### ISSUE THREAD

**Issue by qiaoxueshi** [google/santa#92]

**Comment by arubdesu** [comment]
Hey Joey, an uninstall script is provided [here](https://github.com/google/santa/blob/master/Conf/uninstall.sh).

**Comment by russellhancox** [comment]
Let us know if that doesn't work for you.

**Comment by qiaoxueshi** [comment]
@arubdesu @russellhancox 
Thanks, it works for me.

**Comment by nimdajitam** [comment]
Running it with sudo gave me command not found error or something like that. Running each task from script manually with root priviledges worked well.

**Comment by tburgin** [comment]
You prob need to set the executable bit.
chmod a+x uninstall.sh
