### ISSUE TITLE
EnableSilentMode Not Working

### ISSUE THREAD

**Issue by eopeter** [google/santa#925]
Setting EnableSilentMode = True in the .mobileconfig still allows the Santa Notification Window to show when a binary is blocked. I need to suppress the Santa GUI when Santa blocks a binary. Is that now the right configuration parameter to set? 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.google.santa</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
							         <key>EnableSilentMode</key>
							         <true/>
								<key>BannedBlockMessage</key>
								<string>This application has been blocked</string>
								<key>ClientMode</key>
								<integer>1</integer>
								<key>EnablePageZeroProtection</key>
								<false/>
								<key>EventDetailText</key>
								<string>Open sync server</string>
								<key>EventDetailURL</key>
								<string>https://localhost:18380/santa/blocked/%file_sha%</string>
```

So, even with the `EnableSilentMode` set to `true`, I still get the following pop up
<img width="586" alt="image" src="https://user-images.githubusercontent.com/2012979/199068916-a7c19cba-212d-4bcb-8fcb-9d7b2abd3457.png">

**Comment by russellhancox** [comment]
PR #927 fixes this, which will be included in the 2022.10 release

**Comment by eopeter** [comment]
Is there an estimate on when 2022.10 will be released?

**Comment by russellhancox** [comment]
A pre-release of 2022.10 has been uploaded (https://github.com/google/santa/releases/tag/2022.10). It'll be marked as fully released later in the week, unless we discover any issues.

**Comment by eopeter** [comment]
I just installed the Pre-Release and on block, the UI does not sure but it breaks #869 as my notification observer of blocked does not see the notification. Is the UI showing tied to blocked notification observers getting notified?

**Comment by russellhancox** [comment]
@eopeter I've fixed that issue but unfortunately it's late in the 2022.10 release cycle for the fix to be included. However, we're starting the 2022.11 release and hope to have that published by the middle of next week.

**Comment by russellhancox** [comment]
A pre-release of 2022.11 has been uploaded (https://github.com/google/santa/releases/tag/2022.11). Would you mind testing this version to see if it works for you?

**Comment by eopeter** [comment]
Will do and report back. Thank you!On Nov 21, 2022, at 1:56 PM, Russell Hancox ***@***.***> wrote:﻿
A pre-release of 2022.11 has been uploaded (https://github.com/google/santa/releases/tag/2022.11). Would you mind testing this version to see if it works for you?

**Comment by eopeter** [comment]
This is tested and works as desired with the Prelease. Thank you!!
