### ISSUE TITLE
Rule State Not Maintained Through Reboots When Using Sync Server

### ISSUE THREAD

**Issue by eopeter** [google/santa#926]
I have a configuration that uses a sync server. I access the sync server over a VPN and on reboot, the VPN is not available. What I found out is that when the sync server is available the rules work but on reboot, the binaries that were previously blocked are no longer blocked.

# Before Rebooting with Sync Server Recently Accessed
<img width="446" alt="image" src="https://user-images.githubusercontent.com/2012979/199078158-7e60a7f8-3132-4e4c-ace1-5cec0a0952aa.png">

# After Rebooting with Sync Server Not Accessible
Previously blocked binaries before reboot is allowed and `santactl status` shows:
```
>>> Daemon Info
  Mode                      | Monitor
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 1  (Peak: 26.31%)
  Watchdog RAM Events       | 0  (Peak: 170.48MB)
>>> Cache Info
  Root cache count          | 336
  Non-root cache count      | 0
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 0
  TeamID Rules              | 0
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 190
>>> Sync Info
  Sync Server               | http://localhost:18380/v1/santa/
  Clean Sync Required       | Yes
  Last Successful Full Sync | 2022/10/31 13:14:48 -0400
  Last Successful Rule Sync | 2022/10/31 13:14:48 -0400
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Rules          | Yes
```

It then works fine once the sync happens and the rules are downloaded again from the sync server. I'd think it should hold the state of the last known rules in the absence of the sync server if configured to use a sync server.

**Comment by eopeter** [comment]
Maybe because of `Clean Sync Required`?

**Comment by russellhancox** [comment]
Santa stores the rules in the database, the availability of the sync server should have no impact on the stored rules. Clean Sync Required indicates that _when_ a sync happens, any existing rules will be deleted before applying the latest ruleset but that happens as a transaction, so again there shouldn't be a case where the set of rules drops back to 0.

After a reboot, can you look in Console.app for log messages from `com.google.santa.daemon`? One possible cause of this is that the database file is corrupt or unreadable during startup and so is being replaced by a new clean database. Given that you've also opened #906, I suspect that whatever is causing the database corruption you're seeing there, is also causing this.
