### ISSUE TITLE
Sync Server TLS Issue

### ISSUE THREAD

**Issue by eopeter** [google/santa#946]
I am trying to establish communication with the Sync Server over TLS and possibly mTLS but does not seem to be working without pinning the server cert (highly disruptive in a distributed environment for all clients).

#### For TLS. 
I set `ServerAuthRootsFile` in the mobile config to the path of the CA bundle that signed the server cert. When I attempt to sync, I get the following error:
```
Performing request, attempt 5
Server Trust: /O=XXXX/OU=Tools/CN=XXX.com/SHA-1=232a490318851befb42cd6cca0f34c98dbdf2206
Server Trust: Server isn't trusted. SecTrustResultType: 5
Unable to verify server identity.
```
I verified the ca bundle cert using openssl and int was OK using the following command:
```
openssl verify -CAfile path/to/ca/bundle.crt -untrusted path/to/ca/bundle.crt path/to/ca/bundle.crt
```
One suggestion which I do not love is to disable ATS for the sync server domain. If I were to do that, what info.plist will I make the change to?

#### For mTLS
I set the following configuration to achieve mTLS communication between the client and sync server. Is this correct? I have a client.crt and client.key and do not have a password. How do I supply the client.key file?
```xml
<key>ServerAuthRootsFile</key>
<string>/path/to/ca/bundle.crt</string>
<key>ClientAuthCertificateFile</key>
<string>/client/cert/path.crt</string>
<key>ClientAuthCertificatePassword</key>
<string></string>
```

**Comment by russellhancox** [comment]
> `Server Trust: Server isn't trusted. SecTrustResultType: 5`

result type 5 == `kSecTrustResultRecoverableTrustFailure`, which means the certificate received from the server was not considered trusted using the available roots. Is the certificate served by the server signed by one of the certificates in your bundle file and are the certificates in that bundle in order?

> I verified the ca bundle cert using openssl and int was OK using the following command:

The 3 paths in this command are the same, it isn't clear this is verifying anything. You may be able to verify the server directly using s_client:

```
openssl s_client -CAfile ca.pem -connect yourserver.com:443
```

> One suggestion which I do not love is to disable ATS for the sync server domain. If I were to do that, what info.plist will I make the change to?

This doesn't appear to be an ATS problem, based on the return codes you're getting.

> I have a client.crt and client.key and do not have a password. How do I supply the client.key file

Santa supports either having your identity in the keychain or in a pkcs#12 file (which contains both cert and key). For the latter, you don't _have_ to use a password but it is recommended. If you have the cert and key as separate files, you need to merge them:

```
openssl pkcs7 -in client.crt -print_certs -out client.pem
openssl pkcs12 -export -out client.p12 -inkey client.key -in client.pem
```

The last command will ask for a new password, which is what you'd enter in the `ClientAuthCertificatePassword` field.

**Comment by eopeter** [comment]
> Is the certificate served by the server signed by one of the certificates in your bundle file and are the certificates in that bundle in order?

Yes. Just to be sure I paired it down to only the relevant certificates and was able to connect using something like

`openssl s_client -CAfile ca.pem -connect yourserver.com:443`

But still getting:

```
eoche-mn1:parts eoche$ sudo santactl sync --debug
Missing Machine Owner.
Preflight starting
Performing request, attempt 1
Server Trust: /O=XXXX/OU=Tools/CN=XXX.com/SHA-1=232a490318851befb42cd6cca0f34c98dbdf2206
Server Trust: Server isn't trusted. SecTrustResultType: 5
Unable to verify server identity.
```

**Comment by eopeter** [comment]
Sync is now returning a different error but still not working with TLS:

```
Preflight starting
Performing request, attempt 1
Server Trust: /O=DDDDD/OU=Tools/CN=X.XXXX.com/SHA-1=5b23eb88cbb3a61f78421071acdd41bffecb0a1f
Client Trust: /O=(null)/OU=Users/CN=XXXX/SHA-1=93b56c146ff4ef142ee3d3ec44d5a4e04c54ff0e
Performing request, attempt 2
Performing request, attempt 3
Performing request, attempt 4
```

Not sure if this helps to point me in right direction

**Comment by eopeter** [comment]
I tried verifying the ServerAuthRootsFile against the cert presented by the server and it validates but continue to get `Unable to verify server identity` with Santa Sync. Need some help on how to get info on what exactly is wrong

```
openssl verify -verbose -CAfile /XXX/XXX/ca-bundle.crt /Users/XXX/certs/server.crt 
/Users/XXX/certs/server.crt : OK
```

**Comment by russellhancox** [comment]
The error in [#issuecomment-1343452628](#issuecomment-1343452628) is different from the one in [#issuecomment-1353441018](#issuecomment-1353441018) - the former has passed TLS checks and is being rejected by the server for a different reason, while the latter is failing TLS.

You can collect all the logs from the sync service while running a sync to see what the system frameworks are reporting:

```
sudo log stream --process santacsyncservice | tee syncservice.log
(In a separate tab): sudo santactl sync --debug
```

The log will include lots of messages from Network, CFNetwork and libboringssl; there will be many warnings but if you search for `santasyncservice: Server Trust` and then work backwards you should be able to find the relevant error. If not, try adding `--info` to the log stream command and try again.  If you prefer, you can mail the log file to `santa-team@google.com` and I'll take a look.

**Comment by russellhancox** [comment]
As discussed over e-mail, this was caused by the presented server certificate not adhering to Apple's policies baked into the OS frameworks. The 2023.1 release of Santa will surface these issues much more clearly so that it won't be necessary to trawl through verbose framework logs to track this down.

If replacing the cert does not fully resolve the issue, please re-open.
