### ISSUE TITLE
Create a Signing ID rule type

### ISSUE THREAD

**Issue by pmarkowsky** [google/santa#956]
### Discussed in https://github.com/google/santa/discussions/828

Add a bundle ID / Signer ID rule type to Santa.

<div type='discussions-op-text'>

<sup>Originally posted by **np5** June 24, 2022</sup>
Type: `BUNDLEID`
Identifier: `TEAM_ID:BUNDLE_ID` (`43AQ936H96:org.mozilla.firefoxdeveloperedition`)

Pros:
 * Be able to target all versions of an application
 * All the information to make the decision is already in the SNTFileInfo
 * No need to change the sync protocol</div>

**Comment by russellhancox** [comment]
If this is going to use the `signing_id` field from ES then it should be called `SIGNING_ID` to indicate that it may not _always_ be the bundle ID.
